// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAccessSession = `-- name: CreateAccessSession :exec
INSERT INTO access_sessions (id,user_id,project_id,client_session_id,session_type,state,descriptor,expires_at,idempotency_key)
VALUES ($1,$2,$3,nullif($4,''),$5,'active',$6::jsonb,$7,$8)
`

type CreateAccessSessionParams struct {
	ID              string
	UserID          string
	ProjectID       string
	ClientSessionID interface{}
	SessionType     string
	Descriptor      json.RawMessage
	ExpiresAt       time.Time
	IdempotencyKey  string
}

func (q *Queries) CreateAccessSession(ctx context.Context, arg CreateAccessSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAccessSession,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.ClientSessionID,
		arg.SessionType,
		arg.Descriptor,
		arg.ExpiresAt,
		arg.IdempotencyKey,
	)
	return err
}

const getAgentunnelResource = `-- name: GetAgentunnelResource :one
SELECT tunnel_id,client_id,resource_id,metadata FROM agentunnel_resources WHERE project_id=$1
`

type GetAgentunnelResourceRow struct {
	TunnelID   string
	ClientID   string
	ResourceID string
	Metadata   json.RawMessage
}

func (q *Queries) GetAgentunnelResource(ctx context.Context, projectID string) (GetAgentunnelResourceRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentunnelResource, projectID)
	var i GetAgentunnelResourceRow
	err := row.Scan(
		&i.TunnelID,
		&i.ClientID,
		&i.ResourceID,
		&i.Metadata,
	)
	return i, err
}

const getLatestProjectStopEventType = `-- name: GetLatestProjectStopEventType :one
SELECT event_type FROM project_events WHERE project_id=$1 AND event_type LIKE 'project.stop_queued.%' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestProjectStopEventType(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestProjectStopEventType, projectID)
	var event_type string
	err := row.Scan(&event_type)
	return event_type, err
}

const gitHubConfigReady = `-- name: GitHubConfigReady :one
SELECT EXISTS (SELECT 1 FROM github_oauth_tokens t JOIN github_config_repositories cr ON cr.user_id = t.user_id
WHERE t.user_id = $1 AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at > now()) AND cr.provisioned_at IS NOT NULL)
`

func (q *Queries) GitHubConfigReady(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, gitHubConfigReady, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasConnectCredits = `-- name: HasConnectCredits :one
SELECT coalesce(ca.balance, 0)::numeric >= (((($1::bigint)::numeric / 3600.0) * mtv.credit_weight)::numeric(18,6))
FROM projects p JOIN project_runtime_configs prc ON prc.project_id = p.id
JOIN machine_type_versions mtv ON mtv.id = prc.applied_machine_type_version_id
LEFT JOIN credit_accounts ca ON ca.user_id = p.user_id
WHERE p.id = $2 AND p.user_id = $3
`

type HasConnectCreditsParams struct {
	WindowSeconds int64
	ProjectID     string
	UserID        string
}

func (q *Queries) HasConnectCredits(ctx context.Context, arg HasConnectCreditsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasConnectCredits, arg.WindowSeconds, arg.ProjectID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const recordConnectionEvent = `-- name: RecordConnectionEvent :exec
INSERT INTO connection_events (id,user_id,project_id,access_session_id,result,failure_reason,metadata)
VALUES ($1,nullif($2,''),nullif($3,''),nullif($4,''),$5,$6,$7::jsonb)
`

type RecordConnectionEventParams struct {
	ID              string
	UserID          interface{}
	ProjectID       interface{}
	AccessSessionID interface{}
	Result          string
	FailureReason   string
	Metadata        json.RawMessage
}

func (q *Queries) RecordConnectionEvent(ctx context.Context, arg RecordConnectionEventParams) error {
	_, err := q.db.ExecContext(ctx, recordConnectionEvent,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.AccessSessionID,
		arg.Result,
		arg.FailureReason,
		arg.Metadata,
	)
	return err
}

const revokeClientAccessSessions = `-- name: RevokeClientAccessSessions :exec
UPDATE access_sessions SET state='revoked',revoked_at=coalesce(revoked_at,now()),updated_at=now(),version=version+1,
descriptor=jsonb_set(descriptor,'{revocation_reason}',to_jsonb($1::text),true)
WHERE client_session_id=$2 AND state='active' AND revoked_at IS NULL
`

type RevokeClientAccessSessionsParams struct {
	Reason          string
	ClientSessionID sql.NullString
}

func (q *Queries) RevokeClientAccessSessions(ctx context.Context, arg RevokeClientAccessSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeClientAccessSessions, arg.Reason, arg.ClientSessionID)
	return err
}

const revokeProjectAccessSessions = `-- name: RevokeProjectAccessSessions :exec
UPDATE access_sessions SET state='revoked',revoked_at=now(),updated_at=now(),version=version+1,
descriptor=jsonb_set(descriptor,'{revocation_reason}',to_jsonb($1::text),true)
WHERE state='active' AND revoked_at IS NULL AND project_id=$2
`

type RevokeProjectAccessSessionsParams struct {
	Reason    string
	ProjectID string
}

func (q *Queries) RevokeProjectAccessSessions(ctx context.Context, arg RevokeProjectAccessSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeProjectAccessSessions, arg.Reason, arg.ProjectID)
	return err
}

const revokeUserAccessSessions = `-- name: RevokeUserAccessSessions :exec
UPDATE access_sessions SET state='revoked',revoked_at=now(),updated_at=now(),version=version+1,
descriptor=jsonb_set(descriptor,'{revocation_reason}',to_jsonb($1::text),true)
WHERE state='active' AND revoked_at IS NULL AND user_id=$2
`

type RevokeUserAccessSessionsParams struct {
	Reason string
	UserID string
}

func (q *Queries) RevokeUserAccessSessions(ctx context.Context, arg RevokeUserAccessSessionsParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserAccessSessions, arg.Reason, arg.UserID)
	return err
}

const upsertAgentunnelResource = `-- name: UpsertAgentunnelResource :exec
INSERT INTO agentunnel_resources (id, project_id, tunnel_id, client_id, resource_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
ON CONFLICT (project_id) DO UPDATE SET tunnel_id=EXCLUDED.tunnel_id,client_id=EXCLUDED.client_id,resource_id=EXCLUDED.resource_id,
metadata=EXCLUDED.metadata,version=agentunnel_resources.version+1,updated_at=now()
`

type UpsertAgentunnelResourceParams struct {
	ID         string
	ProjectID  string
	TunnelID   string
	ClientID   string
	ResourceID string
	Metadata   json.RawMessage
}

func (q *Queries) UpsertAgentunnelResource(ctx context.Context, arg UpsertAgentunnelResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentunnelResource,
		arg.ID,
		arg.ProjectID,
		arg.TunnelID,
		arg.ClientID,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const upsertPreviewURLRecord = `-- name: UpsertPreviewURLRecord :exec
INSERT INTO preview_url_records (id, project_id, preview_key, target_url, public_url, state)
VALUES ($1, $2, 'papercode', $3, $4, 'active')
ON CONFLICT (project_id, preview_key) DO UPDATE SET target_url=EXCLUDED.target_url,public_url=EXCLUDED.public_url,state='active',version=preview_url_records.version+1,updated_at=now()
`

type UpsertPreviewURLRecordParams struct {
	ID        string
	ProjectID string
	TargetUrl string
	PublicUrl string
}

func (q *Queries) UpsertPreviewURLRecord(ctx context.Context, arg UpsertPreviewURLRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertPreviewURLRecord,
		arg.ID,
		arg.ProjectID,
		arg.TargetUrl,
		arg.PublicUrl,
	)
	return err
}

const upsertProjectActivity = `-- name: UpsertProjectActivity :exec
INSERT INTO project_activity_markers (project_id,last_activity_at,source,metadata)
VALUES ($1,now(),$2,$3::jsonb)
ON CONFLICT (project_id) DO UPDATE SET last_activity_at=greatest(project_activity_markers.last_activity_at,EXCLUDED.last_activity_at),
source=EXCLUDED.source,metadata=EXCLUDED.metadata,updated_at=now()
`

type UpsertProjectActivityParams struct {
	ProjectID string
	Source    string
	Metadata  json.RawMessage
}

func (q *Queries) UpsertProjectActivity(ctx context.Context, arg UpsertProjectActivityParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectActivity, arg.ProjectID, arg.Source, arg.Metadata)
	return err
}
