// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAccessSession = `-- name: CreateAccessSession :exec
INSERT INTO access_sessions (id,user_id,project_id,cli_client_session_id,helper_terminal_session_id,helper_file_session_id,session_type,state,descriptor,http_base_url,expires_at,idempotency_key)
VALUES ($1,$2,$3,nullif($4,''),nullif($5,''),nullif($6,''),$7,'active',$8::jsonb,$9,$10,$11)
`

type CreateAccessSessionParams struct {
	ID                      string
	UserID                  string
	ProjectID               string
	CLIClientSessionID      interface{}
	HelperTerminalSessionID interface{}
	HelperFileSessionID     interface{}
	SessionType             string
	Descriptor              []byte
	HttpBaseUrl             string
	ExpiresAt               time.Time
	IdempotencyKey          string
}

func (q *Queries) CreateAccessSession(ctx context.Context, arg CreateAccessSessionParams) error {
	_, err := q.db.Exec(ctx, createAccessSession,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.CLIClientSessionID,
		arg.HelperTerminalSessionID,
		arg.HelperFileSessionID,
		arg.SessionType,
		arg.Descriptor,
		arg.HttpBaseUrl,
		arg.ExpiresAt,
		arg.IdempotencyKey,
	)
	return err
}

const createHelperRevocationOutbox = `-- name: CreateHelperRevocationOutbox :exec
INSERT INTO helper_revocation_outbox
(id,user_id,project_id,cli_client_session_id,http_base_url,session_ids,reason)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type CreateHelperRevocationOutboxParams struct {
	ID                 string
	UserID             string
	ProjectID          string
	CLIClientSessionID string
	HttpBaseUrl        string
	SessionIds         []string
	Reason             string
}

func (q *Queries) CreateHelperRevocationOutbox(ctx context.Context, arg CreateHelperRevocationOutboxParams) error {
	_, err := q.db.Exec(ctx, createHelperRevocationOutbox,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.CLIClientSessionID,
		arg.HttpBaseUrl,
		arg.SessionIds,
		arg.Reason,
	)
	return err
}

const getLatestProjectStopEventType = `-- name: GetLatestProjectStopEventType :one
SELECT event_type FROM project_events WHERE project_id=$1 AND event_type LIKE 'project.stop_queued.%' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestProjectStopEventType(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRow(ctx, getLatestProjectStopEventType, projectID)
	var event_type string
	err := row.Scan(&event_type)
	return event_type, err
}

const getProviderRouteResource = `-- name: GetProviderRouteResource :one
SELECT tunnel_id,client_id,resource_id,metadata FROM provider_routes WHERE project_id=$1
`

type GetProviderRouteResourceRow struct {
	TunnelID   string
	ClientID   string
	ResourceID string
	Metadata   []byte
}

func (q *Queries) GetProviderRouteResource(ctx context.Context, projectID string) (GetProviderRouteResourceRow, error) {
	row := q.db.QueryRow(ctx, getProviderRouteResource, projectID)
	var i GetProviderRouteResourceRow
	err := row.Scan(
		&i.TunnelID,
		&i.ClientID,
		&i.ResourceID,
		&i.Metadata,
	)
	return i, err
}

const gitHubConfigReady = `-- name: GitHubConfigReady :one
SELECT EXISTS (SELECT 1 FROM github_oauth_tokens t JOIN github_config_repositories cr ON cr.user_id = t.user_id
WHERE t.user_id = $1 AND t.revoked_at IS NULL AND (t.expires_at IS NULL OR t.expires_at > now()) AND cr.provisioned_at IS NOT NULL)
`

func (q *Queries) GitHubConfigReady(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, gitHubConfigReady, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasConnectCredits = `-- name: HasConnectCredits :one
SELECT coalesce(ca.balance, 0)::numeric >= (((($1::bigint)::numeric / 3600.0) * mtv.credit_weight)::numeric(18,6))
FROM projects p JOIN project_runtime_configs prc ON prc.project_id = p.id
JOIN machine_type_versions mtv ON mtv.id = prc.applied_machine_type_version_id
LEFT JOIN credit_accounts ca ON ca.user_id = p.user_id
WHERE p.id = $2 AND p.user_id = $3
`

type HasConnectCreditsParams struct {
	WindowSeconds int64
	ProjectID     string
	UserID        string
}

func (q *Queries) HasConnectCredits(ctx context.Context, arg HasConnectCreditsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasConnectCredits, arg.WindowSeconds, arg.ProjectID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listClientHelperSessions = `-- name: ListClientHelperSessions :many
SELECT user_id,project_id,coalesce(cli_client_session_id,'') AS cli_client_session_id,
coalesce(helper_terminal_session_id,'') AS helper_terminal_session_id,
coalesce(helper_file_session_id,'') AS helper_file_session_id,
http_base_url
FROM access_sessions WHERE cli_client_session_id=$1
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

type ListClientHelperSessionsRow struct {
	UserID                  string
	ProjectID               string
	CLIClientSessionID      string
	HelperTerminalSessionID string
	HelperFileSessionID     string
	HttpBaseUrl             string
}

func (q *Queries) ListClientHelperSessions(ctx context.Context, cliClientSessionID sql.NullString) ([]ListClientHelperSessionsRow, error) {
	rows, err := q.db.Query(ctx, listClientHelperSessions, cliClientSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientHelperSessionsRow
	for rows.Next() {
		var i ListClientHelperSessionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ProjectID,
			&i.CLIClientSessionID,
			&i.HelperTerminalSessionID,
			&i.HelperFileSessionID,
			&i.HttpBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHelperRevocationOutbox = `-- name: ListPendingHelperRevocationOutbox :many
SELECT id,user_id,project_id,cli_client_session_id,http_base_url,session_ids,reason
FROM helper_revocation_outbox
WHERE propagated_at IS NULL
ORDER BY created_at,id
`

type ListPendingHelperRevocationOutboxRow struct {
	ID                 string
	UserID             string
	ProjectID          string
	CLIClientSessionID string
	HttpBaseUrl        string
	SessionIds         []string
	Reason             string
}

func (q *Queries) ListPendingHelperRevocationOutbox(ctx context.Context) ([]ListPendingHelperRevocationOutboxRow, error) {
	rows, err := q.db.Query(ctx, listPendingHelperRevocationOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingHelperRevocationOutboxRow
	for rows.Next() {
		var i ListPendingHelperRevocationOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.CLIClientSessionID,
			&i.HttpBaseUrl,
			&i.SessionIds,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHelperRevocations = `-- name: ListPendingHelperRevocations :many
SELECT id,user_id,project_id,coalesce(cli_client_session_id,'') AS cli_client_session_id,
coalesce(helper_terminal_session_id,'') AS helper_terminal_session_id,
coalesce(helper_file_session_id,'') AS helper_file_session_id,
http_base_url,
coalesce(descriptor->>'revocation_reason','revoked') AS reason
FROM access_sessions WHERE state='revoked' AND helper_revoked_at IS NULL
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

type ListPendingHelperRevocationsRow struct {
	ID                      string
	UserID                  string
	ProjectID               string
	CLIClientSessionID      string
	HelperTerminalSessionID string
	HelperFileSessionID     string
	HttpBaseUrl             string
	Reason                  interface{}
}

func (q *Queries) ListPendingHelperRevocations(ctx context.Context) ([]ListPendingHelperRevocationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingHelperRevocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingHelperRevocationsRow
	for rows.Next() {
		var i ListPendingHelperRevocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.CLIClientSessionID,
			&i.HelperTerminalSessionID,
			&i.HelperFileSessionID,
			&i.HttpBaseUrl,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProviderRouteCleanupOutbox = `-- name: ListPendingProviderRouteCleanupOutbox :many
SELECT id,project_id,action,reason FROM provider_route_cleanup_outbox
WHERE propagated_at IS NULL ORDER BY created_at,id
`

type ListPendingProviderRouteCleanupOutboxRow struct {
	ID        string
	ProjectID string
	Action    string
	Reason    string
}

func (q *Queries) ListPendingProviderRouteCleanupOutbox(ctx context.Context) ([]ListPendingProviderRouteCleanupOutboxRow, error) {
	rows, err := q.db.Query(ctx, listPendingProviderRouteCleanupOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingProviderRouteCleanupOutboxRow
	for rows.Next() {
		var i ListPendingProviderRouteCleanupOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Action,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectHelperSessions = `-- name: ListProjectHelperSessions :many
SELECT user_id,project_id,coalesce(cli_client_session_id,'') AS cli_client_session_id,
coalesce(helper_terminal_session_id,'') AS helper_terminal_session_id,
coalesce(helper_file_session_id,'') AS helper_file_session_id,
http_base_url
FROM access_sessions WHERE project_id=$1
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

type ListProjectHelperSessionsRow struct {
	UserID                  string
	ProjectID               string
	CLIClientSessionID      string
	HelperTerminalSessionID string
	HelperFileSessionID     string
	HttpBaseUrl             string
}

func (q *Queries) ListProjectHelperSessions(ctx context.Context, projectID string) ([]ListProjectHelperSessionsRow, error) {
	rows, err := q.db.Query(ctx, listProjectHelperSessions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectHelperSessionsRow
	for rows.Next() {
		var i ListProjectHelperSessionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ProjectID,
			&i.CLIClientSessionID,
			&i.HelperTerminalSessionID,
			&i.HelperFileSessionID,
			&i.HttpBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserHelperSessions = `-- name: ListUserHelperSessions :many
SELECT user_id,project_id,coalesce(cli_client_session_id,'') AS cli_client_session_id,
coalesce(helper_terminal_session_id,'') AS helper_terminal_session_id,
coalesce(helper_file_session_id,'') AS helper_file_session_id,
http_base_url
FROM access_sessions WHERE user_id=$1
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

type ListUserHelperSessionsRow struct {
	UserID                  string
	ProjectID               string
	CLIClientSessionID      string
	HelperTerminalSessionID string
	HelperFileSessionID     string
	HttpBaseUrl             string
}

func (q *Queries) ListUserHelperSessions(ctx context.Context, userID string) ([]ListUserHelperSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserHelperSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserHelperSessionsRow
	for rows.Next() {
		var i ListUserHelperSessionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ProjectID,
			&i.CLIClientSessionID,
			&i.HelperTerminalSessionID,
			&i.HelperFileSessionID,
			&i.HttpBaseUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccessSessionHelperRevocationPropagated = `-- name: MarkAccessSessionHelperRevocationPropagated :exec
UPDATE access_sessions SET helper_revoked_at=now(),updated_at=now()
WHERE id=$1 AND state='revoked' AND helper_revoked_at IS NULL
`

func (q *Queries) MarkAccessSessionHelperRevocationPropagated(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAccessSessionHelperRevocationPropagated, id)
	return err
}

const markClientHelperRevocationPropagated = `-- name: MarkClientHelperRevocationPropagated :exec
UPDATE access_sessions SET helper_revoked_at=now(),updated_at=now()
WHERE cli_client_session_id=$1 AND state='revoked' AND helper_revoked_at IS NULL
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

func (q *Queries) MarkClientHelperRevocationPropagated(ctx context.Context, cliClientSessionID sql.NullString) error {
	_, err := q.db.Exec(ctx, markClientHelperRevocationPropagated, cliClientSessionID)
	return err
}

const markHelperRevocationOutboxPropagated = `-- name: MarkHelperRevocationOutboxPropagated :exec
UPDATE helper_revocation_outbox SET propagated_at=now(),updated_at=now()
WHERE id=$1 AND propagated_at IS NULL
`

func (q *Queries) MarkHelperRevocationOutboxPropagated(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markHelperRevocationOutboxPropagated, id)
	return err
}

const markProjectHelperRevocationPropagated = `-- name: MarkProjectHelperRevocationPropagated :exec
UPDATE access_sessions SET helper_revoked_at=now(),updated_at=now()
WHERE project_id=$1 AND state='revoked' AND helper_revoked_at IS NULL
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

func (q *Queries) MarkProjectHelperRevocationPropagated(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, markProjectHelperRevocationPropagated, projectID)
	return err
}

const markProviderRouteCleanupOutboxPropagated = `-- name: MarkProviderRouteCleanupOutboxPropagated :exec
UPDATE provider_route_cleanup_outbox SET propagated_at=now(),updated_at=now()
WHERE project_id=$1 AND propagated_at IS NULL
`

func (q *Queries) MarkProviderRouteCleanupOutboxPropagated(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, markProviderRouteCleanupOutboxPropagated, projectID)
	return err
}

const markUserHelperRevocationPropagated = `-- name: MarkUserHelperRevocationPropagated :exec
UPDATE access_sessions SET helper_revoked_at=now(),updated_at=now()
WHERE user_id=$1 AND state='revoked' AND helper_revoked_at IS NULL
AND (helper_terminal_session_id IS NOT NULL OR helper_file_session_id IS NOT NULL)
`

func (q *Queries) MarkUserHelperRevocationPropagated(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markUserHelperRevocationPropagated, userID)
	return err
}

const recordConnectionEvent = `-- name: RecordConnectionEvent :exec
INSERT INTO connection_events (id,user_id,project_id,access_session_id,result,failure_reason,metadata)
VALUES ($1,nullif($2,''),nullif($3,''),nullif($4,''),$5,$6,$7::jsonb)
`

type RecordConnectionEventParams struct {
	ID              string
	UserID          interface{}
	ProjectID       interface{}
	AccessSessionID interface{}
	Result          string
	FailureReason   string
	Metadata        []byte
}

func (q *Queries) RecordConnectionEvent(ctx context.Context, arg RecordConnectionEventParams) error {
	_, err := q.db.Exec(ctx, recordConnectionEvent,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.AccessSessionID,
		arg.Result,
		arg.FailureReason,
		arg.Metadata,
	)
	return err
}

const revokeClientAccessSessions = `-- name: RevokeClientAccessSessions :exec
UPDATE access_sessions SET state='revoked',revoked_at=coalesce(revoked_at,now()),updated_at=now(),version=version+1,
descriptor=jsonb_set(descriptor,'{revocation_reason}',to_jsonb($1::text),true)
WHERE cli_client_session_id=$2 AND state='active' AND revoked_at IS NULL
`

type RevokeClientAccessSessionsParams struct {
	Reason             string
	CLIClientSessionID sql.NullString
}

func (q *Queries) RevokeClientAccessSessions(ctx context.Context, arg RevokeClientAccessSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeClientAccessSessions, arg.Reason, arg.CLIClientSessionID)
	return err
}

const revokeProjectAccessSessions = `-- name: RevokeProjectAccessSessions :exec
UPDATE access_sessions SET state='revoked',revoked_at=now(),updated_at=now(),version=version+1,
descriptor=jsonb_set(descriptor,'{revocation_reason}',to_jsonb($1::text),true)
WHERE state='active' AND revoked_at IS NULL AND project_id=$2
`

type RevokeProjectAccessSessionsParams struct {
	Reason    string
	ProjectID string
}

func (q *Queries) RevokeProjectAccessSessions(ctx context.Context, arg RevokeProjectAccessSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeProjectAccessSessions, arg.Reason, arg.ProjectID)
	return err
}

const revokeUserAccessSessions = `-- name: RevokeUserAccessSessions :exec
UPDATE access_sessions SET state='revoked',revoked_at=now(),updated_at=now(),version=version+1,
descriptor=jsonb_set(descriptor,'{revocation_reason}',to_jsonb($1::text),true)
WHERE state='active' AND revoked_at IS NULL AND user_id=$2
`

type RevokeUserAccessSessionsParams struct {
	Reason string
	UserID string
}

func (q *Queries) RevokeUserAccessSessions(ctx context.Context, arg RevokeUserAccessSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserAccessSessions, arg.Reason, arg.UserID)
	return err
}

const upsertProviderRouteCleanupOutbox = `-- name: UpsertProviderRouteCleanupOutbox :exec
INSERT INTO provider_route_cleanup_outbox (id,project_id,action,reason)
VALUES ($1,$2,$3,$4)
ON CONFLICT (project_id) DO UPDATE SET action=EXCLUDED.action,reason=EXCLUDED.reason,
propagated_at=NULL,updated_at=now()
`

type UpsertProviderRouteCleanupOutboxParams struct {
	ID        string
	ProjectID string
	Action    string
	Reason    string
}

func (q *Queries) UpsertProviderRouteCleanupOutbox(ctx context.Context, arg UpsertProviderRouteCleanupOutboxParams) error {
	_, err := q.db.Exec(ctx, upsertProviderRouteCleanupOutbox,
		arg.ID,
		arg.ProjectID,
		arg.Action,
		arg.Reason,
	)
	return err
}

const upsertProviderRouteResource = `-- name: UpsertProviderRouteResource :exec
INSERT INTO provider_routes (id, project_id, tunnel_id, client_id, resource_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6::jsonb)
ON CONFLICT (project_id) DO UPDATE SET tunnel_id=EXCLUDED.tunnel_id,client_id=EXCLUDED.client_id,resource_id=EXCLUDED.resource_id,
metadata=EXCLUDED.metadata,version=provider_routes.version+1,updated_at=now()
`

type UpsertProviderRouteResourceParams struct {
	ID         string
	ProjectID  string
	TunnelID   string
	ClientID   string
	ResourceID string
	Metadata   []byte
}

func (q *Queries) UpsertProviderRouteResource(ctx context.Context, arg UpsertProviderRouteResourceParams) error {
	_, err := q.db.Exec(ctx, upsertProviderRouteResource,
		arg.ID,
		arg.ProjectID,
		arg.TunnelID,
		arg.ClientID,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}
