// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbsqlc

import (
	"context"
	"time"
)

const authenticateBrowserSession = `-- name: AuthenticateBrowserSession :one
SELECT s.id AS session_id, s.user_id, s.expires_at, s.csrf_hash,
       u.id, u.workos_subject, u.primary_email, u.display_name, u.status, u.role, u.created_at
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.session_hash = $1 AND s.revoked_at IS NULL AND s.expires_at > now() AND u.status = 'active'
`

type AuthenticateBrowserSessionRow struct {
	SessionID     string
	UserID        string
	ExpiresAt     time.Time
	CsrfHash      string
	ID            string
	WorkosSubject string
	PrimaryEmail  string
	DisplayName   string
	Status        string
	Role          string
	CreatedAt     time.Time
}

func (q *Queries) AuthenticateBrowserSession(ctx context.Context, sessionHash string) (AuthenticateBrowserSessionRow, error) {
	row := q.db.QueryRowContext(ctx, authenticateBrowserSession, sessionHash)
	var i AuthenticateBrowserSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CsrfHash,
		&i.ID,
		&i.WorkosSubject,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const browserSessionCSRFExists = `-- name: BrowserSessionCSRFExists :one
SELECT EXISTS (SELECT 1 FROM sessions WHERE session_hash = $1 AND csrf_hash = $2 AND revoked_at IS NULL AND expires_at > now())
`

type BrowserSessionCSRFExistsParams struct {
	SessionHash string
	CsrfHash    string
}

func (q *Queries) BrowserSessionCSRFExists(ctx context.Context, arg BrowserSessionCSRFExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, browserSessionCSRFExists, arg.SessionHash, arg.CsrfHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBrowserSession = `-- name: CreateBrowserSession :exec
INSERT INTO sessions (id, user_id, session_hash, csrf_hash, expires_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
`

type CreateBrowserSessionParams struct {
	ID          string
	UserID      string
	SessionHash string
	CsrfHash    string
	ExpiresAt   time.Time
}

func (q *Queries) CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) error {
	_, err := q.db.ExecContext(ctx, createBrowserSession,
		arg.ID,
		arg.UserID,
		arg.SessionHash,
		arg.CsrfHash,
		arg.ExpiresAt,
	)
	return err
}

const creditLedgerEntryExists = `-- name: CreditLedgerEntryExists :one
SELECT EXISTS (SELECT 1 FROM credit_ledger_entries WHERE idempotency_key = $1)
`

func (q *Queries) CreditLedgerEntryExists(ctx context.Context, idempotencyKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, creditLedgerEntryExists, idempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ensureCreditAccount = `-- name: EnsureCreditAccount :one
INSERT INTO credit_accounts (id, user_id) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET updated_at = credit_accounts.updated_at RETURNING id
`

type EnsureCreditAccountParams struct {
	ID     string
	UserID string
}

func (q *Queries) EnsureCreditAccount(ctx context.Context, arg EnsureCreditAccountParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureCreditAccount, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const ensureStorageAccount = `-- name: EnsureStorageAccount :one
INSERT INTO storage_accounts (id, user_id) VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET updated_at = storage_accounts.updated_at RETURNING id
`

type EnsureStorageAccountParams struct {
	ID     string
	UserID string
}

func (q *Queries) EnsureStorageAccount(ctx context.Context, arg EnsureStorageAccountParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureStorageAccount, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getFreePlanEntitlement = `-- name: GetFreePlanEntitlement :one
SELECT pv.id, pv.included_credits::text AS included_credits, pv.included_storage_gb
FROM plans p JOIN plan_versions pv ON pv.id = p.current_version_id
WHERE p.code = 'free' AND p.active LIMIT 1
`

type GetFreePlanEntitlementRow struct {
	ID                string
	IncludedCredits   string
	IncludedStorageGb int32
}

func (q *Queries) GetFreePlanEntitlement(ctx context.Context) (GetFreePlanEntitlementRow, error) {
	row := q.db.QueryRowContext(ctx, getFreePlanEntitlement)
	var i GetFreePlanEntitlementRow
	err := row.Scan(&i.ID, &i.IncludedCredits, &i.IncludedStorageGb)
	return i, err
}

const getStorageUsageForUpdate = `-- name: GetStorageUsageForUpdate :one
SELECT purchased_gb, allocated_gb FROM storage_accounts WHERE id = $1 FOR UPDATE
`

type GetStorageUsageForUpdateRow struct {
	PurchasedGb int32
	AllocatedGb int32
}

func (q *Queries) GetStorageUsageForUpdate(ctx context.Context, id string) (GetStorageUsageForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getStorageUsageForUpdate, id)
	var i GetStorageUsageForUpdateRow
	err := row.Scan(&i.PurchasedGb, &i.AllocatedGb)
	return i, err
}

const increaseCreditBalance = `-- name: IncreaseCreditBalance :exec
UPDATE credit_accounts SET balance = balance + $1::numeric, version = version + 1, updated_at = now() WHERE id = $2
`

type IncreaseCreditBalanceParams struct {
	Amount string
	ID     string
}

func (q *Queries) IncreaseCreditBalance(ctx context.Context, arg IncreaseCreditBalanceParams) error {
	_, err := q.db.ExecContext(ctx, increaseCreditBalance, arg.Amount, arg.ID)
	return err
}

const insertFreeCreditGrant = `-- name: InsertFreeCreditGrant :execrows
INSERT INTO credit_ledger_entries (id, account_id, entry_type, amount, source_type, source_id, idempotency_key, metadata)
VALUES ($1, $2, 'grant', $3::numeric, 'plan', $4, $5, '{"plan_code":"free"}'::jsonb)
ON CONFLICT (idempotency_key) DO NOTHING
`

type InsertFreeCreditGrantParams struct {
	ID             string
	AccountID      string
	Amount         string
	SourceID       string
	IdempotencyKey string
}

func (q *Queries) InsertFreeCreditGrant(ctx context.Context, arg InsertFreeCreditGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFreeCreditGrant,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.SourceID,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertFreeIncludedStorageLedger = `-- name: InsertFreeIncludedStorageLedger :execrows
INSERT INTO storage_ledger_entries (id, account_id, entry_type, amount_gb, source_type, source_id, idempotency_key, metadata)
VALUES ($1, $2, 'included_set', $3, 'plan', $4, $5, '{"plan_code":"free"}'::jsonb)
ON CONFLICT (idempotency_key) DO NOTHING
`

type InsertFreeIncludedStorageLedgerParams struct {
	ID             string
	AccountID      string
	AmountGb       int32
	SourceID       string
	IdempotencyKey string
}

func (q *Queries) InsertFreeIncludedStorageLedger(ctx context.Context, arg InsertFreeIncludedStorageLedgerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFreeIncludedStorageLedger,
		arg.ID,
		arg.AccountID,
		arg.AmountGb,
		arg.SourceID,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshBrowserSessionCSRF = `-- name: RefreshBrowserSessionCSRF :execrows
UPDATE sessions SET csrf_hash = $1, updated_at = now()
WHERE id = $2 AND revoked_at IS NULL AND expires_at > now()
`

type RefreshBrowserSessionCSRFParams struct {
	CsrfHash string
	ID       string
}

func (q *Queries) RefreshBrowserSessionCSRF(ctx context.Context, arg RefreshBrowserSessionCSRFParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refreshBrowserSessionCSRF, arg.CsrfHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeBrowserSession = `-- name: RevokeBrowserSession :one
UPDATE sessions SET revoked_at = now(), updated_at = now(), version = version + 1
WHERE session_hash = $1 AND revoked_at IS NULL RETURNING user_id
`

func (q *Queries) RevokeBrowserSession(ctx context.Context, sessionHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, revokeBrowserSession, sessionHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const rotateBrowserSession = `-- name: RotateBrowserSession :execrows
UPDATE sessions SET session_hash = $1, csrf_hash = $2, expires_at = $3,
	rotated_at = now(), updated_at = now(), version = version + 1
WHERE id = $4 AND revoked_at IS NULL AND expires_at > now()
`

type RotateBrowserSessionParams struct {
	SessionHash string
	CsrfHash    string
	ExpiresAt   time.Time
	ID          string
}

func (q *Queries) RotateBrowserSession(ctx context.Context, arg RotateBrowserSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, rotateBrowserSession,
		arg.SessionHash,
		arg.CsrfHash,
		arg.ExpiresAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setIncludedStorage = `-- name: SetIncludedStorage :exec
UPDATE storage_accounts SET included_gb = $2, version = version + 1, updated_at = now() WHERE id = $1
`

type SetIncludedStorageParams struct {
	ID         string
	IncludedGb int32
}

func (q *Queries) SetIncludedStorage(ctx context.Context, arg SetIncludedStorageParams) error {
	_, err := q.db.ExecContext(ctx, setIncludedStorage, arg.ID, arg.IncludedGb)
	return err
}

const upsertWorkOSUser = `-- name: UpsertWorkOSUser :one
WITH upsert_user AS (
	INSERT INTO users (id, workos_subject, primary_email, display_name, status, created_at, updated_at)
	VALUES ($1, $2, $3, $4, 'active', now(), now())
	ON CONFLICT (workos_subject) DO UPDATE SET primary_email = EXCLUDED.primary_email, display_name = EXCLUDED.display_name, updated_at = now(), version = users.version + 1
	RETURNING id, workos_subject, primary_email, display_name, status, role, created_at
), identity AS (
	INSERT INTO user_identities (id, user_id, provider, provider_subject, email, created_at, updated_at)
	SELECT $5, id, 'workos', workos_subject, primary_email, now(), now() FROM upsert_user
	ON CONFLICT (provider, provider_subject) DO UPDATE SET email = EXCLUDED.email, updated_at = now()
)
SELECT id, workos_subject, primary_email, display_name, status, role, created_at FROM upsert_user
`

type UpsertWorkOSUserParams struct {
	UserID        string
	WorkosSubject string
	PrimaryEmail  string
	DisplayName   string
	IdentityID    string
}

type UpsertWorkOSUserRow struct {
	ID            string
	WorkosSubject string
	PrimaryEmail  string
	DisplayName   string
	Status        string
	Role          string
	CreatedAt     time.Time
}

func (q *Queries) UpsertWorkOSUser(ctx context.Context, arg UpsertWorkOSUserParams) (UpsertWorkOSUserRow, error) {
	row := q.db.QueryRowContext(ctx, upsertWorkOSUser,
		arg.UserID,
		arg.WorkosSubject,
		arg.PrimaryEmail,
		arg.DisplayName,
		arg.IdentityID,
	)
	var i UpsertWorkOSUserRow
	err := row.Scan(
		&i.ID,
		&i.WorkosSubject,
		&i.PrimaryEmail,
		&i.DisplayName,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const userHasActiveSubscription = `-- name: UserHasActiveSubscription :one
SELECT EXISTS (SELECT 1 FROM subscriptions WHERE user_id = $1 AND state IN ('active', 'trialing') AND (current_period_end IS NULL OR current_period_end > now()))
`

func (q *Queries) UserHasActiveSubscription(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasActiveSubscription, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userOwnsProject = `-- name: UserOwnsProject :one
SELECT EXISTS (SELECT 1 FROM projects WHERE id = $1 AND user_id = $2 AND state <> 'deleted')
`

type UserOwnsProjectParams struct {
	ID     string
	UserID string
}

func (q *Queries) UserOwnsProject(ctx context.Context, arg UserOwnsProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userOwnsProject, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
