// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codex_sessions.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const completeCodexSessionStop = `-- name: CompleteCodexSessionStop :exec
UPDATE codex_sessions SET state='stopped',cleanup_status='complete',stopped_at=$1,updated_at=$1 WHERE id=$2
`

type CompleteCodexSessionStopParams struct {
	Now sql.NullTime
	ID  string
}

func (q *Queries) CompleteCodexSessionStop(ctx context.Context, arg CompleteCodexSessionStopParams) error {
	_, err := q.db.ExecContext(ctx, completeCodexSessionStop, arg.Now, arg.ID)
	return err
}

const countActiveCodexSessions = `-- name: CountActiveCodexSessions :one
SELECT count(*) FROM codex_sessions
WHERE user_id=$1 AND environment_id=$2
  AND state IN ('preparing','ready','reconnecting') AND lease_expires_at>$3
`

type CountActiveCodexSessionsParams struct {
	UserID        string
	EnvironmentID string
	Now           time.Time
}

func (q *Queries) CountActiveCodexSessions(ctx context.Context, arg CountActiveCodexSessionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveCodexSessions, arg.UserID, arg.EnvironmentID, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCodexSession = `-- name: CreateCodexSession :one
INSERT INTO codex_sessions (id,environment_id,machine_id,user_id,cli_client_session_id,idempotency_key,request_hash,
 installation_generation,connector_generation,edge_pool,edge_node_id,edge_assignment_host,lease_expires_at,last_renewed_at)
VALUES ($1,$2,$3,$4,$5,
 $6,$7,$8,$9,
 $10,$11,$12,$13,$14)
RETURNING id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at
`

type CreateCodexSessionParams struct {
	ID                     string
	EnvironmentID          string
	MachineID              string
	UserID                 string
	CLIClientSessionID     string
	IdempotencyKey         string
	RequestHash            []byte
	InstallationGeneration int64
	ConnectorGeneration    int64
	EdgePool               string
	EdgeNodeID             string
	EdgeAssignmentHost     string
	LeaseExpiresAt         time.Time
	Now                    time.Time
}

func (q *Queries) CreateCodexSession(ctx context.Context, arg CreateCodexSessionParams) (CodexSession, error) {
	row := q.db.QueryRowContext(ctx, createCodexSession,
		arg.ID,
		arg.EnvironmentID,
		arg.MachineID,
		arg.UserID,
		arg.CLIClientSessionID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.InstallationGeneration,
		arg.ConnectorGeneration,
		arg.EdgePool,
		arg.EdgeNodeID,
		arg.EdgeAssignmentHost,
		arg.LeaseExpiresAt,
		arg.Now,
	)
	var i CodexSession
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.MachineID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.State,
		&i.InstallationGeneration,
		&i.ConnectorID,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.EdgeAssignmentHost,
		&i.RemoteCodexVersion,
		&i.FailureCode,
		&i.CleanupStatus,
		&i.LeaseExpiresAt,
		&i.PreparedAt,
		&i.ReconnectingAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.LastRenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodexSessionByIdempotency = `-- name: GetCodexSessionByIdempotency :one
SELECT id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at FROM codex_sessions WHERE cli_client_session_id=$1 AND idempotency_key=$2
`

type GetCodexSessionByIdempotencyParams struct {
	CLIClientSessionID string
	IdempotencyKey     string
}

func (q *Queries) GetCodexSessionByIdempotency(ctx context.Context, arg GetCodexSessionByIdempotencyParams) (CodexSession, error) {
	row := q.db.QueryRowContext(ctx, getCodexSessionByIdempotency, arg.CLIClientSessionID, arg.IdempotencyKey)
	var i CodexSession
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.MachineID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.State,
		&i.InstallationGeneration,
		&i.ConnectorID,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.EdgeAssignmentHost,
		&i.RemoteCodexVersion,
		&i.FailureCode,
		&i.CleanupStatus,
		&i.LeaseExpiresAt,
		&i.PreparedAt,
		&i.ReconnectingAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.LastRenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCodexSessionMachineCapability = `-- name: GetCodexSessionMachineCapability :one
SELECT m.online, m.configured_capabilities, m.observed_capabilities
FROM user_machines m
WHERE m.id=$1 AND m.environment_id=$2
  AND m.revoked_at IS NULL AND m.deleted_at IS NULL
`

type GetCodexSessionMachineCapabilityParams struct {
	MachineID     string
	EnvironmentID string
}

type GetCodexSessionMachineCapabilityRow struct {
	Online                 bool
	ConfiguredCapabilities []string
	ObservedCapabilities   []string
}

func (q *Queries) GetCodexSessionMachineCapability(ctx context.Context, arg GetCodexSessionMachineCapabilityParams) (GetCodexSessionMachineCapabilityRow, error) {
	row := q.db.QueryRowContext(ctx, getCodexSessionMachineCapability, arg.MachineID, arg.EnvironmentID)
	var i GetCodexSessionMachineCapabilityRow
	err := row.Scan(&i.Online, pq.Array(&i.ConfiguredCapabilities), pq.Array(&i.ObservedCapabilities))
	return i, err
}

const getOwnedCodexSession = `-- name: GetOwnedCodexSession :one
SELECT id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at FROM codex_sessions WHERE id=$1 AND user_id=$2 AND cli_client_session_id=$3
`

type GetOwnedCodexSessionParams struct {
	ID                 string
	UserID             string
	CLIClientSessionID string
}

func (q *Queries) GetOwnedCodexSession(ctx context.Context, arg GetOwnedCodexSessionParams) (CodexSession, error) {
	row := q.db.QueryRowContext(ctx, getOwnedCodexSession, arg.ID, arg.UserID, arg.CLIClientSessionID)
	var i CodexSession
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.MachineID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.State,
		&i.InstallationGeneration,
		&i.ConnectorID,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.EdgeAssignmentHost,
		&i.RemoteCodexVersion,
		&i.FailureCode,
		&i.CleanupStatus,
		&i.LeaseExpiresAt,
		&i.PreparedAt,
		&i.ReconnectingAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.LastRenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredCodexSessions = `-- name: ListExpiredCodexSessions :many
SELECT id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at FROM codex_sessions WHERE state IN ('preparing','ready','reconnecting','stopping') AND lease_expires_at<=$1
ORDER BY lease_expires_at,id LIMIT $2
`

type ListExpiredCodexSessionsParams struct {
	Now       time.Time
	BatchSize int32
}

func (q *Queries) ListExpiredCodexSessions(ctx context.Context, arg ListExpiredCodexSessionsParams) ([]CodexSession, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredCodexSessions, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodexSession
	for rows.Next() {
		var i CodexSession
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.MachineID,
			&i.UserID,
			&i.CLIClientSessionID,
			&i.IdempotencyKey,
			&i.RequestHash,
			&i.State,
			&i.InstallationGeneration,
			&i.ConnectorID,
			&i.ConnectorGeneration,
			&i.EdgePool,
			&i.EdgeNodeID,
			&i.EdgeAssignmentHost,
			&i.RemoteCodexVersion,
			&i.FailureCode,
			&i.CleanupStatus,
			&i.LeaseExpiresAt,
			&i.PreparedAt,
			&i.ReconnectingAt,
			&i.StoppingAt,
			&i.StoppedAt,
			&i.LastRenewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCodexSessionLimit = `-- name: LockCodexSessionLimit :one
SELECT id FROM control_environments WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCodexSessionLimit(ctx context.Context, environmentID string) (string, error) {
	row := q.db.QueryRowContext(ctx, lockCodexSessionLimit, environmentID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markCodexSessionReady = `-- name: MarkCodexSessionReady :one
UPDATE codex_sessions SET state='ready',remote_codex_version=$1,prepared_at=$2,updated_at=$2
WHERE id=$3 AND state='preparing' RETURNING id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at
`

type MarkCodexSessionReadyParams struct {
	RemoteCodexVersion sql.NullString
	Now                sql.NullTime
	ID                 string
}

func (q *Queries) MarkCodexSessionReady(ctx context.Context, arg MarkCodexSessionReadyParams) (CodexSession, error) {
	row := q.db.QueryRowContext(ctx, markCodexSessionReady, arg.RemoteCodexVersion, arg.Now, arg.ID)
	var i CodexSession
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.MachineID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.State,
		&i.InstallationGeneration,
		&i.ConnectorID,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.EdgeAssignmentHost,
		&i.RemoteCodexVersion,
		&i.FailureCode,
		&i.CleanupStatus,
		&i.LeaseExpiresAt,
		&i.PreparedAt,
		&i.ReconnectingAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.LastRenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExpiredCodexSessionStopped = `-- name: MarkExpiredCodexSessionStopped :exec
UPDATE codex_sessions SET state='stopped',cleanup_status='uncertain',stopped_at=$1,updated_at=$1
WHERE id=$2 AND lease_expires_at<=$1 AND state IN ('preparing','ready','reconnecting','stopping')
`

type MarkExpiredCodexSessionStoppedParams struct {
	Now sql.NullTime
	ID  string
}

func (q *Queries) MarkExpiredCodexSessionStopped(ctx context.Context, arg MarkExpiredCodexSessionStoppedParams) error {
	_, err := q.db.ExecContext(ctx, markExpiredCodexSessionStopped, arg.Now, arg.ID)
	return err
}

const renewCodexSession = `-- name: RenewCodexSession :one
UPDATE codex_sessions SET lease_expires_at=$1,last_renewed_at=$2,updated_at=$2
WHERE id=$3 AND user_id=$4 AND cli_client_session_id=$5
 AND state IN ('preparing','ready','reconnecting') AND lease_expires_at>$2
RETURNING id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at
`

type RenewCodexSessionParams struct {
	LeaseExpiresAt     time.Time
	Now                time.Time
	ID                 string
	UserID             string
	CLIClientSessionID string
}

func (q *Queries) RenewCodexSession(ctx context.Context, arg RenewCodexSessionParams) (CodexSession, error) {
	row := q.db.QueryRowContext(ctx, renewCodexSession,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.ID,
		arg.UserID,
		arg.CLIClientSessionID,
	)
	var i CodexSession
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.MachineID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.State,
		&i.InstallationGeneration,
		&i.ConnectorID,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.EdgeAssignmentHost,
		&i.RemoteCodexVersion,
		&i.FailureCode,
		&i.CleanupStatus,
		&i.LeaseExpiresAt,
		&i.PreparedAt,
		&i.ReconnectingAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.LastRenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveCodexSessionEnvironment = `-- name: ResolveCodexSessionEnvironment :one
SELECT e.id AS environment_id, e.owner_user_id AS user_id, m.id AS machine_id,
       m.installation_generation, c.generation AS connector_generation,
       c.edge_pool, c.edge_node_id, r.public_host, m.online,
       m.configured_capabilities, m.observed_capabilities
FROM control_environments e
JOIN user_machines m ON m.environment_id=e.id AND m.revoked_at IS NULL AND m.deleted_at IS NULL
JOIN control_connector_generations c ON c.environment_id=e.id AND c.state IN ('pending','admitted') AND c.revoked_at IS NULL
JOIN control_routes r ON r.environment_id=e.id AND r.kind='runtime_https_wss' AND r.desired_state IN ('attached','replacing')
WHERE e.id=$1 AND e.owner_user_id=$2
  AND e.desired_state='active' AND e.revoked_at IS NULL
`

type ResolveCodexSessionEnvironmentParams struct {
	EnvironmentID string
	UserID        sql.NullString
}

type ResolveCodexSessionEnvironmentRow struct {
	EnvironmentID          string
	UserID                 sql.NullString
	MachineID              string
	InstallationGeneration int64
	ConnectorGeneration    int64
	EdgePool               string
	EdgeNodeID             sql.NullString
	PublicHost             string
	Online                 bool
	ConfiguredCapabilities []string
	ObservedCapabilities   []string
}

func (q *Queries) ResolveCodexSessionEnvironment(ctx context.Context, arg ResolveCodexSessionEnvironmentParams) (ResolveCodexSessionEnvironmentRow, error) {
	row := q.db.QueryRowContext(ctx, resolveCodexSessionEnvironment, arg.EnvironmentID, arg.UserID)
	var i ResolveCodexSessionEnvironmentRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.UserID,
		&i.MachineID,
		&i.InstallationGeneration,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.PublicHost,
		&i.Online,
		pq.Array(&i.ConfiguredCapabilities),
		pq.Array(&i.ObservedCapabilities),
	)
	return i, err
}

const stopCodexSession = `-- name: StopCodexSession :one
UPDATE codex_sessions SET state='stopping',cleanup_status='pending',stopping_at=$1,updated_at=$1
WHERE id=$2 AND user_id=$3 AND cli_client_session_id=$4
 AND state NOT IN ('stopped','failed') RETURNING id, environment_id, machine_id, user_id, cli_client_session_id, idempotency_key, request_hash, state, installation_generation, connector_id, connector_generation, edge_pool, edge_node_id, edge_assignment_host, remote_codex_version, failure_code, cleanup_status, lease_expires_at, prepared_at, reconnecting_at, stopping_at, stopped_at, last_renewed_at, created_at, updated_at
`

type StopCodexSessionParams struct {
	Now                sql.NullTime
	ID                 string
	UserID             string
	CLIClientSessionID string
}

func (q *Queries) StopCodexSession(ctx context.Context, arg StopCodexSessionParams) (CodexSession, error) {
	row := q.db.QueryRowContext(ctx, stopCodexSession,
		arg.Now,
		arg.ID,
		arg.UserID,
		arg.CLIClientSessionID,
	)
	var i CodexSession
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.MachineID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.State,
		&i.InstallationGeneration,
		&i.ConnectorID,
		&i.ConnectorGeneration,
		&i.EdgePool,
		&i.EdgeNodeID,
		&i.EdgeAssignmentHost,
		&i.RemoteCodexVersion,
		&i.FailureCode,
		&i.CleanupStatus,
		&i.LeaseExpiresAt,
		&i.PreparedAt,
		&i.ReconnectingAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.LastRenewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stopCodexSessionsForMachine = `-- name: StopCodexSessionsForMachine :execrows
UPDATE codex_sessions
SET state='stopping',cleanup_status='pending',stopping_at=$1,updated_at=$1
WHERE machine_id=$2 AND state IN ('preparing','ready','reconnecting')
`

type StopCodexSessionsForMachineParams struct {
	Now       sql.NullTime
	MachineID string
}

func (q *Queries) StopCodexSessionsForMachine(ctx context.Context, arg StopCodexSessionsForMachineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stopCodexSessionsForMachine, arg.Now, arg.MachineID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
