// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connector_bootstrap_v1.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const getTunnelManagedEndpointForConnectorBootstrapV1 = `-- name: GetTunnelManagedEndpointForConnectorBootstrapV1 :one
SELECT stable_endpoint_id, stable_endpoint
FROM tunnels
WHERE id = $1
  AND account_id = $2
  AND desired_state <> 'deleted'
`

type GetTunnelManagedEndpointForConnectorBootstrapV1Params struct {
	TunnelID  string
	AccountID string
}

type GetTunnelManagedEndpointForConnectorBootstrapV1Row struct {
	StableEndpointID string
	StableEndpoint   string
}

func (q *Queries) GetTunnelManagedEndpointForConnectorBootstrapV1(ctx context.Context, arg GetTunnelManagedEndpointForConnectorBootstrapV1Params) (GetTunnelManagedEndpointForConnectorBootstrapV1Row, error) {
	row := q.db.QueryRow(ctx, getTunnelManagedEndpointForConnectorBootstrapV1, arg.TunnelID, arg.AccountID)
	var i GetTunnelManagedEndpointForConnectorBootstrapV1Row
	err := row.Scan(&i.StableEndpointID, &i.StableEndpoint)
	return i, err
}

const listReadyConnectorCarrierNodesV1 = `-- name: ListReadyConnectorCarrierNodesV1 :many
SELECT id AS edge_node_id,
       process_epoch AS edge_process_epoch,
       relay_region AS failure_domain,
       carrier_endpoint_host,
       carrier_endpoint_tcp_port,
       carrier_endpoint_quic_port,
       carrier_server_spki_sha256,
       carrier_server_certificate_chain_pem,
       last_heartbeat_at
FROM control_tunnel_nodes
WHERE state = 'ready'
  AND ready = true
  AND last_heartbeat_at > $1::timestamptz - interval '2 minutes'
  AND carrier_endpoint_host IS NOT NULL
  AND carrier_endpoint_tcp_port IS NOT NULL
  AND carrier_endpoint_quic_port IS NOT NULL
  AND carrier_server_spki_sha256 IS NOT NULL
  AND carrier_server_certificate_chain_pem IS NOT NULL
ORDER BY relay_region, id, process_epoch
LIMIT $2
`

type ListReadyConnectorCarrierNodesV1Params struct {
	Now      time.Time
	RowLimit int32
}

type ListReadyConnectorCarrierNodesV1Row struct {
	EdgeNodeID                       string
	EdgeProcessEpoch                 string
	FailureDomain                    sql.NullString
	CarrierEndpointHost              sql.NullString
	CarrierEndpointTcpPort           sql.NullInt32
	CarrierEndpointQuicPort          sql.NullInt32
	CarrierServerSpkiSha256          sql.NullString
	CarrierServerCertificateChainPem sql.NullString
	LastHeartbeatAt                  sql.NullTime
}

func (q *Queries) ListReadyConnectorCarrierNodesV1(ctx context.Context, arg ListReadyConnectorCarrierNodesV1Params) ([]ListReadyConnectorCarrierNodesV1Row, error) {
	rows, err := q.db.Query(ctx, listReadyConnectorCarrierNodesV1, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyConnectorCarrierNodesV1Row
	for rows.Next() {
		var i ListReadyConnectorCarrierNodesV1Row
		if err := rows.Scan(
			&i.EdgeNodeID,
			&i.EdgeProcessEpoch,
			&i.FailureDomain,
			&i.CarrierEndpointHost,
			&i.CarrierEndpointTcpPort,
			&i.CarrierEndpointQuicPort,
			&i.CarrierServerSpkiSha256,
			&i.CarrierServerCertificateChainPem,
			&i.LastHeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
