// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnostic_uploads.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const completeDiagnosticUploadIntent = `-- name: CompleteDiagnosticUploadIntent :one
UPDATE diagnostic_upload_intents
SET state = 'uploaded', uploaded_at = $1, object_etag = $2
WHERE id = $3 AND user_id = $4 AND state = 'pending'
  AND expires_at > $1
RETURNING id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag
`

type CompleteDiagnosticUploadIntentParams struct {
	UploadedAt sql.NullTime
	ObjectEtag sql.NullString
	ID         string
	UserID     string
}

func (q *Queries) CompleteDiagnosticUploadIntent(ctx context.Context, arg CompleteDiagnosticUploadIntentParams) (DiagnosticUploadIntent, error) {
	row := q.db.QueryRow(ctx, completeDiagnosticUploadIntent,
		arg.UploadedAt,
		arg.ObjectEtag,
		arg.ID,
		arg.UserID,
	)
	var i DiagnosticUploadIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.OperationKey,
		&i.RequestHash,
		&i.CorrelationID,
		&i.ObjectKey,
		&i.ExpectedBytes,
		&i.Sha256,
		&i.Categories,
		&i.State,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.ObjectEtag,
	)
	return i, err
}

const createDiagnosticUploadIntent = `-- name: CreateDiagnosticUploadIntent :one
INSERT INTO diagnostic_upload_intents
  (id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id,
   object_key, expected_bytes, sha256, categories, expires_at, retain_until, created_at)
SELECT
  $1, $2, $3, $4,
   $5, $6, $7,
   $8, $9, $10, $11,
   $12, $13
FROM cli_client_sessions
WHERE id = $3 AND user_id = $2 AND state = 'active'
RETURNING id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag
`

type CreateDiagnosticUploadIntentParams struct {
	ID                 string
	UserID             string
	CLIClientSessionID string
	OperationKey       string
	RequestHash        []byte
	CorrelationID      string
	ObjectKey          string
	ExpectedBytes      int64
	Sha256             []byte
	Categories         []string
	ExpiresAt          time.Time
	RetainUntil        time.Time
	CreatedAt          time.Time
}

func (q *Queries) CreateDiagnosticUploadIntent(ctx context.Context, arg CreateDiagnosticUploadIntentParams) (DiagnosticUploadIntent, error) {
	row := q.db.QueryRow(ctx, createDiagnosticUploadIntent,
		arg.ID,
		arg.UserID,
		arg.CLIClientSessionID,
		arg.OperationKey,
		arg.RequestHash,
		arg.CorrelationID,
		arg.ObjectKey,
		arg.ExpectedBytes,
		arg.Sha256,
		arg.Categories,
		arg.ExpiresAt,
		arg.RetainUntil,
		arg.CreatedAt,
	)
	var i DiagnosticUploadIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.OperationKey,
		&i.RequestHash,
		&i.CorrelationID,
		&i.ObjectKey,
		&i.ExpectedBytes,
		&i.Sha256,
		&i.Categories,
		&i.State,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.ObjectEtag,
	)
	return i, err
}

const deleteRetainedDiagnosticUploadIntent = `-- name: DeleteRetainedDiagnosticUploadIntent :one
DELETE FROM diagnostic_upload_intents
WHERE id = $1 AND retain_until <= $2
RETURNING object_key
`

type DeleteRetainedDiagnosticUploadIntentParams struct {
	ID  string
	Now time.Time
}

func (q *Queries) DeleteRetainedDiagnosticUploadIntent(ctx context.Context, arg DeleteRetainedDiagnosticUploadIntentParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteRetainedDiagnosticUploadIntent, arg.ID, arg.Now)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const expireDiagnosticUploadIntents = `-- name: ExpireDiagnosticUploadIntents :many
UPDATE diagnostic_upload_intents
SET state = 'expired'
WHERE state = 'pending' AND expires_at <= $1
RETURNING id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag
`

func (q *Queries) ExpireDiagnosticUploadIntents(ctx context.Context, now time.Time) ([]DiagnosticUploadIntent, error) {
	rows, err := q.db.Query(ctx, expireDiagnosticUploadIntents, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiagnosticUploadIntent
	for rows.Next() {
		var i DiagnosticUploadIntent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CLIClientSessionID,
			&i.OperationKey,
			&i.RequestHash,
			&i.CorrelationID,
			&i.ObjectKey,
			&i.ExpectedBytes,
			&i.Sha256,
			&i.Categories,
			&i.State,
			&i.ExpiresAt,
			&i.RetainUntil,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.ObjectEtag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiagnosticUploadIntentByOperationForUpdate = `-- name: GetDiagnosticUploadIntentByOperationForUpdate :one
SELECT id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag FROM diagnostic_upload_intents
WHERE user_id = $1 AND operation_key = $2
FOR UPDATE
`

type GetDiagnosticUploadIntentByOperationForUpdateParams struct {
	UserID       string
	OperationKey string
}

func (q *Queries) GetDiagnosticUploadIntentByOperationForUpdate(ctx context.Context, arg GetDiagnosticUploadIntentByOperationForUpdateParams) (DiagnosticUploadIntent, error) {
	row := q.db.QueryRow(ctx, getDiagnosticUploadIntentByOperationForUpdate, arg.UserID, arg.OperationKey)
	var i DiagnosticUploadIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.OperationKey,
		&i.RequestHash,
		&i.CorrelationID,
		&i.ObjectKey,
		&i.ExpectedBytes,
		&i.Sha256,
		&i.Categories,
		&i.State,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.ObjectEtag,
	)
	return i, err
}

const getDiagnosticUploadIntentForUserForUpdate = `-- name: GetDiagnosticUploadIntentForUserForUpdate :one
SELECT id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag FROM diagnostic_upload_intents
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetDiagnosticUploadIntentForUserForUpdateParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetDiagnosticUploadIntentForUserForUpdate(ctx context.Context, arg GetDiagnosticUploadIntentForUserForUpdateParams) (DiagnosticUploadIntent, error) {
	row := q.db.QueryRow(ctx, getDiagnosticUploadIntentForUserForUpdate, arg.ID, arg.UserID)
	var i DiagnosticUploadIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.OperationKey,
		&i.RequestHash,
		&i.CorrelationID,
		&i.ObjectKey,
		&i.ExpectedBytes,
		&i.Sha256,
		&i.Categories,
		&i.State,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.ObjectEtag,
	)
	return i, err
}

const listDiagnosticUploadCleanupCandidates = `-- name: ListDiagnosticUploadCleanupCandidates :many
SELECT id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag FROM diagnostic_upload_intents
WHERE (state = 'pending' AND expires_at <= $1) OR retain_until <= $1
ORDER BY LEAST(expires_at, retain_until), id
LIMIT $2
`

type ListDiagnosticUploadCleanupCandidatesParams struct {
	Now      time.Time
	RowLimit int32
}

func (q *Queries) ListDiagnosticUploadCleanupCandidates(ctx context.Context, arg ListDiagnosticUploadCleanupCandidatesParams) ([]DiagnosticUploadIntent, error) {
	rows, err := q.db.Query(ctx, listDiagnosticUploadCleanupCandidates, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiagnosticUploadIntent
	for rows.Next() {
		var i DiagnosticUploadIntent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CLIClientSessionID,
			&i.OperationKey,
			&i.RequestHash,
			&i.CorrelationID,
			&i.ObjectKey,
			&i.ExpectedBytes,
			&i.Sha256,
			&i.Categories,
			&i.State,
			&i.ExpiresAt,
			&i.RetainUntil,
			&i.CreatedAt,
			&i.UploadedAt,
			&i.ObjectEtag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDiagnosticUploadIntentExpired = `-- name: MarkDiagnosticUploadIntentExpired :one
UPDATE diagnostic_upload_intents
SET state = 'expired'
WHERE id = $1 AND state = 'pending' AND expires_at <= $2
RETURNING id, user_id, cli_client_session_id, operation_key, request_hash, correlation_id, object_key, expected_bytes, sha256, categories, state, expires_at, retain_until, created_at, uploaded_at, object_etag
`

type MarkDiagnosticUploadIntentExpiredParams struct {
	ID  string
	Now time.Time
}

func (q *Queries) MarkDiagnosticUploadIntentExpired(ctx context.Context, arg MarkDiagnosticUploadIntentExpiredParams) (DiagnosticUploadIntent, error) {
	row := q.db.QueryRow(ctx, markDiagnosticUploadIntentExpired, arg.ID, arg.Now)
	var i DiagnosticUploadIntent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.OperationKey,
		&i.RequestHash,
		&i.CorrelationID,
		&i.ObjectKey,
		&i.ExpectedBytes,
		&i.Sha256,
		&i.Categories,
		&i.State,
		&i.ExpiresAt,
		&i.RetainUntil,
		&i.CreatedAt,
		&i.UploadedAt,
		&i.ObjectEtag,
	)
	return i, err
}
