// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getGitHubConfigRepoStatus = `-- name: GetGitHubConfigRepoStatus :one
SELECT owner, name, default_branch FROM github_config_repositories
WHERE user_id = $1 AND provisioned_at IS NOT NULL
`

type GetGitHubConfigRepoStatusRow struct {
	Owner         string
	Name          string
	DefaultBranch string
}

func (q *Queries) GetGitHubConfigRepoStatus(ctx context.Context, userID string) (GetGitHubConfigRepoStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getGitHubConfigRepoStatus, userID)
	var i GetGitHubConfigRepoStatusRow
	err := row.Scan(&i.Owner, &i.Name, &i.DefaultBranch)
	return i, err
}

const getGitHubConnectionStatus = `-- name: GetGitHubConnectionStatus :one
SELECT scopes, last_validated_at, token_ciphertext FROM github_oauth_tokens
WHERE user_id = $1 AND revoked_at IS NULL ORDER BY updated_at DESC LIMIT 1
`

type GetGitHubConnectionStatusRow struct {
	Scopes          []string
	LastValidatedAt sql.NullTime
	TokenCiphertext []byte
}

func (q *Queries) GetGitHubConnectionStatus(ctx context.Context, userID string) (GetGitHubConnectionStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getGitHubConnectionStatus, userID)
	var i GetGitHubConnectionStatusRow
	err := row.Scan(pq.Array(&i.Scopes), &i.LastValidatedAt, &i.TokenCiphertext)
	return i, err
}

const getGitHubScopes = `-- name: GetGitHubScopes :one
SELECT scopes FROM github_oauth_tokens
WHERE user_id = $1 AND revoked_at IS NULL ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) GetGitHubScopes(ctx context.Context, userID string) ([]string, error) {
	row := q.db.QueryRowContext(ctx, getGitHubScopes, userID)
	var scopes []string
	err := row.Scan(pq.Array(&scopes))
	return scopes, err
}

const getGitHubToken = `-- name: GetGitHubToken :one
SELECT token_ciphertext, provider_account_login, scopes FROM github_oauth_tokens
WHERE user_id = $1 AND revoked_at IS NULL ORDER BY updated_at DESC LIMIT 1
`

type GetGitHubTokenRow struct {
	TokenCiphertext      []byte
	ProviderAccountLogin string
	Scopes               []string
}

func (q *Queries) GetGitHubToken(ctx context.Context, userID string) (GetGitHubTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getGitHubToken, userID)
	var i GetGitHubTokenRow
	err := row.Scan(&i.TokenCiphertext, &i.ProviderAccountLogin, pq.Array(&i.Scopes))
	return i, err
}

const linkGitHubIdentity = `-- name: LinkGitHubIdentity :one
INSERT INTO user_identities (id, user_id, provider, provider_subject, email, created_at, updated_at)
VALUES ($1, $2, 'github', $3, '', now(), now())
ON CONFLICT (provider, provider_subject) DO UPDATE SET updated_at = now()
RETURNING user_id
`

type LinkGitHubIdentityParams struct {
	ID              string
	UserID          string
	ProviderSubject string
}

func (q *Queries) LinkGitHubIdentity(ctx context.Context, arg LinkGitHubIdentityParams) (string, error) {
	row := q.db.QueryRowContext(ctx, linkGitHubIdentity, arg.ID, arg.UserID, arg.ProviderSubject)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const markGitHubProvisioningSucceeded = `-- name: MarkGitHubProvisioningSucceeded :exec
UPDATE github_repo_provisioning_attempts SET state = 'succeeded', updated_at = now() WHERE idempotency_key = $1
`

func (q *Queries) MarkGitHubProvisioningSucceeded(ctx context.Context, idempotencyKey string) error {
	_, err := q.db.ExecContext(ctx, markGitHubProvisioningSucceeded, idempotencyKey)
	return err
}

const upsertGitHubConfigRepository = `-- name: UpsertGitHubConfigRepository :exec
INSERT INTO github_config_repositories (id, user_id, provider_repo_id, owner, name, default_branch, clone_url, html_url, private, provisioned_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now(), now())
ON CONFLICT (user_id) DO UPDATE SET
	provider_repo_id = EXCLUDED.provider_repo_id, owner = EXCLUDED.owner, name = EXCLUDED.name,
	default_branch = EXCLUDED.default_branch, clone_url = EXCLUDED.clone_url, html_url = EXCLUDED.html_url,
	private = EXCLUDED.private, provisioned_at = now(), updated_at = now(), version = github_config_repositories.version + 1
`

type UpsertGitHubConfigRepositoryParams struct {
	ID             string
	UserID         string
	ProviderRepoID string
	Owner          string
	Name           string
	DefaultBranch  string
	CloneUrl       string
	HtmlUrl        string
	Private        bool
}

func (q *Queries) UpsertGitHubConfigRepository(ctx context.Context, arg UpsertGitHubConfigRepositoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubConfigRepository,
		arg.ID,
		arg.UserID,
		arg.ProviderRepoID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.CloneUrl,
		arg.HtmlUrl,
		arg.Private,
	)
	return err
}

const upsertGitHubOAuthToken = `-- name: UpsertGitHubOAuthToken :exec
INSERT INTO github_oauth_tokens
	(id, user_id, token_ciphertext, refresh_token_ciphertext, scopes, expires_at, provider_account_login, last_validated_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now(), now())
ON CONFLICT (user_id) DO UPDATE SET
	token_ciphertext = EXCLUDED.token_ciphertext,
	refresh_token_ciphertext = EXCLUDED.refresh_token_ciphertext,
	scopes = EXCLUDED.scopes,
	expires_at = EXCLUDED.expires_at,
	provider_account_login = EXCLUDED.provider_account_login,
	revoked_at = NULL,
	last_validated_at = now(),
	updated_at = now(),
	version = github_oauth_tokens.version + 1
`

type UpsertGitHubOAuthTokenParams struct {
	ID                     string
	UserID                 string
	TokenCiphertext        []byte
	RefreshTokenCiphertext []byte
	Scopes                 []string
	ExpiresAt              sql.NullTime
	ProviderAccountLogin   string
}

func (q *Queries) UpsertGitHubOAuthToken(ctx context.Context, arg UpsertGitHubOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubOAuthToken,
		arg.ID,
		arg.UserID,
		arg.TokenCiphertext,
		arg.RefreshTokenCiphertext,
		pq.Array(arg.Scopes),
		arg.ExpiresAt,
		arg.ProviderAccountLogin,
	)
	return err
}

const upsertGitHubProvisioningAttempt = `-- name: UpsertGitHubProvisioningAttempt :exec
INSERT INTO github_repo_provisioning_attempts (id, user_id, idempotency_key, state, repo_owner, repo_name, last_error, attempts, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, now(), now())
ON CONFLICT (idempotency_key) DO UPDATE SET
	state = EXCLUDED.state, repo_owner = EXCLUDED.repo_owner, repo_name = EXCLUDED.repo_name,
	last_error = EXCLUDED.last_error, attempts = github_repo_provisioning_attempts.attempts + 1, updated_at = now()
`

type UpsertGitHubProvisioningAttemptParams struct {
	ID             string
	UserID         string
	IdempotencyKey string
	State          string
	RepoOwner      string
	RepoName       string
	LastError      string
}

func (q *Queries) UpsertGitHubProvisioningAttempt(ctx context.Context, arg UpsertGitHubProvisioningAttemptParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubProvisioningAttempt,
		arg.ID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.State,
		arg.RepoOwner,
		arg.RepoName,
		arg.LastError,
	)
	return err
}
