// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
	"time"
)

type AccessSession struct {
	ID                      string
	UserID                  string
	ProjectID               string
	SessionType             string
	State                   string
	Descriptor              []byte
	ExpiresAt               time.Time
	RevokedAt               sql.NullTime
	IdempotencyKey          string
	Version                 int64
	CreatedAt               time.Time
	UpdatedAt               time.Time
	CLIClientSessionID      sql.NullString
	HelperTerminalSessionID sql.NullString
	HelperFileSessionID     sql.NullString
	HelperRevokedAt         sql.NullTime
	HttpBaseUrl             string
}

type AccountE2eeRoot struct {
	UserID      string
	PublicKey   []byte
	Fingerprint []byte
	Generation  int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RevokedAt   sql.NullTime
}

type AuditEvent struct {
	ID             string
	ActorUserID    sql.NullString
	ActorType      string
	EventType      string
	ResourceType   string
	ResourceID     string
	IdempotencyKey sql.NullString
	Metadata       []byte
	CreatedAt      time.Time
}

type AuthRateLimit struct {
	BucketKey    string
	WindowStart  time.Time
	RequestCount int32
}

type BillingCheckoutReservation struct {
	ID                 string
	UserID             string
	ProductCode        string
	IdempotencyKey     string
	ProviderCheckoutID sql.NullString
	CheckoutUrl        sql.NullString
	State              string
	ExpiresAt          time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	LastError          sql.NullString
	UncertainAt        sql.NullTime
}

type BillingPortalOperation struct {
	IdempotencyKey   string
	UserID           string
	RequestHash      []byte
	State            string
	ResultCiphertext []byte
	LastError        sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type BillingProduct struct {
	ID                string
	Code              string
	Provider          string
	ProviderProductID string
	ProviderPriceID   string
	CatalogType       string
	CatalogRef        string
	Active            bool
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type BillingSubscriptionUpdateOperation struct {
	IdempotencyKey         string
	UserID                 string
	ProviderSubscriptionID string
	RequestHash            []byte
	State                  string
	LastError              sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type BillingUncertainRecovery struct {
	IdempotencyKey string
	OperationKind  string
	OperationID    string
	RequestHash    []byte
	ActorUserID    sql.NullString
	CreatedAt      time.Time
}

type CLIAccessToken struct {
	TokenHash          string
	CLIClientSessionID string
	ExpiresAt          time.Time
	CreatedAt          time.Time
	RevokedAt          sql.NullTime
}

type CLIClientSession struct {
	ID               string
	UserID           string
	ClientID         string
	ClientLabel      string
	DeviceType       string
	Os               string
	Scopes           []string
	State            string
	CreatedAt        time.Time
	ApprovedAt       time.Time
	LastUsedAt       sql.NullTime
	RevokedAt        sql.NullTime
	RevocationReason sql.NullString
	Version          int64
}

type CLIRefreshToken struct {
	TokenHash          string
	CLIClientSessionID string
	State              string
	ExpiresAt          time.Time
	CreatedAt          time.Time
	RotatedAt          sql.NullTime
	RevokedAt          sql.NullTime
}

type CodexSession struct {
	ID                     string
	EnvironmentID          string
	MachineID              string
	UserID                 string
	CLIClientSessionID     string
	IdempotencyKey         string
	RequestHash            []byte
	State                  string
	InstallationGeneration int64
	ConnectorID            string
	ConnectorGeneration    int64
	EdgePool               string
	EdgeNodeID             string
	EdgeAssignmentHost     string
	RemoteCodexVersion     sql.NullString
	FailureCode            sql.NullString
	CleanupStatus          string
	LeaseExpiresAt         time.Time
	PreparedAt             sql.NullTime
	ReconnectingAt         sql.NullTime
	StoppingAt             sql.NullTime
	StoppedAt              sql.NullTime
	LastRenewedAt          time.Time
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type ConnectionEvent struct {
	ID              string
	UserID          sql.NullString
	ProjectID       sql.NullString
	AccessSessionID sql.NullString
	Result          string
	FailureReason   string
	Metadata        []byte
	CreatedAt       time.Time
}

type ControlConfigAssignment struct {
	ID              string
	EnvironmentID   string
	RepositoryID    sql.NullString
	Mode            string
	ConsentState    string
	WarningRevision sql.NullString
	AcceptedAt      sql.NullTime
	RevokedAt       sql.NullTime
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	MachineID       string
}

type ControlConfigConflictResolution struct {
	ID                     string
	EnvironmentID          string
	RepositoryID           string
	AssignmentID           string
	ConflictRevision       string
	Path                   string
	Scope                  string
	Action                 string
	ExpectedRemoteRevision string
	RequestedByUserID      string
	State                  string
	LandedRevision         sql.NullString
	RequestedAt            time.Time
	AppliedAt              sql.NullTime
	UpdatedAt              time.Time
}

type ControlConfigCredential struct {
	JtiHash              []byte
	Jti                  string
	OperationKey         string
	RequestHash          []byte
	EnvironmentID        string
	MachineID            string
	AssignmentID         string
	WarningRevision      sql.NullString
	CredentialCiphertext []byte
	ExpiresAt            time.Time
	RevokedAt            sql.NullTime
	CreatedAt            time.Time
}

type ControlConfigRepository struct {
	ID                   string
	OwnerUserID          string
	Provider             string
	ExternalRef          string
	DisplayName          string
	State                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ProviderAccountID    sql.NullString
	ExternalRepositoryID sql.NullString
	CloneUrl             sql.NullString
	PublishUrl           sql.NullString
	DefaultBranch        sql.NullString
	AuthorizationRef     sql.NullString
	CredentialCapability sql.NullString
	ObservedRevision     sql.NullString
	DisconnectedAt       sql.NullTime
	Version              int64
}

type ControlConfigRepositoryAccessOperation struct {
	OperationID            string
	RequestHash            []byte
	RepositoryID           string
	AssignmentID           string
	EnvironmentID          string
	MachineID              string
	InstallationGeneration int64
	WarningRevision        string
	State                  string
	AccessCiphertext       []byte
	ExpiresAt              sql.NullTime
	RevokedAt              sql.NullTime
	ProviderRevokedAt      sql.NullTime
	RevokeAttempts         int32
	LastErrorCode          sql.NullString
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type ControlConfigRepositoryLeaseAuthority struct {
	RepositoryID           string
	LastFencingToken       int64
	LeaseID                sql.NullString
	AssignmentID           sql.NullString
	EnvironmentID          sql.NullString
	MachineID              sql.NullString
	InstallationGeneration sql.NullInt64
	BaseRemoteRevision     sql.NullString
	OperationID            sql.NullString
	AcquiredAt             sql.NullTime
	ExpiresAt              sql.NullTime
	RevokedAt              sql.NullTime
	Version                int64
	UpdatedAt              time.Time
}

type ControlConfigRepositoryLeaseOperation struct {
	OperationID        string
	OperationType      string
	RequestHash        []byte
	RepositoryID       string
	LeaseID            sql.NullString
	FencingToken       sql.NullInt64
	ResultState        string
	ExpiresAt          sql.NullTime
	CreatedAt          time.Time
	AssignmentID       sql.NullString
	EnvironmentID      sql.NullString
	MachineID          sql.NullString
	BaseRemoteRevision sql.NullString
}

type ControlConfigRepositoryMigrationReview struct {
	Source       string
	SourceID     string
	RepositoryID sql.NullString
	Reason       string
	Details      []byte
	ReviewedAt   sql.NullTime
	CreatedAt    time.Time
}

type ControlConfigSyncMigrationReview struct {
	Source        string
	ProjectID     string
	MachineID     string
	EnvironmentID sql.NullString
	Reason        string
	Details       []byte
	ReviewedAt    sql.NullTime
	CreatedAt     time.Time
}

type ControlConfigSyncStatus struct {
	EnvironmentID          string
	RepositoryID           string
	AssignmentID           string
	MachineID              string
	InstallationGeneration int64
	WarningRevision        string
	PolicyRevision         string
	SyncRevision           int64
	State                  string
	Mode                   string
	RemoteRevision         sql.NullString
	ManifestHealth         string
	ManifestRevision       sql.NullString
	ManagedPathCount       int32
	PendingCleanPathCount  int32
	LastAppliedRevision    sql.NullString
	LastPublishedRevision  sql.NullString
	LeaseID                sql.NullString
	FencingToken           sql.NullInt64
	Skipped                []byte
	Conflicts              []byte
	ErrorCode              sql.NullString
	RecoveryActions        []byte
	LastAttemptAt          sql.NullTime
	LastSuccessfulAt       sql.NullTime
	MachineUpdatedAt       time.Time
	ObservedAt             time.Time
}

type ControlConfigSyncStatusHistory struct {
	EnvironmentID          string
	SyncRevision           int64
	RepositoryID           string
	AssignmentID           string
	MachineID              string
	InstallationGeneration int64
	State                  string
	ErrorCode              sql.NullString
	RemoteRevision         sql.NullString
	ObservedAt             time.Time
}

type ControlConnectorGeneration struct {
	EnvironmentID                 string
	MachineID                     string
	Generation                    int64
	EdgePool                      string
	EdgeNodeID                    sql.NullString
	State                         string
	AdmissionJtiHash              []byte
	AdmissionOperationKey         sql.NullString
	AdmissionRequestHash          []byte
	AdmissionCredentialCiphertext []byte
	ExpiresAt                     sql.NullTime
	RevokedAt                     sql.NullTime
	Version                       int64
	UpdatedAt                     time.Time
	ConnectorID                   string
}

type ControlEnvironment struct {
	ID             string
	WorkspaceID    string
	OwnerUserID    sql.NullString
	DesiredState   string
	DesiredVersion int64
	AppliedState   string
	AppliedVersion int64
	RevokedAt      sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ControlHelper struct {
	ID                             string
	EnvironmentID                  string
	KeyThumbprint                  sql.NullString
	PublicKey                      []byte
	State                          string
	Generation                     int64
	ReplacementOperationKey        sql.NullString
	ReplacementConnectorGeneration sql.NullInt64
	LastSeenAt                     sql.NullTime
	RevokedAt                      sql.NullTime
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

type ControlHelperEnrollment struct {
	ID              string
	EnvironmentID   string
	HelperID        string
	JtiHash         []byte
	OperationKey    string
	RequestHash     []byte
	GrantCiphertext []byte
	State           string
	ExpiresAt       time.Time
	ConsumedAt      sql.NullTime
	RevokedAt       sql.NullTime
	CreatedAt       time.Time
}

type ControlOperation struct {
	ID             string
	OperationKey   string
	OperationType  string
	RequestHash    []byte
	State          string
	Result         []byte
	LastError      sql.NullString
	Attempts       int32
	NextAttemptAt  sql.NullTime
	LeaseExpiresAt sql.NullTime
	UncertainAt    sql.NullTime
	CompletedAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ControlOperationRecovery struct {
	OperationKey string
	OperationID  string
	ActorUserID  sql.NullString
	CreatedAt    time.Time
}

type ControlPreview struct {
	ID                        string
	EnvironmentID             string
	LogicalName               string
	PreviewKey                string
	CollisionCounter          int64
	PublicHost                string
	TargetHost                string
	TargetPort                int32
	State                     string
	RouteID                   sql.NullString
	HelperReady               bool
	EdgeReady                 bool
	TargetReady               bool
	PublicAcknowledgedAt      sql.NullTime
	ExpiresAt                 sql.NullTime
	RemovedAt                 sql.NullTime
	RetainedUntil             sql.NullTime
	Version                   int64
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	HelperObservationRevision int64
	HelperObservedAt          sql.NullTime
	SourceKind                string
	OwnerMode                 string
}

type ControlPreviewOperation struct {
	OperationKey  string
	OperationType string
	RequestHash   []byte
	PreviewID     sql.NullString
	Result        []byte
	CreatedAt     time.Time
}

type ControlReconciliationAttempt struct {
	ID             string
	EnvironmentID  string
	DesiredVersion int64
	State          string
	OperationID    sql.NullString
	StartedAt      time.Time
	FinishedAt     sql.NullTime
	LastError      sql.NullString
}

type ControlRoute struct {
	ID                string
	EnvironmentID     string
	Kind              string
	PublicHost        string
	TargetHost        string
	TargetPort        int32
	DesiredRevision   int64
	DesiredState      string
	AppliedRevision   int64
	AppliedNodeID     sql.NullString
	AppliedGeneration sql.NullInt64
	DrainDeadline     sql.NullTime
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ConnectorID       string
}

type ControlRouteOperation struct {
	OperationKey   string
	OperationType  string
	RequestHash    []byte
	RouteID        string
	ResultRevision sql.NullInt64
	Result         []byte
	CreatedAt      time.Time
}

type ControlSigningKeyRevocation struct {
	KeyID       string
	Reason      string
	RevokedAt   time.Time
	ActorUserID sql.NullString
	CreatedAt   time.Time
}

type ControlSigningKeyRevocationOperation struct {
	OperationKey string
	KeyID        string
	Reason       string
	CreatedAt    time.Time
}

type ControlTunnelNode struct {
	ID               string
	EdgePool         string
	ProtocolVersion  string
	ProcessEpoch     string
	EndpointHost     sql.NullString
	EndpointTcpPort  sql.NullInt32
	EndpointQuicPort sql.NullInt32
	State            string
	Ready            bool
	Capacity         []byte
	Observation      []byte
	LastHeartbeatAt  sql.NullTime
	DrainDeadline    sql.NullTime
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	SignalingHost    sql.NullString
	StunHost         sql.NullString
	StunPort         sql.NullInt32
	RelayID          sql.NullString
	RelayRegion      sql.NullString
	RelayName        sql.NullString
}

type ControlUsageCounter struct {
	EdgeNodeID    string
	CounterEpoch  string
	EnvironmentID string
	RouteID       string
	RouteRevision int64
	Direction     string
	Bytes         int64
	ObservedAt    time.Time
}

type ControlUsageReceipt struct {
	OperationID    string
	EdgeNodeID     string
	CounterEpoch   string
	EnvironmentID  string
	RouteID        string
	RouteRevision  int64
	Direction      string
	ObservedBytes  int64
	DeltaBytes     int64
	IntervalStart  time.Time
	IntervalEnd    time.Time
	AcknowledgedAt sql.NullTime
	CreatedAt      time.Time
}

type ControlUsageVerificationKey struct {
	KeyID      string
	EdgeNodeID string
	PublicKey  []byte
	NotBefore  time.Time
	ExpiresAt  time.Time
	RevokedAt  sql.NullTime
	CreatedAt  time.Time
}

type CreditAccount struct {
	ID        string
	UserID    string
	Balance   string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreditAutoTopupAttempt struct {
	ID              string
	UserID          string
	IdempotencyKey  string
	ProviderOrderID sql.NullString
	State           string
	LastError       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CreditAutoTopupPolicy struct {
	ID                string
	UserID            string
	Enabled           bool
	Threshold         string
	BundleCredits     string
	ProviderProductID string
	UpdatedAt         time.Time
}

type CreditLedgerEntry struct {
	ID             string
	AccountID      string
	EntryType      string
	Amount         string
	SourceType     string
	SourceID       string
	IdempotencyKey string
	Metadata       []byte
	CreatedAt      time.Time
}

type DeviceGrant struct {
	ID                  string
	ClientID            string
	ClientLabel         string
	DeviceType          string
	Os                  string
	Scopes              []string
	DeviceCodeHash      string
	UserCodeHash        string
	State               string
	UserID              sql.NullString
	IssuedAt            time.Time
	ExpiresAt           time.Time
	PollIntervalSeconds int32
	NextPollAt          time.Time
	ApprovedAt          sql.NullTime
	DeniedAt            sql.NullTime
	ConsumedAt          sql.NullTime
	CreatedNetworkHash  string
	Version             int64
}

type DiagnosticUploadIntent struct {
	ID                 string
	UserID             string
	CLIClientSessionID string
	OperationKey       string
	RequestHash        []byte
	CorrelationID      string
	ObjectKey          string
	ExpectedBytes      int64
	Sha256             []byte
	Categories         []string
	State              string
	ExpiresAt          time.Time
	RetainUntil        time.Time
	CreatedAt          time.Time
	UploadedAt         sql.NullTime
	ObjectEtag         sql.NullString
}

type FeatureFlag struct {
	ID        string
	Code      string
	Enabled   bool
	Config    []byte
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FlyMachine struct {
	ID                 string
	ProjectID          string
	FlyMachineID       string
	State              string
	ImageRef           string
	Region             string
	ObservedConfigHash string
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	UserMachineID      string
}

type FlyVolume struct {
	ID          string
	ProjectID   string
	FlyVolumeID string
	SizeGb      int32
	Region      string
	State       string
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GithubConfigRepository struct {
	ID             string
	UserID         string
	ProviderRepoID string
	Owner          string
	Name           string
	DefaultBranch  string
	CloneUrl       string
	HtmlUrl        string
	Private        bool
	ProvisionedAt  sql.NullTime
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GithubOauthToken struct {
	ID                     string
	UserID                 string
	TokenCiphertext        []byte
	Scopes                 []string
	ExpiresAt              sql.NullTime
	RefreshExpiresAt       sql.NullTime
	RevokedAt              sql.NullTime
	LastValidatedAt        sql.NullTime
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RefreshTokenCiphertext []byte
	ProviderAccountLogin   string
}

type GithubRepoProvisioningAttempt struct {
	ID             string
	UserID         string
	IdempotencyKey string
	State          string
	RepoOwner      string
	RepoName       string
	LastError      string
	Attempts       int32
	NextRetryAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type HelperRevocationOutbox struct {
	ID                 string
	UserID             string
	ProjectID          string
	CLIClientSessionID string
	HttpBaseUrl        string
	SessionIds         []string
	Reason             string
	PropagatedAt       sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type HostedHelperIdentityRenewal struct {
	OperationKey       string
	HelperID           string
	EnvironmentID      string
	RequestHash        []byte
	IdentityCiphertext []byte
	ExpiresAt          time.Time
	CreatedAt          time.Time
}

type HostedProviderOperation struct {
	ID                 string
	OrchestrationJobID string
	Step               string
	ResourceType       string
	RequestHash        []byte
	State              string
	Outcome            string
	ProviderRequestID  string
	LastError          string
	Attempts           int32
	UncertainAt        sql.NullTime
	ObservedAt         sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type HostedProviderOperationRecovery struct {
	OperationKey        string
	ProviderOperationID string
	ActorUserID         sql.NullString
	Action              string
	EvidenceReference   string
	CreatedAt           time.Time
}

type HostedReadinessObservation struct {
	ID                 string
	ProjectID          string
	OrchestrationJobID sql.NullString
	Stage              string
	State              string
	Reason             string
	Evidence           []byte
	ObservedAt         time.Time
	CreatedAt          time.Time
}

type MachineControlRenewal struct {
	OperationID            string
	MachineID              string
	InstallationGeneration int64
	CredentialJti          string
	IssuedAt               time.Time
	ExpiresAt              time.Time
	CreatedAt              time.Time
}

type MachineRuntimeInterval struct {
	ID                   string
	ProjectID            string
	UserID               string
	FlyMachineID         string
	MachineTypeVersionID string
	CreditWeight         string
	StartedAt            time.Time
	StoppedAt            sql.NullTime
	LastMeteredAt        time.Time
	ObservedState        string
	ObservationSource    string
	Confidence           string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MachineSshHostKey struct {
	SetID         string
	UserMachineID string
	Fingerprint   []byte
	Ordinal       int16
}

type MachineSshHostKeyOwner struct {
	Fingerprint     []byte
	UserMachineID   string
	Algorithm       string
	PublicKey       string
	FirstObservedAt time.Time
}

type MachineSshHostKeySet struct {
	ID                    string
	UserMachineID         string
	MachineGeneration     int64
	ObservationGeneration int64
	SetFingerprint        []byte
	State                 string
	ReconciliationVersion int64
	ObservedAt            time.Time
	PromotedAt            sql.NullTime
	RejectedAt            sql.NullTime
	RejectionReason       sql.NullString
}

type MachineSshTarget struct {
	UserMachineID         string
	MachineGeneration     int64
	OsUser                string
	TargetPort            int32
	ReconciliationVersion int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type MachineType struct {
	ID                 string
	Code               string
	Name               string
	Vcpu               int32
	MemoryMb           int32
	CreditWeight       string
	CustomShapeAllowed bool
	Active             bool
	CurrentVersionID   sql.NullString
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type MachineTypeVersion struct {
	ID            string
	MachineTypeID string
	VersionNumber int32
	Vcpu          int32
	MemoryMb      int32
	CreditWeight  string
	Metadata      []byte
	CreatedAt     time.Time
}

type ManagedSshClientKey struct {
	Fingerprint           []byte
	UserID                string
	CLIClientSessionID    string
	Algorithm             string
	PublicKey             string
	State                 string
	ReconciliationVersion int64
	CreatedAt             time.Time
	RevokedAt             sql.NullTime
	RevocationReason      sql.NullString
}

type ManagedSshOperation struct {
	OperationID    string
	UserID         string
	OperationKind  string
	RequestHash    []byte
	ResourceID     string
	ResultRevision int64
	CreatedAt      time.Time
}

type MeteringCheckpoint struct {
	ID                string
	RuntimeIntervalID string
	ProjectID         string
	UserID            string
	PeriodStart       time.Time
	PeriodEnd         time.Time
	RuntimeSeconds    int32
	CreditWeight      string
	CreditsDebited    string
	IdempotencyKey    string
	State             string
	LastError         string
	CreatedAt         time.Time
	ProcessedAt       sql.NullTime
}

type OrchestrationJob struct {
	ID             string
	JobType        string
	AggregateType  string
	AggregateID    string
	IdempotencyKey string
	State          string
	Attempts       int32
	NextRunAt      time.Time
	Payload        []byte
	LastError      string
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LeaseToken     string
	LeaseExpiresAt sql.NullTime
}

type PeerEndpointCertificate struct {
	Fingerprint      []byte
	UserID           string
	EndpointID       string
	Role             string
	Generation       int64
	Serial           int64
	Certificate      []byte
	NoisePublicKey   []byte
	QuicPublicKey    []byte
	IssuedAt         time.Time
	ExpiresAt        time.Time
	CreatedAt        time.Time
	RevokedAt        sql.NullTime
	RevocationReason sql.NullString
}

type PeerEndpointCertificateOperation struct {
	OperationID            string
	UserID                 string
	RequestHash            []byte
	CertificateFingerprint []byte
	CreatedAt              time.Time
}

type PeerEndpointCertificateRevocation struct {
	OperationID            string
	UserID                 string
	CertificateFingerprint []byte
	Serial                 int64
	Reason                 string
	CreatedAt              time.Time
}

type PeerEndpointEnrollmentRequest struct {
	ID                     string
	OperationKey           string
	RequestHash            []byte
	UserID                 string
	EndpointID             string
	Generation             int64
	Role                   string
	NoisePublicKey         []byte
	QuicPublicKey          []byte
	State                  string
	CertificateFingerprint []byte
	CreatedAt              time.Time
	ExpiresAt              time.Time
	FulfilledAt            sql.NullTime
}

type PeerRelayAllocation struct {
	IntentID        string
	RouteAllocation []byte
	Jti             string
	RouteGeneration int64
	ByteLimit       int64
	IssuedAt        time.Time
	ExpiresAt       time.Time
	RevokedAt       sql.NullTime
}

type PeerRelaySelectionState struct {
	UserID                   string
	MachineID                string
	NetworkGeneration        int64
	HostWorkerGeneration     int64
	CurrentRegion            sql.NullString
	ClientGeneration         int64
	ClientObservedAt         sql.NullTime
	CandidateRegion          sql.NullString
	CandidateFirstObservedAt sql.NullTime
	CandidateLastObservedAt  sql.NullTime
	CandidateSamples         int32
	UpdatedAt                time.Time
}

type PeerSessionIntent struct {
	ID                                string
	OperationKey                      string
	RequestHash                       []byte
	UserID                            string
	CLIClientSessionID                string
	EnvironmentID                     string
	Purpose                           string
	EdgeNodeID                        string
	ControllingCertificateFingerprint []byte
	ControlledCertificateFingerprint  []byte
	AttemptGeneration                 int64
	NetworkGeneration                 int64
	State                             string
	ExpiresAt                         time.Time
	RevokedAt                         sql.NullTime
	RevocationReason                  sql.NullString
	CreatedAt                         time.Time
	IceCredentialsCiphertext          []byte
	EdgePool                          sql.NullString
	SignalingHost                     sql.NullString
	StunHost                          sql.NullString
	StunPort                          sql.NullInt32
	ControlledDeliveredAt             sql.NullTime
}

type PeerSessionRevocationOperation struct {
	OperationKey string
	IntentID     string
	ActorUserID  sql.NullString
	Reason       string
	CreatedAt    time.Time
}

type PeerSignalingGrant struct {
	IntentID       string
	Role           string
	EndpointID     string
	PeerEndpointID string
	Jti            string
	IssuedAt       time.Time
	ExpiresAt      time.Time
	RevokedAt      sql.NullTime
}

type Plan struct {
	ID               string
	Code             string
	Name             string
	Active           bool
	CurrentVersionID sql.NullString
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type PlanVersion struct {
	ID                string
	PlanID            string
	VersionNumber     int32
	IncludedCredits   string
	IncludedStorageGb int32
	Metadata          []byte
	CreatedAt         time.Time
}

type PolarEvent struct {
	ID              string
	ProviderEventID string
	EventType       string
	ProcessedState  string
	Payload         []byte
	ProcessedAt     sql.NullTime
	CreatedAt       time.Time
}

type PreviewUrlRecord struct {
	ID         string
	ProjectID  string
	PreviewKey string
	TargetUrl  string
	PublicUrl  string
	State      string
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Project struct {
	ID                string
	UserID            string
	Name              string
	State             string
	IdempotencyKey    string
	CreateRequestHash string
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProjectCredential struct {
	ID             string
	ProjectID      string
	CredentialType string
	Ciphertext     []byte
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProjectEvent struct {
	ID        string
	ProjectID string
	EventType string
	Message   string
	Metadata  []byte
	CreatedAt time.Time
}

type ProjectRepository struct {
	ProjectID     string
	Provider      string
	SourceUrl     string
	DefaultBranch string
	CloneMetadata []byte
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ProjectRuntimeConfig struct {
	ProjectID                   string
	MachineTypeVersionID        sql.NullString
	PresetVersionIds            []string
	SetupScriptRef              string
	RegionID                    sql.NullString
	PendingRestartApply         bool
	DesiredConfigHash           string
	AppliedStorageGb            int32
	AppliedMachineTypeVersionID sql.NullString
	AppliedPresetVersionIds     []string
	AppliedSetupScriptRef       string
	AppliedRegionID             sql.NullString
	AppliedConfigHash           string
	Version                     int64
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

type ProjectSetupScriptRevision struct {
	ID               string
	ProjectID        string
	RevisionNumber   int32
	ScriptSha256     string
	ScriptCiphertext []byte
	Guidance         string
	CreatedByUserID  string
	CreatedAt        time.Time
}

type ProjectStorageAllocation struct {
	ProjectID        string
	StorageAccountID string
	AssignedGb       int32
	FlyVolumeID      sql.NullString
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ProjectTerminalSession struct {
	ID                           string
	ProjectID                    string
	TerminalID                   string
	ThreadID                     string
	Name                         string
	IdempotencyKey               sql.NullString
	IsDefault                    bool
	AutoNameOrdinal              sql.NullInt32
	LaunchCwd                    string
	DesiredState                 string
	RuntimeState                 string
	LastActivityAt               sql.NullTime
	LastRuntimeSyncAt            sql.NullTime
	LastRuntimeSequence          sql.NullInt64
	DeletedAt                    sql.NullTime
	Version                      int64
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	TransferDestinationMachineID sql.NullString
}

type ProviderEvent struct {
	ID              string
	Provider        string
	ProviderEventID string
	EventType       string
	ProcessedState  string
	Payload         []byte
	ProcessedAt     sql.NullTime
	CreatedAt       time.Time
}

type ProviderRoute struct {
	ID         string
	ProjectID  string
	TunnelID   string
	ClientID   string
	ResourceID string
	Metadata   []byte
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ProviderRouteCleanupOutbox struct {
	ID           string
	ProjectID    string
	Action       string
	Reason       string
	PropagatedAt sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ReconciliationRun struct {
	ID         string
	Scope      string
	State      string
	Findings   []byte
	StartedAt  time.Time
	FinishedAt sql.NullTime
}

type Region struct {
	ID              string
	Code            string
	Name            string
	Enabled         bool
	PlacementPolicy []byte
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type ReleaseAuthorityBundle struct {
	ID                 string
	ReleaseID          string
	Version            string
	Platform           string
	Architecture       string
	Action             string
	PolicyRevision     int64
	Payload            []byte
	PayloadHash        []byte
	Signatures         []byte
	IssuedAt           time.Time
	ExpiresAt          time.Time
	AuthorityRequestID string
	ImportedByUserID   string
	ImportedAt         time.Time
}

type ReleaseAuthorityImportOperation struct {
	ActorUserID    string
	IdempotencyKey string
	RequestHash    []byte
	BundleID       string
	CreatedAt      time.Time
}

type ReleaseAuthorityRequest struct {
	ID                string
	Action            string
	ReleaseID         string
	Version           string
	Platform          string
	Architecture      string
	PolicyRevision    int64
	RolloutPercentage int32
	Status            string
	RequestedByUserID string
	IdempotencyKey    string
	RequestHash       []byte
	FulfilledBundleID sql.NullString
	CreatedAt         time.Time
	FulfilledAt       sql.NullTime
}

type Session struct {
	ID          string
	UserID      string
	SessionHash string
	CsrfHash    string
	ExpiresAt   time.Time
	RotatedAt   sql.NullTime
	RevokedAt   sql.NullTime
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type StorageAccount struct {
	ID          string
	UserID      string
	IncludedGb  int32
	PurchasedGb int32
	AllocatedGb int32
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type StorageLedgerEntry struct {
	ID             string
	AccountID      string
	EntryType      string
	AmountGb       int32
	SourceType     string
	SourceID       string
	IdempotencyKey string
	Metadata       []byte
	CreatedAt      time.Time
}

type Subscription struct {
	ID                     string
	UserID                 string
	Provider               string
	ProviderSubscriptionID string
	State                  string
	ActivePlanVersionID    sql.NullString
	CurrentPeriodStart     sql.NullTime
	CurrentPeriodEnd       sql.NullTime
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	StorageUnits           int32
	PendingStorageUnits    sql.NullInt32
	PendingPlanVersionID   sql.NullString
}

type TerminalSessionOperation struct {
	ID                string
	ProjectID         string
	TerminalSessionID string
	Operation         string
	State             string
	Attempts          int32
	NextAttemptAt     time.Time
	LastError         sql.NullString
	CompletedAt       sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type User struct {
	ID            string
	WorkosSubject string
	PrimaryEmail  string
	DisplayName   string
	Status        string
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Role          string
}

type UserFavorite struct {
	UserID     string
	Kind       string
	ResourceID string
	CreatedAt  time.Time
}

type UserIdentity struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	Email           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserMachine struct {
	ID                            string
	UserID                        string
	EnvironmentID                 string
	DisplayName                   string
	Platform                      string
	Architecture                  string
	WorkspaceRoot                 string
	State                         string
	SeatState                     string
	Online                        bool
	ProviderRouteRouteID          sql.NullString
	ProviderRouteClientID         sql.NullString
	ProviderRouteHttpBaseUrl      sql.NullString
	ProviderRouteWebsocketBaseUrl sql.NullString
	RuntimeVersions               []byte
	EnrolledAt                    sql.NullTime
	LastSeenAt                    sql.NullTime
	RevokedAt                     sql.NullTime
	DisconnectedAt                sql.NullTime
	DeletedAt                     sql.NullTime
	Version                       int64
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	AvailabilityMode              string
	AvailabilityDesiredVersion    int64
	AvailabilityObservedMode      sql.NullString
	AvailabilityObservedVersion   int64
	AvailabilityObservedAt        sql.NullTime
	AvailabilityStatus            string
	AvailabilityErrorCode         sql.NullString
	HostServiceVersion            sql.NullString
	HostServiceScope              sql.NullString
	WorkerGeneration              int64
	OsBootID                      sql.NullString
	WorkerServiceScope            string
	ConnectorState                string
	ConnectorGeneration           int64
	HostUpdateRollbacks           int64
	RuntimeDiagnosticsObservedAt  sql.NullTime
	SetupRoles                    []string
	PublicIdentityKey             sql.NullString
	InstallationGeneration        int64
	MachineKind                   string
	SetupMode                     string
	ConfiguredCapabilities        []string
	ObservedCapabilities          []string
	Alias                         string
	UpdateHealth                  string
	RelayLatencyWorkerGeneration  int64
	RelayLatencyGeneration        int64
	RelayLatencyObservedAt        sql.NullTime
	RelayLatencyVector            []byte
}

type UserMachineAccessSession struct {
	ID                      string
	UserMachineID           string
	UserID                  string
	EnvironmentID           string
	CLIClientSessionID      string
	HttpBaseUrl             string
	HelperTerminalSessionID sql.NullString
	HelperFileSessionID     sql.NullString
	State                   string
	RevocationReason        sql.NullString
	RevokedAt               sql.NullTime
	HelperRevokedAt         sql.NullTime
	ExpiresAt               time.Time
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type UserMachineAvailabilityOperation struct {
	ID               string
	UserMachineID    string
	UserID           string
	IdempotencyKey   string
	RequestHash      []byte
	ExpectedVersion  int64
	ResultingVersion int64
	Mode             string
	Result           []byte
	CreatedAt        time.Time
}

type UserMachineBandwidthPeriod struct {
	ID                    string
	UserMachineID         string
	PeriodStart           time.Time
	PeriodEnd             time.Time
	IncludedBytes         int64
	ConsumedIncludedBytes int64
	ConsumedTopupBytes    int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type UserMachineBandwidthTopup struct {
	ID              string
	UserID          string
	ProviderOrderID sql.NullString
	PurchasedBytes  int64
	RemainingBytes  int64
	State           string
	ExpiresAt       sql.NullTime
	ConsumedAt      sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserMachineEnrollment struct {
	ID                       string
	UserID                   string
	OperationID              string
	IdempotencyKey           string
	BootstrapTokenHash       []byte
	BootstrapTokenCiphertext []byte
	State                    string
	Generation               int64
	PairingID                sql.NullString
	UserMachineID            sql.NullString
	RequestedDisplayName     sql.NullString
	Platform                 sql.NullString
	Architecture             sql.NullString
	WorkspaceRoot            sql.NullString
	ExpiresAt                time.Time
	CancelledAt              sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type UserMachineEntitlement struct {
	ID                     string
	UserID                 string
	ProviderSubscriptionID string
	ProductCode            string
	State                  string
	SeatQuantity           int32
	AllowanceBytes         int64
	CurrentPeriodStart     time.Time
	CurrentPeriodEnd       time.Time
	UpdatedAt              time.Time
	CreatedAt              time.Time
}

type UserMachineMaintenanceApproval struct {
	ID              string
	UserMachineID   string
	UserID          string
	Schema          string
	Action          string
	TargetVersion   string
	Reason          string
	Status          string
	IdempotencyKey  string
	RequestHash     []byte
	ExpiresAt       time.Time
	DecidedAt       sql.NullTime
	DecidedByUserID sql.NullString
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserMachinePairing struct {
	ID                               string
	VerifierHash                     []byte
	UserCode                         string
	RequestedDisplayName             string
	Platform                         string
	Architecture                     string
	WorkspaceRoot                    string
	RuntimeVersions                  []byte
	State                            string
	ApprovedByUserID                 sql.NullString
	UserMachineID                    sql.NullString
	InstallationConfigCiphertext     []byte
	InstallationConfigNonce          []byte
	InstallationConfigConsumedAt     sql.NullTime
	ExpiresAt                        time.Time
	ApprovedAt                       sql.NullTime
	DeniedAt                         sql.NullTime
	CreatedAt                        time.Time
	UpdatedAt                        time.Time
	PublicIdentityKey                string
	SshUser                          sql.NullString
	SshPort                          sql.NullInt32
	CanReuseRuntimeIdentity          bool
	InstallationRecoveryOperationKey sql.NullString
}

type UserMachineTerminalSession struct {
	ID                           string
	UserMachineID                string
	TerminalID                   string
	ThreadID                     string
	Name                         string
	IdempotencyKey               sql.NullString
	IsDefault                    bool
	AutoNameOrdinal              sql.NullInt32
	LaunchCwd                    string
	DesiredState                 string
	RuntimeState                 string
	LastActivityAt               sql.NullTime
	LastRuntimeSyncAt            sql.NullTime
	LastRuntimeSequence          sql.NullInt64
	DeletedAt                    sql.NullTime
	Version                      int64
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	TransferDestinationMachineID sql.NullString
}

type UserMachineTerminalSessionOperation struct {
	ID                string
	UserMachineID     string
	TerminalSessionID string
	Operation         string
	State             string
	Attempts          int32
	NextAttemptAt     time.Time
	LastError         sql.NullString
	CompletedAt       sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type UserMachineUpdateObservation struct {
	UserMachineID          string
	EnvironmentID          string
	Schema                 string
	CurrentVersion         string
	TargetVersion          sql.NullString
	Channel                string
	State                  string
	ErrorCode              sql.NullString
	OperationID            string
	InstallationGeneration int64
	WorkerGeneration       int64
	OsBootID               string
	RollbackCount          int64
	ObservedAt             time.Time
	PayloadHash            []byte
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type UserTransferDestinationDefault struct {
	UserID    string
	MachineID string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type VmPreset struct {
	ID               string
	Code             string
	Name             string
	Description      string
	Active           bool
	CurrentVersionID sql.NullString
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type VmPresetVersion struct {
	ID            string
	PresetID      string
	VersionNumber int32
	Manifest      []byte
	CreatedAt     time.Time
}
