// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AccessSession struct {
	ID                         string
	UserID                     string
	ProjectID                  string
	SessionType                string
	State                      string
	Descriptor                 json.RawMessage
	ExpiresAt                  time.Time
	RevokedAt                  sql.NullTime
	IdempotencyKey             string
	Version                    int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	ClientSessionID            sql.NullString
	PapercodeTerminalSessionID sql.NullString
	PapercodeFileSessionID     sql.NullString
	PapercodeRevokedAt         sql.NullTime
}

type AgentunnelCleanupOutbox struct {
	ID           string
	ProjectID    string
	Action       string
	Reason       string
	PropagatedAt sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AgentunnelResource struct {
	ID         string
	ProjectID  string
	TunnelID   string
	ClientID   string
	ResourceID string
	Metadata   json.RawMessage
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AuditEvent struct {
	ID             string
	ActorUserID    sql.NullString
	ActorType      string
	EventType      string
	ResourceType   string
	ResourceID     string
	IdempotencyKey sql.NullString
	Metadata       json.RawMessage
	CreatedAt      time.Time
}

type AuthRateLimit struct {
	BucketKey    string
	WindowStart  time.Time
	RequestCount int32
}

type BillingProduct struct {
	ID                string
	Code              string
	Provider          string
	ProviderProductID string
	ProviderPriceID   string
	CatalogType       string
	CatalogRef        string
	Active            bool
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ClientAccessToken struct {
	TokenHash       string
	ClientSessionID string
	ExpiresAt       time.Time
	CreatedAt       time.Time
	RevokedAt       sql.NullTime
}

type ClientRefreshToken struct {
	TokenHash       string
	ClientSessionID string
	State           string
	ExpiresAt       time.Time
	CreatedAt       time.Time
	RotatedAt       sql.NullTime
	RevokedAt       sql.NullTime
}

type ClientSession struct {
	ID               string
	UserID           string
	ClientID         string
	ClientLabel      string
	DeviceType       string
	Os               string
	Scopes           []string
	State            string
	CreatedAt        time.Time
	ApprovedAt       time.Time
	LastUsedAt       sql.NullTime
	RevokedAt        sql.NullTime
	RevocationReason sql.NullString
	Version          int64
}

type ConfigSyncStatus struct {
	ProjectID            string
	MachineID            string
	State                string
	LastAttemptAt        sql.NullTime
	LastSuccessfulSyncAt sql.NullTime
	RemoteCommit         string
	PendingPathCount     int32
	Skipped              json.RawMessage
	Conflicts            json.RawMessage
	ErrorCode            string
	ErrorMessage         string
	MaxFileBytes         int64
	MaxBatchBytes        int64
	PolicyRevision       string
	HeartbeatAt          time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	StatusUpdatedAt      time.Time
	ReceivedAt           time.Time
	StatusObservedAt     time.Time
}

type ConnectionEvent struct {
	ID              string
	UserID          sql.NullString
	ProjectID       sql.NullString
	AccessSessionID sql.NullString
	Result          string
	FailureReason   string
	Metadata        json.RawMessage
	CreatedAt       time.Time
}

type CreditAccount struct {
	ID        string
	UserID    string
	Balance   string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreditLedgerEntry struct {
	ID             string
	AccountID      string
	EntryType      string
	Amount         string
	SourceType     string
	SourceID       string
	IdempotencyKey string
	Metadata       json.RawMessage
	CreatedAt      time.Time
}

type DeviceGrant struct {
	ID                  string
	ClientID            string
	ClientLabel         string
	DeviceType          string
	Os                  string
	Scopes              []string
	DeviceCodeHash      string
	UserCodeHash        string
	State               string
	UserID              sql.NullString
	IssuedAt            time.Time
	ExpiresAt           time.Time
	PollIntervalSeconds int32
	NextPollAt          time.Time
	ApprovedAt          sql.NullTime
	DeniedAt            sql.NullTime
	ConsumedAt          sql.NullTime
	CreatedNetworkHash  string
	Version             int64
}

type FeatureFlag struct {
	ID        string
	Code      string
	Enabled   bool
	Config    json.RawMessage
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FlyMachine struct {
	ID                 string
	ProjectID          string
	FlyMachineID       string
	State              string
	ImageRef           string
	Region             string
	ObservedConfigHash string
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type FlyVolume struct {
	ID          string
	ProjectID   string
	FlyVolumeID string
	SizeGb      int32
	Region      string
	State       string
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GithubConfigRepository struct {
	ID             string
	UserID         string
	ProviderRepoID string
	Owner          string
	Name           string
	DefaultBranch  string
	CloneUrl       string
	HtmlUrl        string
	Private        bool
	ProvisionedAt  sql.NullTime
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GithubOauthToken struct {
	ID                     string
	UserID                 string
	TokenCiphertext        []byte
	Scopes                 []string
	ExpiresAt              sql.NullTime
	RefreshExpiresAt       sql.NullTime
	RevokedAt              sql.NullTime
	LastValidatedAt        sql.NullTime
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RefreshTokenCiphertext []byte
	ProviderAccountLogin   string
}

type GithubRepoProvisioningAttempt struct {
	ID             string
	UserID         string
	IdempotencyKey string
	State          string
	RepoOwner      string
	RepoName       string
	LastError      string
	Attempts       int32
	NextRetryAt    sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IdleTimeoutOption struct {
	ID              string
	Code            string
	DurationSeconds int32
	Active          bool
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MachineRuntimeInterval struct {
	ID                   string
	ProjectID            string
	UserID               string
	FlyMachineID         string
	MachineTypeVersionID string
	CreditWeight         string
	StartedAt            time.Time
	StoppedAt            sql.NullTime
	LastMeteredAt        time.Time
	ObservedState        string
	ObservationSource    string
	Confidence           string
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type MachineType struct {
	ID                 string
	Code               string
	Name               string
	Vcpu               int32
	MemoryMb           int32
	CreditWeight       string
	CustomShapeAllowed bool
	Active             bool
	CurrentVersionID   sql.NullString
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type MachineTypeVersion struct {
	ID            string
	MachineTypeID string
	VersionNumber int32
	Vcpu          int32
	MemoryMb      int32
	CreditWeight  string
	Metadata      json.RawMessage
	CreatedAt     time.Time
}

type MeteringCheckpoint struct {
	ID                string
	RuntimeIntervalID string
	ProjectID         string
	UserID            string
	PeriodStart       time.Time
	PeriodEnd         time.Time
	RuntimeSeconds    int32
	CreditWeight      string
	CreditsDebited    string
	IdempotencyKey    string
	State             string
	LastError         string
	CreatedAt         time.Time
	ProcessedAt       sql.NullTime
}

type OrchestrationJob struct {
	ID             string
	JobType        string
	AggregateType  string
	AggregateID    string
	IdempotencyKey string
	State          string
	Attempts       int32
	NextRunAt      time.Time
	Payload        json.RawMessage
	LastError      string
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PapercodeRevocationOutbox struct {
	ID              string
	UserID          string
	ProjectID       string
	ClientSessionID string
	HttpBaseUrl     string
	SessionIds      []string
	Reason          string
	PropagatedAt    sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Plan struct {
	ID               string
	Code             string
	Name             string
	Active           bool
	CurrentVersionID sql.NullString
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type PlanVersion struct {
	ID                string
	PlanID            string
	VersionNumber     int32
	IncludedCredits   string
	IncludedStorageGb int32
	Metadata          json.RawMessage
	CreatedAt         time.Time
}

type PolarEvent struct {
	ID              string
	ProviderEventID string
	EventType       string
	ProcessedState  string
	Payload         json.RawMessage
	ProcessedAt     sql.NullTime
	CreatedAt       time.Time
}

type PreviewUrlRecord struct {
	ID         string
	ProjectID  string
	PreviewKey string
	TargetUrl  string
	PublicUrl  string
	State      string
	Version    int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Project struct {
	ID                string
	UserID            string
	Name              string
	State             string
	IdempotencyKey    string
	CreateRequestHash string
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProjectActivityMarker struct {
	ProjectID         string
	LastActivityAt    time.Time
	Source            string
	Metadata          json.RawMessage
	CreatedAt         time.Time
	UpdatedAt         time.Time
	MachineID         string
	LastHeartbeatAt   sql.NullTime
	ReporterVersion   string
	Signals           json.RawMessage
	KeepAliveUntil    sql.NullTime
	ReporterLostSince sql.NullTime
	IdleWarningSentAt sql.NullTime
}

type ProjectCredential struct {
	ID             string
	ProjectID      string
	CredentialType string
	Ciphertext     []byte
	Version        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProjectEvent struct {
	ID        string
	ProjectID string
	EventType string
	Message   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

type ProjectRepository struct {
	ProjectID     string
	Provider      string
	SourceUrl     string
	DefaultBranch string
	CloneMetadata json.RawMessage
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ProjectRuntimeConfig struct {
	ProjectID                   string
	MachineTypeVersionID        sql.NullString
	PresetVersionIds            []string
	SetupScriptRef              string
	IdleTimeoutOptionID         sql.NullString
	RegionID                    sql.NullString
	PendingRestartApply         bool
	DesiredConfigHash           string
	AppliedStorageGb            int32
	AppliedMachineTypeVersionID sql.NullString
	AppliedPresetVersionIds     []string
	AppliedSetupScriptRef       string
	AppliedIdleTimeoutOptionID  sql.NullString
	AppliedRegionID             sql.NullString
	AppliedConfigHash           string
	Version                     int64
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
}

type ProjectSetupScriptRevision struct {
	ID               string
	ProjectID        string
	RevisionNumber   int32
	ScriptSha256     string
	ScriptCiphertext []byte
	Guidance         string
	CreatedByUserID  string
	CreatedAt        time.Time
}

type ProjectStorageAllocation struct {
	ProjectID        string
	StorageAccountID string
	AssignedGb       int32
	FlyVolumeID      sql.NullString
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ProviderEvent struct {
	ID              string
	Provider        string
	ProviderEventID string
	EventType       string
	ProcessedState  string
	Payload         json.RawMessage
	ProcessedAt     sql.NullTime
	CreatedAt       time.Time
}

type ReconciliationRun struct {
	ID         string
	Scope      string
	State      string
	Findings   json.RawMessage
	StartedAt  time.Time
	FinishedAt sql.NullTime
}

type Region struct {
	ID              string
	Code            string
	Name            string
	Enabled         bool
	PlacementPolicy json.RawMessage
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	ID          string
	UserID      string
	SessionHash string
	CsrfHash    string
	ExpiresAt   time.Time
	RotatedAt   sql.NullTime
	RevokedAt   sql.NullTime
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type StorageAccount struct {
	ID          string
	UserID      string
	IncludedGb  int32
	PurchasedGb int32
	AllocatedGb int32
	Version     int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type StorageLedgerEntry struct {
	ID             string
	AccountID      string
	EntryType      string
	AmountGb       int32
	SourceType     string
	SourceID       string
	IdempotencyKey string
	Metadata       json.RawMessage
	CreatedAt      time.Time
}

type Subscription struct {
	ID                     string
	UserID                 string
	Provider               string
	ProviderSubscriptionID string
	State                  string
	ActivePlanVersionID    sql.NullString
	CurrentPeriodStart     sql.NullTime
	CurrentPeriodEnd       sql.NullTime
	Version                int64
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type User struct {
	ID            string
	WorkosSubject string
	PrimaryEmail  string
	DisplayName   string
	Status        string
	Version       int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Role          string
}

type UserIdentity struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	Email           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type VmPreset struct {
	ID               string
	Code             string
	Name             string
	Description      string
	Active           bool
	CurrentVersionID sql.NullString
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type VmPresetVersion struct {
	ID            string
	PresetID      string
	VersionNumber int32
	Manifest      json.RawMessage
	CreatedAt     time.Time
}
