// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peer_sessions.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPeerRelayAllocation = `-- name: CreatePeerRelayAllocation :one
INSERT INTO peer_relay_allocations
  (intent_id, route_allocation, jti, route_generation, byte_limit, issued_at, expires_at)
VALUES
  ($1, $2, $3, $4,
   $5, $6, $7)
RETURNING intent_id, route_allocation, jti, route_generation, byte_limit, issued_at, expires_at, revoked_at
`

type CreatePeerRelayAllocationParams struct {
	IntentID        string
	RouteAllocation []byte
	Jti             string
	RouteGeneration int64
	ByteLimit       int64
	IssuedAt        time.Time
	ExpiresAt       time.Time
}

func (q *Queries) CreatePeerRelayAllocation(ctx context.Context, arg CreatePeerRelayAllocationParams) (PeerRelayAllocation, error) {
	row := q.db.QueryRow(ctx, createPeerRelayAllocation,
		arg.IntentID,
		arg.RouteAllocation,
		arg.Jti,
		arg.RouteGeneration,
		arg.ByteLimit,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i PeerRelayAllocation
	err := row.Scan(
		&i.IntentID,
		&i.RouteAllocation,
		&i.Jti,
		&i.RouteGeneration,
		&i.ByteLimit,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createPeerSessionIntent = `-- name: CreatePeerSessionIntent :one
INSERT INTO peer_session_intents
  (id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose,
   edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint,
   attempt_generation, network_generation, ice_credentials_ciphertext, edge_pool,
   signaling_host, stun_host, stun_port, expires_at, created_at)
VALUES
  ($1, $2, $3, $4,
   $5, $6, $7, $8,
   $9, $10,
   $11, $12, $13,
   $14, $15, $16, $17,
   $18, $19)
RETURNING id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose, edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint, attempt_generation, network_generation, state, expires_at, revoked_at, revocation_reason, created_at, ice_credentials_ciphertext, edge_pool, signaling_host, stun_host, stun_port, controlled_delivered_at
`

type CreatePeerSessionIntentParams struct {
	ID                                string
	OperationKey                      string
	RequestHash                       []byte
	UserID                            string
	CLIClientSessionID                string
	EnvironmentID                     string
	Purpose                           string
	EdgeNodeID                        string
	ControllingCertificateFingerprint []byte
	ControlledCertificateFingerprint  []byte
	AttemptGeneration                 int64
	NetworkGeneration                 int64
	IceCredentialsCiphertext          []byte
	EdgePool                          sql.NullString
	SignalingHost                     sql.NullString
	StunHost                          sql.NullString
	StunPort                          sql.NullInt32
	ExpiresAt                         time.Time
	CreatedAt                         time.Time
}

func (q *Queries) CreatePeerSessionIntent(ctx context.Context, arg CreatePeerSessionIntentParams) (PeerSessionIntent, error) {
	row := q.db.QueryRow(ctx, createPeerSessionIntent,
		arg.ID,
		arg.OperationKey,
		arg.RequestHash,
		arg.UserID,
		arg.CLIClientSessionID,
		arg.EnvironmentID,
		arg.Purpose,
		arg.EdgeNodeID,
		arg.ControllingCertificateFingerprint,
		arg.ControlledCertificateFingerprint,
		arg.AttemptGeneration,
		arg.NetworkGeneration,
		arg.IceCredentialsCiphertext,
		arg.EdgePool,
		arg.SignalingHost,
		arg.StunHost,
		arg.StunPort,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i PeerSessionIntent
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.EnvironmentID,
		&i.Purpose,
		&i.EdgeNodeID,
		&i.ControllingCertificateFingerprint,
		&i.ControlledCertificateFingerprint,
		&i.AttemptGeneration,
		&i.NetworkGeneration,
		&i.State,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.IceCredentialsCiphertext,
		&i.EdgePool,
		&i.SignalingHost,
		&i.StunHost,
		&i.StunPort,
		&i.ControlledDeliveredAt,
	)
	return i, err
}

const createPeerSignalingGrant = `-- name: CreatePeerSignalingGrant :one
INSERT INTO peer_signaling_grants
  (intent_id, role, endpoint_id, peer_endpoint_id, jti, issued_at, expires_at)
VALUES
  ($1, $2, $3, $4,
   $5, $6, $7)
RETURNING intent_id, role, endpoint_id, peer_endpoint_id, jti, issued_at, expires_at, revoked_at
`

type CreatePeerSignalingGrantParams struct {
	IntentID       string
	Role           string
	EndpointID     string
	PeerEndpointID string
	Jti            string
	IssuedAt       time.Time
	ExpiresAt      time.Time
}

func (q *Queries) CreatePeerSignalingGrant(ctx context.Context, arg CreatePeerSignalingGrantParams) (PeerSignalingGrant, error) {
	row := q.db.QueryRow(ctx, createPeerSignalingGrant,
		arg.IntentID,
		arg.Role,
		arg.EndpointID,
		arg.PeerEndpointID,
		arg.Jti,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i PeerSignalingGrant
	err := row.Scan(
		&i.IntentID,
		&i.Role,
		&i.EndpointID,
		&i.PeerEndpointID,
		&i.Jti,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const ensurePeerRelaySelectionState = `-- name: EnsurePeerRelaySelectionState :exec
INSERT INTO peer_relay_selection_states
  (user_id, machine_id, network_generation, host_worker_generation, updated_at)
VALUES
  ($1, $2, $3,
   $4, $5)
ON CONFLICT DO NOTHING
`

type EnsurePeerRelaySelectionStateParams struct {
	UserID               string
	MachineID            string
	NetworkGeneration    int64
	HostWorkerGeneration int64
	UpdatedAt            time.Time
}

func (q *Queries) EnsurePeerRelaySelectionState(ctx context.Context, arg EnsurePeerRelaySelectionStateParams) error {
	_, err := q.db.Exec(ctx, ensurePeerRelaySelectionState,
		arg.UserID,
		arg.MachineID,
		arg.NetworkGeneration,
		arg.HostWorkerGeneration,
		arg.UpdatedAt,
	)
	return err
}

const expirePeerSessionIntents = `-- name: ExpirePeerSessionIntents :many
WITH expired AS (
  UPDATE peer_session_intents
  SET state = 'expired', revoked_at = $1::timestamptz, revocation_reason = 'expired'
  WHERE state = 'active' AND expires_at <= $1::timestamptz
  RETURNING id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose, edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint, attempt_generation, network_generation, state, expires_at, revoked_at, revocation_reason, created_at, ice_credentials_ciphertext, edge_pool, signaling_host, stun_host, stun_port, controlled_delivered_at
), grants AS (
  UPDATE peer_signaling_grants g
  SET revoked_at = $1::timestamptz
  FROM expired
  WHERE g.intent_id = expired.id AND g.revoked_at IS NULL
), relays AS (
  UPDATE peer_relay_allocations relay
  SET revoked_at = $1::timestamptz
  FROM expired
  WHERE relay.intent_id = expired.id AND relay.revoked_at IS NULL
)
SELECT id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose, edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint, attempt_generation, network_generation, state, expires_at, revoked_at, revocation_reason, created_at, ice_credentials_ciphertext, edge_pool, signaling_host, stun_host, stun_port, controlled_delivered_at FROM expired ORDER BY id
`

type ExpirePeerSessionIntentsRow struct {
	ID                                string
	OperationKey                      string
	RequestHash                       []byte
	UserID                            string
	CLIClientSessionID                string
	EnvironmentID                     string
	Purpose                           string
	EdgeNodeID                        string
	ControllingCertificateFingerprint []byte
	ControlledCertificateFingerprint  []byte
	AttemptGeneration                 int64
	NetworkGeneration                 int64
	State                             string
	ExpiresAt                         time.Time
	RevokedAt                         sql.NullTime
	RevocationReason                  sql.NullString
	CreatedAt                         time.Time
	IceCredentialsCiphertext          []byte
	EdgePool                          sql.NullString
	SignalingHost                     sql.NullString
	StunHost                          sql.NullString
	StunPort                          sql.NullInt32
	ControlledDeliveredAt             sql.NullTime
}

func (q *Queries) ExpirePeerSessionIntents(ctx context.Context, now time.Time) ([]ExpirePeerSessionIntentsRow, error) {
	rows, err := q.db.Query(ctx, expirePeerSessionIntents, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpirePeerSessionIntentsRow
	for rows.Next() {
		var i ExpirePeerSessionIntentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationKey,
			&i.RequestHash,
			&i.UserID,
			&i.CLIClientSessionID,
			&i.EnvironmentID,
			&i.Purpose,
			&i.EdgeNodeID,
			&i.ControllingCertificateFingerprint,
			&i.ControlledCertificateFingerprint,
			&i.AttemptGeneration,
			&i.NetworkGeneration,
			&i.State,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.CreatedAt,
			&i.IceCredentialsCiphertext,
			&i.EdgePool,
			&i.SignalingHost,
			&i.StunHost,
			&i.StunPort,
			&i.ControlledDeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeerRelayAllocationForIntent = `-- name: GetPeerRelayAllocationForIntent :one
SELECT intent_id, route_allocation, jti, route_generation, byte_limit, issued_at, expires_at, revoked_at FROM peer_relay_allocations
WHERE intent_id = $1
`

func (q *Queries) GetPeerRelayAllocationForIntent(ctx context.Context, intentID string) (PeerRelayAllocation, error) {
	row := q.db.QueryRow(ctx, getPeerRelayAllocationForIntent, intentID)
	var i PeerRelayAllocation
	err := row.Scan(
		&i.IntentID,
		&i.RouteAllocation,
		&i.Jti,
		&i.RouteGeneration,
		&i.ByteLimit,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPeerRelaySelectionStateForUpdate = `-- name: GetPeerRelaySelectionStateForUpdate :one
SELECT user_id, machine_id, network_generation, host_worker_generation, current_region, client_generation, client_observed_at, candidate_region, candidate_first_observed_at, candidate_last_observed_at, candidate_samples, updated_at FROM peer_relay_selection_states
WHERE user_id = $1 AND machine_id = $2
  AND network_generation = $3
  AND host_worker_generation = $4
FOR UPDATE
`

type GetPeerRelaySelectionStateForUpdateParams struct {
	UserID               string
	MachineID            string
	NetworkGeneration    int64
	HostWorkerGeneration int64
}

func (q *Queries) GetPeerRelaySelectionStateForUpdate(ctx context.Context, arg GetPeerRelaySelectionStateForUpdateParams) (PeerRelaySelectionState, error) {
	row := q.db.QueryRow(ctx, getPeerRelaySelectionStateForUpdate,
		arg.UserID,
		arg.MachineID,
		arg.NetworkGeneration,
		arg.HostWorkerGeneration,
	)
	var i PeerRelaySelectionState
	err := row.Scan(
		&i.UserID,
		&i.MachineID,
		&i.NetworkGeneration,
		&i.HostWorkerGeneration,
		&i.CurrentRegion,
		&i.ClientGeneration,
		&i.ClientObservedAt,
		&i.CandidateRegion,
		&i.CandidateFirstObservedAt,
		&i.CandidateLastObservedAt,
		&i.CandidateSamples,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeerSessionIntentByOperationForUpdate = `-- name: GetPeerSessionIntentByOperationForUpdate :one
SELECT id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose, edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint, attempt_generation, network_generation, state, expires_at, revoked_at, revocation_reason, created_at, ice_credentials_ciphertext, edge_pool, signaling_host, stun_host, stun_port, controlled_delivered_at FROM peer_session_intents
WHERE operation_key = $1
FOR UPDATE
`

func (q *Queries) GetPeerSessionIntentByOperationForUpdate(ctx context.Context, operationKey string) (PeerSessionIntent, error) {
	row := q.db.QueryRow(ctx, getPeerSessionIntentByOperationForUpdate, operationKey)
	var i PeerSessionIntent
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.EnvironmentID,
		&i.Purpose,
		&i.EdgeNodeID,
		&i.ControllingCertificateFingerprint,
		&i.ControlledCertificateFingerprint,
		&i.AttemptGeneration,
		&i.NetworkGeneration,
		&i.State,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.IceCredentialsCiphertext,
		&i.EdgePool,
		&i.SignalingHost,
		&i.StunHost,
		&i.StunPort,
		&i.ControlledDeliveredAt,
	)
	return i, err
}

const getPeerSessionRevocationOperation = `-- name: GetPeerSessionRevocationOperation :one
SELECT operation_key, intent_id, actor_user_id, reason, created_at FROM peer_session_revocation_operations
WHERE operation_key = $1
`

func (q *Queries) GetPeerSessionRevocationOperation(ctx context.Context, operationKey string) (PeerSessionRevocationOperation, error) {
	row := q.db.QueryRow(ctx, getPeerSessionRevocationOperation, operationKey)
	var i PeerSessionRevocationOperation
	err := row.Scan(
		&i.OperationKey,
		&i.IntentID,
		&i.ActorUserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const isPeerRelayNodeReady = `-- name: IsPeerRelayNodeReady :one
SELECT EXISTS (
  SELECT 1 FROM control_tunnel_nodes
  WHERE id = $1 AND state = 'ready' AND ready = true
    AND last_heartbeat_at > $2::timestamptz
)
`

type IsPeerRelayNodeReadyParams struct {
	ID             string
	NodeStaleAfter time.Time
}

func (q *Queries) IsPeerRelayNodeReady(ctx context.Context, arg IsPeerRelayNodeReadyParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPeerRelayNodeReady, arg.ID, arg.NodeStaleAfter)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActivePeerSignalingJTIs = `-- name: ListActivePeerSignalingJTIs :many
SELECT g.jti
FROM peer_signaling_grants g
JOIN peer_session_intents intent ON intent.id = g.intent_id
JOIN cli_client_sessions client ON client.id = intent.cli_client_session_id
JOIN peer_endpoint_certificates endpoint ON endpoint.fingerprint = CASE g.role
  WHEN 'controlling' THEN intent.controlling_certificate_fingerprint
  ELSE intent.controlled_certificate_fingerprint END
JOIN account_e2ee_roots root ON root.user_id = intent.user_id
WHERE intent.edge_node_id = $1
  AND intent.state = 'active' AND intent.expires_at > $2
  AND g.revoked_at IS NULL AND g.expires_at > $2
  AND client.state = 'active'
  AND endpoint.revoked_at IS NULL AND endpoint.expires_at > $2
  AND root.revoked_at IS NULL
ORDER BY g.jti
`

type ListActivePeerSignalingJTIsParams struct {
	EdgeNodeID string
	Now        time.Time
}

func (q *Queries) ListActivePeerSignalingJTIs(ctx context.Context, arg ListActivePeerSignalingJTIsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listActivePeerSignalingJTIs, arg.EdgeNodeID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jti string
		if err := rows.Scan(&jti); err != nil {
			return nil, err
		}
		items = append(items, jti)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeerSignalingGrantsForIntent = `-- name: ListPeerSignalingGrantsForIntent :many
SELECT intent_id, role, endpoint_id, peer_endpoint_id, jti, issued_at, expires_at, revoked_at FROM peer_signaling_grants
WHERE intent_id = $1
ORDER BY role
`

func (q *Queries) ListPeerSignalingGrantsForIntent(ctx context.Context, intentID string) ([]PeerSignalingGrant, error) {
	rows, err := q.db.Query(ctx, listPeerSignalingGrantsForIntent, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerSignalingGrant
	for rows.Next() {
		var i PeerSignalingGrant
		if err := rows.Scan(
			&i.IntentID,
			&i.Role,
			&i.EndpointID,
			&i.PeerEndpointID,
			&i.Jti,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyPeerRelayNodes = `-- name: ListReadyPeerRelayNodes :many
SELECT DISTINCT ON (relay_region)
  id, relay_id, relay_region, relay_name, signaling_host, stun_host, stun_port
FROM control_tunnel_nodes
WHERE state = 'ready' AND ready = true
  AND last_heartbeat_at > $1::timestamptz
  AND relay_region IS NOT NULL AND trim(relay_region) <> ''
  AND signaling_host IS NOT NULL AND stun_host IS NOT NULL
  AND stun_port BETWEEN 1 AND 65535
  AND CASE WHEN jsonb_typeof(capacity->'connectors') = 'number'
      THEN (capacity->>'connectors')::bigint ELSE 0 END
    > CASE WHEN jsonb_typeof(observation->'active_streams') = 'number'
      THEN (observation->>'active_streams')::bigint ELSE 0 END
ORDER BY relay_region, last_heartbeat_at DESC, id
LIMIT 32
`

type ListReadyPeerRelayNodesRow struct {
	ID            string
	RelayID       sql.NullString
	RelayRegion   sql.NullString
	RelayName     sql.NullString
	SignalingHost sql.NullString
	StunHost      sql.NullString
	StunPort      sql.NullInt32
}

func (q *Queries) ListReadyPeerRelayNodes(ctx context.Context, nodeStaleAfter time.Time) ([]ListReadyPeerRelayNodesRow, error) {
	rows, err := q.db.Query(ctx, listReadyPeerRelayNodes, nodeStaleAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyPeerRelayNodesRow
	for rows.Next() {
		var i ListReadyPeerRelayNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.RelayID,
			&i.RelayRegion,
			&i.RelayName,
			&i.SignalingHost,
			&i.StunHost,
			&i.StunPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markControlledPeerSessionDelivered = `-- name: MarkControlledPeerSessionDelivered :execrows
UPDATE peer_session_intents
SET controlled_delivered_at = coalesce(controlled_delivered_at, $1::timestamptz)
WHERE id = $2 AND state = 'active'
`

type MarkControlledPeerSessionDeliveredParams struct {
	DeliveredAt time.Time
	ID          string
}

func (q *Queries) MarkControlledPeerSessionDelivered(ctx context.Context, arg MarkControlledPeerSessionDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markControlledPeerSessionDelivered, arg.DeliveredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const prunePeerRelaySelectionStates = `-- name: PrunePeerRelaySelectionStates :execrows
WITH ranked AS (
  SELECT state.user_id, state.machine_id, state.network_generation, state.host_worker_generation,
         row_number() OVER (ORDER BY updated_at DESC, network_generation DESC, host_worker_generation DESC) AS position
  FROM peer_relay_selection_states state
  WHERE state.user_id = $1 AND state.machine_id = $2
), removed AS (
  DELETE FROM peer_relay_selection_states state
  USING ranked
  WHERE state.user_id = ranked.user_id AND state.machine_id = ranked.machine_id
    AND state.network_generation = ranked.network_generation
    AND state.host_worker_generation = ranked.host_worker_generation
    AND (state.updated_at < $3 OR ranked.position > 64)
  RETURNING 1
)
SELECT count(*) FROM removed
`

type PrunePeerRelaySelectionStatesParams struct {
	UserID      string
	MachineID   string
	StaleBefore time.Time
}

func (q *Queries) PrunePeerRelaySelectionStates(ctx context.Context, arg PrunePeerRelaySelectionStatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, prunePeerRelaySelectionStates, arg.UserID, arg.MachineID, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reservePeerSessionRevocation = `-- name: ReservePeerSessionRevocation :one
INSERT INTO peer_session_revocation_operations
  (operation_key, intent_id, actor_user_id, reason, created_at)
VALUES
  ($1, $2, nullif($3, ''),
   $4, $5)
ON CONFLICT DO NOTHING
RETURNING operation_key, intent_id, actor_user_id, reason, created_at
`

type ReservePeerSessionRevocationParams struct {
	OperationKey string
	IntentID     string
	ActorUserID  interface{}
	Reason       string
	CreatedAt    time.Time
}

func (q *Queries) ReservePeerSessionRevocation(ctx context.Context, arg ReservePeerSessionRevocationParams) (PeerSessionRevocationOperation, error) {
	row := q.db.QueryRow(ctx, reservePeerSessionRevocation,
		arg.OperationKey,
		arg.IntentID,
		arg.ActorUserID,
		arg.Reason,
		arg.CreatedAt,
	)
	var i PeerSessionRevocationOperation
	err := row.Scan(
		&i.OperationKey,
		&i.IntentID,
		&i.ActorUserID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const resolveControlledPeerSessionForMachine = `-- name: ResolveControlledPeerSessionForMachine :one
SELECT intent.id, intent.operation_key, intent.request_hash, intent.user_id, intent.cli_client_session_id, intent.environment_id, intent.purpose, intent.edge_node_id, intent.controlling_certificate_fingerprint, intent.controlled_certificate_fingerprint, intent.attempt_generation, intent.network_generation, intent.state, intent.expires_at, intent.revoked_at, intent.revocation_reason, intent.created_at, intent.ice_credentials_ciphertext, intent.edge_pool, intent.signaling_host, intent.stun_host, intent.stun_port, intent.controlled_delivered_at,
       controlling.certificate AS controlling_certificate,
       controlled.certificate AS controlled_certificate,
       controlling_grant.endpoint_id AS controlling_endpoint_id,
       controlling_grant.peer_endpoint_id AS controlling_peer_endpoint_id,
       controlling_grant.jti AS controlling_jti,
       controlled_grant.endpoint_id AS controlled_endpoint_id,
       controlled_grant.peer_endpoint_id AS controlled_peer_endpoint_id,
       controlled_grant.jti AS controlled_jti,
       relay.route_allocation, relay.jti AS relay_jti,
       relay.route_generation, relay.byte_limit,
       connector.generation AS authorization_generation,
       machine.installation_generation AS host_generation
FROM peer_session_intents intent
JOIN peer_endpoint_certificates controlling
  ON controlling.fingerprint = intent.controlling_certificate_fingerprint
JOIN peer_endpoint_certificates controlled
  ON controlled.fingerprint = intent.controlled_certificate_fingerprint
JOIN peer_signaling_grants controlling_grant
  ON controlling_grant.intent_id = intent.id AND controlling_grant.role = 'controlling'
JOIN peer_signaling_grants controlled_grant
  ON controlled_grant.intent_id = intent.id AND controlled_grant.role = 'controlled'
JOIN peer_relay_allocations relay ON relay.intent_id = intent.id
JOIN user_machines machine
  ON machine.id = controlled.endpoint_id AND machine.user_id = intent.user_id
JOIN control_connector_generations connector
  ON connector.environment_id = intent.environment_id AND connector.machine_id = machine.id
  AND connector.connector_id = 'runtime'
JOIN control_tunnel_nodes node ON node.id = intent.edge_node_id
JOIN account_e2ee_roots root ON root.user_id = intent.user_id
JOIN cli_client_sessions client ON client.id = intent.cli_client_session_id
WHERE intent.user_id = $1 AND machine.id = $2
  AND machine.installation_generation = $3
  AND controlled.generation = $3
  AND intent.controlled_delivered_at IS NULL
  AND intent.state = 'active' AND intent.expires_at > $4
  AND controlling.revoked_at IS NULL AND controlling.expires_at > $4
  AND controlled.revoked_at IS NULL AND controlled.expires_at > $4
  AND controlling_grant.revoked_at IS NULL AND controlling_grant.expires_at > $4
  AND controlled_grant.revoked_at IS NULL AND controlled_grant.expires_at > $4
  AND relay.revoked_at IS NULL AND relay.expires_at > $4
  AND connector.revoked_at IS NULL AND connector.state = 'admitted'
  AND machine.revoked_at IS NULL AND machine.deleted_at IS NULL
  AND root.revoked_at IS NULL AND client.state = 'active'
  AND node.state = 'ready' AND node.ready = true
  AND node.last_heartbeat_at > $5::timestamptz
ORDER BY intent.created_at, intent.id
LIMIT 1
FOR UPDATE OF intent SKIP LOCKED
`

type ResolveControlledPeerSessionForMachineParams struct {
	UserID         string
	MachineID      string
	HostGeneration int64
	Now            time.Time
	NodeStaleAfter time.Time
}

type ResolveControlledPeerSessionForMachineRow struct {
	ID                                string
	OperationKey                      string
	RequestHash                       []byte
	UserID                            string
	CLIClientSessionID                string
	EnvironmentID                     string
	Purpose                           string
	EdgeNodeID                        string
	ControllingCertificateFingerprint []byte
	ControlledCertificateFingerprint  []byte
	AttemptGeneration                 int64
	NetworkGeneration                 int64
	State                             string
	ExpiresAt                         time.Time
	RevokedAt                         sql.NullTime
	RevocationReason                  sql.NullString
	CreatedAt                         time.Time
	IceCredentialsCiphertext          []byte
	EdgePool                          sql.NullString
	SignalingHost                     sql.NullString
	StunHost                          sql.NullString
	StunPort                          sql.NullInt32
	ControlledDeliveredAt             sql.NullTime
	ControllingCertificate            []byte
	ControlledCertificate             []byte
	ControllingEndpointID             string
	ControllingPeerEndpointID         string
	ControllingJti                    string
	ControlledEndpointID              string
	ControlledPeerEndpointID          string
	ControlledJti                     string
	RouteAllocation                   []byte
	RelayJti                          string
	RouteGeneration                   int64
	ByteLimit                         int64
	AuthorizationGeneration           int64
	HostGeneration                    int64
}

func (q *Queries) ResolveControlledPeerSessionForMachine(ctx context.Context, arg ResolveControlledPeerSessionForMachineParams) (ResolveControlledPeerSessionForMachineRow, error) {
	row := q.db.QueryRow(ctx, resolveControlledPeerSessionForMachine,
		arg.UserID,
		arg.MachineID,
		arg.HostGeneration,
		arg.Now,
		arg.NodeStaleAfter,
	)
	var i ResolveControlledPeerSessionForMachineRow
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.EnvironmentID,
		&i.Purpose,
		&i.EdgeNodeID,
		&i.ControllingCertificateFingerprint,
		&i.ControlledCertificateFingerprint,
		&i.AttemptGeneration,
		&i.NetworkGeneration,
		&i.State,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.IceCredentialsCiphertext,
		&i.EdgePool,
		&i.SignalingHost,
		&i.StunHost,
		&i.StunPort,
		&i.ControlledDeliveredAt,
		&i.ControllingCertificate,
		&i.ControlledCertificate,
		&i.ControllingEndpointID,
		&i.ControllingPeerEndpointID,
		&i.ControllingJti,
		&i.ControlledEndpointID,
		&i.ControlledPeerEndpointID,
		&i.ControlledJti,
		&i.RouteAllocation,
		&i.RelayJti,
		&i.RouteGeneration,
		&i.ByteLimit,
		&i.AuthorizationGeneration,
		&i.HostGeneration,
	)
	return i, err
}

const resolvePeerSessionAuthorityForUpdate = `-- name: ResolvePeerSessionAuthorityForUpdate :one
SELECT controlling.endpoint_id AS controlling_endpoint_id,
       controlled.endpoint_id AS controlled_endpoint_id,
       controlling.certificate AS controlling_certificate,
       controlled.certificate AS controlled_certificate,
       node.id AS edge_node_id,
       node.relay_region,
       node.signaling_host,
       node.stun_host,
       node.stun_port,
       connector.generation AS authorization_generation,
       machine.installation_generation AS host_generation,
       machine.relay_latency_worker_generation,
       machine.relay_latency_generation,
       machine.relay_latency_observed_at,
       machine.relay_latency_vector
FROM cli_client_sessions client
JOIN account_e2ee_roots root ON root.user_id = client.user_id
JOIN peer_endpoint_certificates controlling
  ON controlling.fingerprint = $1
  AND controlling.user_id = client.user_id AND controlling.role = 'cli'
  AND controlling.endpoint_id = client.id
JOIN peer_endpoint_certificates controlled
  ON controlled.fingerprint = $2
  AND controlled.user_id = client.user_id AND controlled.role = 'machine'
JOIN control_environments environment
  ON environment.id = $3 AND environment.owner_user_id = client.user_id
JOIN user_machines machine
  ON machine.id = controlled.endpoint_id AND machine.environment_id = environment.id
JOIN control_connector_generations connector
  ON connector.environment_id = environment.id AND connector.machine_id = machine.id
  AND connector.connector_id = 'runtime' AND connector.state = 'admitted' AND connector.revoked_at IS NULL
JOIN control_tunnel_nodes node ON node.id = connector.edge_node_id
WHERE client.id = $4
  AND client.user_id = $5 AND client.state = 'active'
  AND root.revoked_at IS NULL
  AND controlling.revoked_at IS NULL AND controlling.issued_at <= $6
  AND controlling.expires_at > $6
  AND controlled.revoked_at IS NULL AND controlled.issued_at <= $6
  AND controlled.expires_at > $6
  AND environment.desired_state = 'active' AND environment.revoked_at IS NULL
  AND machine.revoked_at IS NULL AND machine.deleted_at IS NULL
  AND node.state = 'ready' AND node.ready = true
  AND node.relay_region IS NOT NULL AND trim(node.relay_region) <> ''
  AND node.signaling_host IS NOT NULL AND node.stun_host IS NOT NULL AND node.stun_port IS NOT NULL
  AND node.last_heartbeat_at > $7::timestamptz
FOR UPDATE OF client, root, controlling, controlled, environment, node
`

type ResolvePeerSessionAuthorityForUpdateParams struct {
	ControllingCertificateFingerprint []byte
	ControlledCertificateFingerprint  []byte
	EnvironmentID                     string
	CLIClientSessionID                string
	UserID                            string
	Now                               time.Time
	NodeStaleAfter                    time.Time
}

type ResolvePeerSessionAuthorityForUpdateRow struct {
	ControllingEndpointID        string
	ControlledEndpointID         string
	ControllingCertificate       []byte
	ControlledCertificate        []byte
	EdgeNodeID                   string
	RelayRegion                  sql.NullString
	SignalingHost                sql.NullString
	StunHost                     sql.NullString
	StunPort                     sql.NullInt32
	AuthorizationGeneration      int64
	HostGeneration               int64
	RelayLatencyWorkerGeneration int64
	RelayLatencyGeneration       int64
	RelayLatencyObservedAt       sql.NullTime
	RelayLatencyVector           []byte
}

func (q *Queries) ResolvePeerSessionAuthorityForUpdate(ctx context.Context, arg ResolvePeerSessionAuthorityForUpdateParams) (ResolvePeerSessionAuthorityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, resolvePeerSessionAuthorityForUpdate,
		arg.ControllingCertificateFingerprint,
		arg.ControlledCertificateFingerprint,
		arg.EnvironmentID,
		arg.CLIClientSessionID,
		arg.UserID,
		arg.Now,
		arg.NodeStaleAfter,
	)
	var i ResolvePeerSessionAuthorityForUpdateRow
	err := row.Scan(
		&i.ControllingEndpointID,
		&i.ControlledEndpointID,
		&i.ControllingCertificate,
		&i.ControlledCertificate,
		&i.EdgeNodeID,
		&i.RelayRegion,
		&i.SignalingHost,
		&i.StunHost,
		&i.StunPort,
		&i.AuthorizationGeneration,
		&i.HostGeneration,
		&i.RelayLatencyWorkerGeneration,
		&i.RelayLatencyGeneration,
		&i.RelayLatencyObservedAt,
		&i.RelayLatencyVector,
	)
	return i, err
}

const revokePeerSessionIntent = `-- name: RevokePeerSessionIntent :one
WITH revoked AS (
  UPDATE peer_session_intents
  SET state = CASE WHEN $1::text = 'expired' THEN 'expired' ELSE 'revoked' END,
      revoked_at = $2::timestamptz, revocation_reason = $1::text
  WHERE id = $3 AND state = 'active'
    AND attempt_generation = $4
    AND ($5::text = '' OR user_id = $5::text)
  RETURNING id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose, edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint, attempt_generation, network_generation, state, expires_at, revoked_at, revocation_reason, created_at, ice_credentials_ciphertext, edge_pool, signaling_host, stun_host, stun_port, controlled_delivered_at
), grants AS (
  UPDATE peer_signaling_grants
  SET revoked_at = $2::timestamptz
  WHERE intent_id = $3 AND revoked_at IS NULL
), relay AS (
  UPDATE peer_relay_allocations
  SET revoked_at = $2::timestamptz
  WHERE intent_id = $3 AND revoked_at IS NULL
)
SELECT id, operation_key, request_hash, user_id, cli_client_session_id, environment_id, purpose, edge_node_id, controlling_certificate_fingerprint, controlled_certificate_fingerprint, attempt_generation, network_generation, state, expires_at, revoked_at, revocation_reason, created_at, ice_credentials_ciphertext, edge_pool, signaling_host, stun_host, stun_port, controlled_delivered_at FROM revoked
`

type RevokePeerSessionIntentParams struct {
	Reason            string
	Now               time.Time
	ID                string
	AttemptGeneration int64
	ActorUserID       string
}

type RevokePeerSessionIntentRow struct {
	ID                                string
	OperationKey                      string
	RequestHash                       []byte
	UserID                            string
	CLIClientSessionID                string
	EnvironmentID                     string
	Purpose                           string
	EdgeNodeID                        string
	ControllingCertificateFingerprint []byte
	ControlledCertificateFingerprint  []byte
	AttemptGeneration                 int64
	NetworkGeneration                 int64
	State                             string
	ExpiresAt                         time.Time
	RevokedAt                         sql.NullTime
	RevocationReason                  sql.NullString
	CreatedAt                         time.Time
	IceCredentialsCiphertext          []byte
	EdgePool                          sql.NullString
	SignalingHost                     sql.NullString
	StunHost                          sql.NullString
	StunPort                          sql.NullInt32
	ControlledDeliveredAt             sql.NullTime
}

func (q *Queries) RevokePeerSessionIntent(ctx context.Context, arg RevokePeerSessionIntentParams) (RevokePeerSessionIntentRow, error) {
	row := q.db.QueryRow(ctx, revokePeerSessionIntent,
		arg.Reason,
		arg.Now,
		arg.ID,
		arg.AttemptGeneration,
		arg.ActorUserID,
	)
	var i RevokePeerSessionIntentRow
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.CLIClientSessionID,
		&i.EnvironmentID,
		&i.Purpose,
		&i.EdgeNodeID,
		&i.ControllingCertificateFingerprint,
		&i.ControlledCertificateFingerprint,
		&i.AttemptGeneration,
		&i.NetworkGeneration,
		&i.State,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.CreatedAt,
		&i.IceCredentialsCiphertext,
		&i.EdgePool,
		&i.SignalingHost,
		&i.StunHost,
		&i.StunPort,
		&i.ControlledDeliveredAt,
	)
	return i, err
}

const updatePeerRelaySelectionState = `-- name: UpdatePeerRelaySelectionState :execrows
UPDATE peer_relay_selection_states
SET current_region = $1,
    client_generation = $2,
    client_observed_at = $3,
    candidate_region = $4,
    candidate_first_observed_at = $5,
    candidate_last_observed_at = $6,
    candidate_samples = $7,
    updated_at = $8
WHERE user_id = $9 AND machine_id = $10
  AND network_generation = $11
  AND host_worker_generation = $12
`

type UpdatePeerRelaySelectionStateParams struct {
	CurrentRegion            sql.NullString
	ClientGeneration         int64
	ClientObservedAt         sql.NullTime
	CandidateRegion          sql.NullString
	CandidateFirstObservedAt sql.NullTime
	CandidateLastObservedAt  sql.NullTime
	CandidateSamples         int32
	UpdatedAt                time.Time
	UserID                   string
	MachineID                string
	NetworkGeneration        int64
	HostWorkerGeneration     int64
}

func (q *Queries) UpdatePeerRelaySelectionState(ctx context.Context, arg UpdatePeerRelaySelectionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePeerRelaySelectionState,
		arg.CurrentRegion,
		arg.ClientGeneration,
		arg.ClientObservedAt,
		arg.CandidateRegion,
		arg.CandidateFirstObservedAt,
		arg.CandidateLastObservedAt,
		arg.CandidateSamples,
		arg.UpdatedAt,
		arg.UserID,
		arg.MachineID,
		arg.NetworkGeneration,
		arg.HostWorkerGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
