// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peer_identity.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const createAccountE2EERoot = `-- name: CreateAccountE2EERoot :one
INSERT INTO account_e2ee_roots (user_id, public_key, fingerprint)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING user_id, public_key, fingerprint, generation, created_at, updated_at, revoked_at
`

type CreateAccountE2EERootParams struct {
	UserID      string
	PublicKey   []byte
	Fingerprint []byte
}

func (q *Queries) CreateAccountE2EERoot(ctx context.Context, arg CreateAccountE2EERootParams) (AccountE2eeRoot, error) {
	row := q.db.QueryRow(ctx, createAccountE2EERoot, arg.UserID, arg.PublicKey, arg.Fingerprint)
	var i AccountE2eeRoot
	err := row.Scan(
		&i.UserID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createCLIPeerEndpointEnrollmentRequest = `-- name: CreateCLIPeerEndpointEnrollmentRequest :one
INSERT INTO peer_endpoint_enrollment_requests
  (id, operation_key, request_hash, user_id, endpoint_id, generation,
   noise_public_key, quic_public_key, role, created_at, expires_at)
VALUES
  ($1, $2, $3, $4,
   $5, $6, $7,
   $8, 'cli', $9, $10)
ON CONFLICT DO NOTHING
RETURNING id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at
`

type CreateCLIPeerEndpointEnrollmentRequestParams struct {
	ID             string
	OperationKey   string
	RequestHash    []byte
	UserID         string
	EndpointID     string
	Generation     int64
	NoisePublicKey []byte
	QuicPublicKey  []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

func (q *Queries) CreateCLIPeerEndpointEnrollmentRequest(ctx context.Context, arg CreateCLIPeerEndpointEnrollmentRequestParams) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, createCLIPeerEndpointEnrollmentRequest,
		arg.ID,
		arg.OperationKey,
		arg.RequestHash,
		arg.UserID,
		arg.EndpointID,
		arg.Generation,
		arg.NoisePublicKey,
		arg.QuicPublicKey,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const createPeerEndpointCertificate = `-- name: CreatePeerEndpointCertificate :one
INSERT INTO peer_endpoint_certificates
  (fingerprint, user_id, endpoint_id, role, generation, serial, certificate,
   noise_public_key, quic_public_key, issued_at, expires_at)
VALUES
  ($1, $2, $3, $4,
   $5, $6, $7,
   $8, $9, $10, $11)
ON CONFLICT DO NOTHING
RETURNING fingerprint, user_id, endpoint_id, role, generation, serial, certificate, noise_public_key, quic_public_key, issued_at, expires_at, created_at, revoked_at, revocation_reason
`

type CreatePeerEndpointCertificateParams struct {
	Fingerprint    []byte
	UserID         string
	EndpointID     string
	Role           string
	Generation     int64
	Serial         int64
	Certificate    []byte
	NoisePublicKey []byte
	QuicPublicKey  []byte
	IssuedAt       time.Time
	ExpiresAt      time.Time
}

func (q *Queries) CreatePeerEndpointCertificate(ctx context.Context, arg CreatePeerEndpointCertificateParams) (PeerEndpointCertificate, error) {
	row := q.db.QueryRow(ctx, createPeerEndpointCertificate,
		arg.Fingerprint,
		arg.UserID,
		arg.EndpointID,
		arg.Role,
		arg.Generation,
		arg.Serial,
		arg.Certificate,
		arg.NoisePublicKey,
		arg.QuicPublicKey,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i PeerEndpointCertificate
	err := row.Scan(
		&i.Fingerprint,
		&i.UserID,
		&i.EndpointID,
		&i.Role,
		&i.Generation,
		&i.Serial,
		&i.Certificate,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const createPeerEndpointCertificateOperation = `-- name: CreatePeerEndpointCertificateOperation :one
INSERT INTO peer_endpoint_certificate_operations
  (operation_id, user_id, request_hash, certificate_fingerprint, created_at)
VALUES
  ($1, $2, $3,
   $4, $5)
RETURNING operation_id, user_id, request_hash, certificate_fingerprint, created_at
`

type CreatePeerEndpointCertificateOperationParams struct {
	OperationID            string
	UserID                 string
	RequestHash            []byte
	CertificateFingerprint []byte
	CreatedAt              time.Time
}

func (q *Queries) CreatePeerEndpointCertificateOperation(ctx context.Context, arg CreatePeerEndpointCertificateOperationParams) (PeerEndpointCertificateOperation, error) {
	row := q.db.QueryRow(ctx, createPeerEndpointCertificateOperation,
		arg.OperationID,
		arg.UserID,
		arg.RequestHash,
		arg.CertificateFingerprint,
		arg.CreatedAt,
	)
	var i PeerEndpointCertificateOperation
	err := row.Scan(
		&i.OperationID,
		&i.UserID,
		&i.RequestHash,
		&i.CertificateFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const createPeerEndpointCertificateRevocation = `-- name: CreatePeerEndpointCertificateRevocation :one
INSERT INTO peer_endpoint_certificate_revocations
  (operation_id, user_id, certificate_fingerprint, serial, reason, created_at)
VALUES
  ($1, $2, $3,
   $4, $5, $6)
RETURNING operation_id, user_id, certificate_fingerprint, serial, reason, created_at
`

type CreatePeerEndpointCertificateRevocationParams struct {
	OperationID            string
	UserID                 string
	CertificateFingerprint []byte
	Serial                 int64
	Reason                 string
	CreatedAt              time.Time
}

func (q *Queries) CreatePeerEndpointCertificateRevocation(ctx context.Context, arg CreatePeerEndpointCertificateRevocationParams) (PeerEndpointCertificateRevocation, error) {
	row := q.db.QueryRow(ctx, createPeerEndpointCertificateRevocation,
		arg.OperationID,
		arg.UserID,
		arg.CertificateFingerprint,
		arg.Serial,
		arg.Reason,
		arg.CreatedAt,
	)
	var i PeerEndpointCertificateRevocation
	err := row.Scan(
		&i.OperationID,
		&i.UserID,
		&i.CertificateFingerprint,
		&i.Serial,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createPeerEndpointEnrollmentRequest = `-- name: CreatePeerEndpointEnrollmentRequest :one
INSERT INTO peer_endpoint_enrollment_requests
  (id, operation_key, request_hash, user_id, endpoint_id, generation,
   noise_public_key, quic_public_key, role, created_at, expires_at)
SELECT $1, $2, $3, machine.user_id,
       machine.id, $4, $5,
       $6, 'machine', $7, $8
FROM user_machines machine
WHERE machine.id = $9 AND machine.user_id = $10
  AND machine.installation_generation = $4
  AND machine.revoked_at IS NULL AND machine.deleted_at IS NULL
ON CONFLICT DO NOTHING
RETURNING id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at
`

type CreatePeerEndpointEnrollmentRequestParams struct {
	ID             string
	OperationKey   string
	RequestHash    []byte
	Generation     int64
	NoisePublicKey []byte
	QuicPublicKey  []byte
	CreatedAt      time.Time
	ExpiresAt      time.Time
	EndpointID     string
	UserID         string
}

func (q *Queries) CreatePeerEndpointEnrollmentRequest(ctx context.Context, arg CreatePeerEndpointEnrollmentRequestParams) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, createPeerEndpointEnrollmentRequest,
		arg.ID,
		arg.OperationKey,
		arg.RequestHash,
		arg.Generation,
		arg.NoisePublicKey,
		arg.QuicPublicKey,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.EndpointID,
		arg.UserID,
	)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const expirePeerEndpointEnrollmentRequests = `-- name: ExpirePeerEndpointEnrollmentRequests :execrows
UPDATE peer_endpoint_enrollment_requests
SET state = 'expired'
WHERE state = 'pending' AND expires_at <= $1
`

func (q *Queries) ExpirePeerEndpointEnrollmentRequests(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expirePeerEndpointEnrollmentRequests, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fulfillPeerEndpointEnrollmentRequest = `-- name: FulfillPeerEndpointEnrollmentRequest :one
UPDATE peer_endpoint_enrollment_requests
SET state = 'fulfilled', certificate_fingerprint = $1,
    fulfilled_at = $2
WHERE id = $3 AND state = 'pending'
RETURNING id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at
`

type FulfillPeerEndpointEnrollmentRequestParams struct {
	CertificateFingerprint []byte
	Now                    sql.NullTime
	ID                     string
}

func (q *Queries) FulfillPeerEndpointEnrollmentRequest(ctx context.Context, arg FulfillPeerEndpointEnrollmentRequestParams) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, fulfillPeerEndpointEnrollmentRequest, arg.CertificateFingerprint, arg.Now, arg.ID)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const getAccountE2EERootForUpdate = `-- name: GetAccountE2EERootForUpdate :one
SELECT user_id, public_key, fingerprint, generation, created_at, updated_at, revoked_at FROM account_e2ee_roots
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetAccountE2EERootForUpdate(ctx context.Context, userID string) (AccountE2eeRoot, error) {
	row := q.db.QueryRow(ctx, getAccountE2EERootForUpdate, userID)
	var i AccountE2eeRoot
	err := row.Scan(
		&i.UserID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAccountE2EERoot = `-- name: GetActiveAccountE2EERoot :one
SELECT user_id, public_key, fingerprint, generation, created_at, updated_at, revoked_at FROM account_e2ee_roots
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveAccountE2EERoot(ctx context.Context, userID string) (AccountE2eeRoot, error) {
	row := q.db.QueryRow(ctx, getActiveAccountE2EERoot, userID)
	var i AccountE2eeRoot
	err := row.Scan(
		&i.UserID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActivePeerEndpointCertificateForUpdate = `-- name: GetActivePeerEndpointCertificateForUpdate :one
SELECT certificate.fingerprint, certificate.user_id, certificate.endpoint_id, certificate.role, certificate.generation, certificate.serial, certificate.certificate, certificate.noise_public_key, certificate.quic_public_key, certificate.issued_at, certificate.expires_at, certificate.created_at, certificate.revoked_at, certificate.revocation_reason FROM peer_endpoint_certificates certificate
JOIN account_e2ee_roots root ON root.user_id = certificate.user_id
WHERE certificate.user_id = $1
  AND certificate.endpoint_id = $2
  AND certificate.generation = $3
  AND certificate.revoked_at IS NULL
  AND certificate.issued_at <= $4
  AND certificate.expires_at > $4
  AND root.revoked_at IS NULL
FOR UPDATE OF certificate, root
`

type GetActivePeerEndpointCertificateForUpdateParams struct {
	UserID     string
	EndpointID string
	Generation int64
	Now        time.Time
}

func (q *Queries) GetActivePeerEndpointCertificateForUpdate(ctx context.Context, arg GetActivePeerEndpointCertificateForUpdateParams) (PeerEndpointCertificate, error) {
	row := q.db.QueryRow(ctx, getActivePeerEndpointCertificateForUpdate,
		arg.UserID,
		arg.EndpointID,
		arg.Generation,
		arg.Now,
	)
	var i PeerEndpointCertificate
	err := row.Scan(
		&i.Fingerprint,
		&i.UserID,
		&i.EndpointID,
		&i.Role,
		&i.Generation,
		&i.Serial,
		&i.Certificate,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const getMatchingPeerEndpointEnrollmentRequestForUpdate = `-- name: GetMatchingPeerEndpointEnrollmentRequestForUpdate :one
SELECT id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at FROM peer_endpoint_enrollment_requests
WHERE user_id = $1 AND endpoint_id = $2
  AND generation = $3 AND state = 'pending'
  AND expires_at > $4
FOR UPDATE
`

type GetMatchingPeerEndpointEnrollmentRequestForUpdateParams struct {
	UserID     string
	EndpointID string
	Generation int64
	Now        time.Time
}

func (q *Queries) GetMatchingPeerEndpointEnrollmentRequestForUpdate(ctx context.Context, arg GetMatchingPeerEndpointEnrollmentRequestForUpdateParams) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, getMatchingPeerEndpointEnrollmentRequestForUpdate,
		arg.UserID,
		arg.EndpointID,
		arg.Generation,
		arg.Now,
	)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const getPeerEndpointCertificateByFingerprint = `-- name: GetPeerEndpointCertificateByFingerprint :one
SELECT fingerprint, user_id, endpoint_id, role, generation, serial, certificate, noise_public_key, quic_public_key, issued_at, expires_at, created_at, revoked_at, revocation_reason FROM peer_endpoint_certificates
WHERE fingerprint = $1
`

func (q *Queries) GetPeerEndpointCertificateByFingerprint(ctx context.Context, fingerprint []byte) (PeerEndpointCertificate, error) {
	row := q.db.QueryRow(ctx, getPeerEndpointCertificateByFingerprint, fingerprint)
	var i PeerEndpointCertificate
	err := row.Scan(
		&i.Fingerprint,
		&i.UserID,
		&i.EndpointID,
		&i.Role,
		&i.Generation,
		&i.Serial,
		&i.Certificate,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const getPeerEndpointCertificateByIdentity = `-- name: GetPeerEndpointCertificateByIdentity :one
SELECT fingerprint, user_id, endpoint_id, role, generation, serial, certificate, noise_public_key, quic_public_key, issued_at, expires_at, created_at, revoked_at, revocation_reason FROM peer_endpoint_certificates
WHERE user_id = $1 AND endpoint_id = $2
  AND generation = $3
`

type GetPeerEndpointCertificateByIdentityParams struct {
	UserID     string
	EndpointID string
	Generation int64
}

func (q *Queries) GetPeerEndpointCertificateByIdentity(ctx context.Context, arg GetPeerEndpointCertificateByIdentityParams) (PeerEndpointCertificate, error) {
	row := q.db.QueryRow(ctx, getPeerEndpointCertificateByIdentity, arg.UserID, arg.EndpointID, arg.Generation)
	var i PeerEndpointCertificate
	err := row.Scan(
		&i.Fingerprint,
		&i.UserID,
		&i.EndpointID,
		&i.Role,
		&i.Generation,
		&i.Serial,
		&i.Certificate,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const getPeerEndpointCertificateOperationForUpdate = `-- name: GetPeerEndpointCertificateOperationForUpdate :one
SELECT operation_id, user_id, request_hash, certificate_fingerprint, created_at FROM peer_endpoint_certificate_operations
WHERE operation_id = $1
FOR UPDATE
`

func (q *Queries) GetPeerEndpointCertificateOperationForUpdate(ctx context.Context, operationID string) (PeerEndpointCertificateOperation, error) {
	row := q.db.QueryRow(ctx, getPeerEndpointCertificateOperationForUpdate, operationID)
	var i PeerEndpointCertificateOperation
	err := row.Scan(
		&i.OperationID,
		&i.UserID,
		&i.RequestHash,
		&i.CertificateFingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const getPeerEndpointCertificateRevocationForUpdate = `-- name: GetPeerEndpointCertificateRevocationForUpdate :one
SELECT operation_id, user_id, certificate_fingerprint, serial, reason, created_at FROM peer_endpoint_certificate_revocations
WHERE operation_id = $1
FOR UPDATE
`

func (q *Queries) GetPeerEndpointCertificateRevocationForUpdate(ctx context.Context, operationID string) (PeerEndpointCertificateRevocation, error) {
	row := q.db.QueryRow(ctx, getPeerEndpointCertificateRevocationForUpdate, operationID)
	var i PeerEndpointCertificateRevocation
	err := row.Scan(
		&i.OperationID,
		&i.UserID,
		&i.CertificateFingerprint,
		&i.Serial,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getPeerEndpointEnrollmentRequestByOperation = `-- name: GetPeerEndpointEnrollmentRequestByOperation :one
SELECT id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at FROM peer_endpoint_enrollment_requests
WHERE operation_key = $1
`

func (q *Queries) GetPeerEndpointEnrollmentRequestByOperation(ctx context.Context, operationKey string) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, getPeerEndpointEnrollmentRequestByOperation, operationKey)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const listPendingPeerEndpointEnrollmentRequests = `-- name: ListPendingPeerEndpointEnrollmentRequests :many
SELECT id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at FROM peer_endpoint_enrollment_requests
WHERE user_id = $1 AND state = 'pending'
  AND expires_at > $2
ORDER BY created_at, id
LIMIT $3
`

type ListPendingPeerEndpointEnrollmentRequestsParams struct {
	UserID   string
	Now      time.Time
	RowLimit int32
}

func (q *Queries) ListPendingPeerEndpointEnrollmentRequests(ctx context.Context, arg ListPendingPeerEndpointEnrollmentRequestsParams) ([]PeerEndpointEnrollmentRequest, error) {
	rows, err := q.db.Query(ctx, listPendingPeerEndpointEnrollmentRequests, arg.UserID, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerEndpointEnrollmentRequest
	for rows.Next() {
		var i PeerEndpointEnrollmentRequest
		if err := rows.Scan(
			&i.ID,
			&i.OperationKey,
			&i.RequestHash,
			&i.UserID,
			&i.EndpointID,
			&i.Generation,
			&i.Role,
			&i.NoisePublicKey,
			&i.QuicPublicKey,
			&i.State,
			&i.CertificateFingerprint,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.FulfilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewExpiredCLIPeerEndpointEnrollmentRequest = `-- name: RenewExpiredCLIPeerEndpointEnrollmentRequest :one
UPDATE peer_endpoint_enrollment_requests request
SET state = 'pending', created_at = $1, expires_at = $2,
    fulfilled_at = NULL, certificate_fingerprint = NULL
WHERE request.operation_key = $3
  AND request.request_hash = $4
  AND request.user_id = $5
  AND request.endpoint_id = $6
  AND request.generation = $7
  AND request.role = 'cli' AND request.state = 'expired'
RETURNING id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at
`

type RenewExpiredCLIPeerEndpointEnrollmentRequestParams struct {
	CreatedAt    time.Time
	ExpiresAt    time.Time
	OperationKey string
	RequestHash  []byte
	UserID       string
	EndpointID   string
	Generation   int64
}

func (q *Queries) RenewExpiredCLIPeerEndpointEnrollmentRequest(ctx context.Context, arg RenewExpiredCLIPeerEndpointEnrollmentRequestParams) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, renewExpiredCLIPeerEndpointEnrollmentRequest,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.OperationKey,
		arg.RequestHash,
		arg.UserID,
		arg.EndpointID,
		arg.Generation,
	)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const renewExpiredPeerEndpointEnrollmentRequest = `-- name: RenewExpiredPeerEndpointEnrollmentRequest :one
UPDATE peer_endpoint_enrollment_requests request
SET state = 'pending', created_at = $1, expires_at = $2,
    fulfilled_at = NULL, certificate_fingerprint = NULL
WHERE request.operation_key = $3
  AND request.request_hash = $4
  AND request.user_id = $5
  AND request.endpoint_id = $6
  AND request.generation = $7
  AND request.state = 'expired'
  AND EXISTS (
    SELECT 1 FROM user_machines machine
    WHERE machine.id = request.endpoint_id AND machine.user_id = request.user_id
      AND machine.installation_generation = request.generation
      AND machine.revoked_at IS NULL AND machine.deleted_at IS NULL
  )
RETURNING id, operation_key, request_hash, user_id, endpoint_id, generation, role, noise_public_key, quic_public_key, state, certificate_fingerprint, created_at, expires_at, fulfilled_at
`

type RenewExpiredPeerEndpointEnrollmentRequestParams struct {
	CreatedAt    time.Time
	ExpiresAt    time.Time
	OperationKey string
	RequestHash  []byte
	UserID       string
	EndpointID   string
	Generation   int64
}

func (q *Queries) RenewExpiredPeerEndpointEnrollmentRequest(ctx context.Context, arg RenewExpiredPeerEndpointEnrollmentRequestParams) (PeerEndpointEnrollmentRequest, error) {
	row := q.db.QueryRow(ctx, renewExpiredPeerEndpointEnrollmentRequest,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.OperationKey,
		arg.RequestHash,
		arg.UserID,
		arg.EndpointID,
		arg.Generation,
	)
	var i PeerEndpointEnrollmentRequest
	err := row.Scan(
		&i.ID,
		&i.OperationKey,
		&i.RequestHash,
		&i.UserID,
		&i.EndpointID,
		&i.Generation,
		&i.Role,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.State,
		&i.CertificateFingerprint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FulfilledAt,
	)
	return i, err
}

const revokeAccountE2EERoot = `-- name: RevokeAccountE2EERoot :one
UPDATE account_e2ee_roots
SET revoked_at = $1, generation = generation + 1, updated_at = $1
WHERE user_id = $2 AND revoked_at IS NULL
RETURNING user_id, public_key, fingerprint, generation, created_at, updated_at, revoked_at
`

type RevokeAccountE2EERootParams struct {
	Now    sql.NullTime
	UserID string
}

func (q *Queries) RevokeAccountE2EERoot(ctx context.Context, arg RevokeAccountE2EERootParams) (AccountE2eeRoot, error) {
	row := q.db.QueryRow(ctx, revokeAccountE2EERoot, arg.Now, arg.UserID)
	var i AccountE2eeRoot
	err := row.Scan(
		&i.UserID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokePeerEndpointCertificate = `-- name: RevokePeerEndpointCertificate :one
UPDATE peer_endpoint_certificates
SET revoked_at = $1, revocation_reason = $2
WHERE fingerprint = $3 AND revoked_at IS NULL
RETURNING fingerprint, user_id, endpoint_id, role, generation, serial, certificate, noise_public_key, quic_public_key, issued_at, expires_at, created_at, revoked_at, revocation_reason
`

type RevokePeerEndpointCertificateParams struct {
	Now         sql.NullTime
	Reason      sql.NullString
	Fingerprint []byte
}

func (q *Queries) RevokePeerEndpointCertificate(ctx context.Context, arg RevokePeerEndpointCertificateParams) (PeerEndpointCertificate, error) {
	row := q.db.QueryRow(ctx, revokePeerEndpointCertificate, arg.Now, arg.Reason, arg.Fingerprint)
	var i PeerEndpointCertificate
	err := row.Scan(
		&i.Fingerprint,
		&i.UserID,
		&i.EndpointID,
		&i.Role,
		&i.Generation,
		&i.Serial,
		&i.Certificate,
		&i.NoisePublicKey,
		&i.QuicPublicKey,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
	)
	return i, err
}

const revokeSupersededPeerEndpointCertificates = `-- name: RevokeSupersededPeerEndpointCertificates :execrows
UPDATE peer_endpoint_certificates
SET revoked_at = $1, revocation_reason = 'certificate_superseded'
WHERE user_id = $2 AND endpoint_id = $3
  AND generation < $4 AND revoked_at IS NULL
`

type RevokeSupersededPeerEndpointCertificatesParams struct {
	Now        sql.NullTime
	UserID     string
	EndpointID string
	Generation int64
}

func (q *Queries) RevokeSupersededPeerEndpointCertificates(ctx context.Context, arg RevokeSupersededPeerEndpointCertificatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSupersededPeerEndpointCertificates,
		arg.Now,
		arg.UserID,
		arg.EndpointID,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
