// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preview_domains_v1.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"
)

const advancePreviewDomainCreateOperationsV1 = `-- name: AdvancePreviewDomainCreateOperationsV1 :execrows
UPDATE operations
SET state = 'running', phase = 'issuing_certificate', progress = GREATEST(progress, 60),
    outcome = 'changed', completed_at = NULL, updated_at = $1
WHERE account_id = $2
  AND resource_kind = 'domain_binding'
  AND resource_id = $3
  AND operation_type = 'preview.domain.create'
  AND state IN ('pending','running')
`

type AdvancePreviewDomainCreateOperationsV1Params struct {
	Now       time.Time
	AccountID string
	DomainID  sql.NullString
}

// Certificate issuance is a separate lifecycle worker. DNS proof may move a
// preview create operation into issuing, but it must not complete that
// operation until the certificate worker has an active, distributed cert.
func (q *Queries) AdvancePreviewDomainCreateOperationsV1(ctx context.Context, arg AdvancePreviewDomainCreateOperationsV1Params) (int64, error) {
	result, err := q.db.Exec(ctx, advancePreviewDomainCreateOperationsV1, arg.Now, arg.AccountID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advancePreviewDomainTargetGenerationV1 = `-- name: AdvancePreviewDomainTargetGenerationV1 :execrows
UPDATE preview_domains
SET preview_generation = $1,
    updated_at = $2
WHERE preview_id = $3
  AND account_id = $4
  AND preview_generation = $5
  AND deleted_at IS NULL
`

type AdvancePreviewDomainTargetGenerationV1Params struct {
	NewPreviewGeneration      int64
	Now                       time.Time
	PreviewID                 string
	AccountID                 string
	PreviousPreviewGeneration int64
}

func (q *Queries) AdvancePreviewDomainTargetGenerationV1(ctx context.Context, arg AdvancePreviewDomainTargetGenerationV1Params) (int64, error) {
	result, err := q.db.Exec(ctx, advancePreviewDomainTargetGenerationV1,
		arg.NewPreviewGeneration,
		arg.Now,
		arg.PreviewID,
		arg.AccountID,
		arg.PreviousPreviewGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advancePreviewDomainsWithLeaseGenerationV1 = `-- name: AdvancePreviewDomainsWithLeaseGenerationV1 :execrows
WITH live_lease AS (
  SELECT preview_leases.id, preview_leases.account_id, preview_leases.generation
  FROM preview_leases
  WHERE preview_leases.id = $3
    AND preview_leases.account_id = $4
    AND preview_leases.generation = $2
    AND preview_leases.terminal_state = 'active'
  FOR UPDATE
)
UPDATE preview_domains AS d
SET preview_generation = live_lease.generation + 1,
    updated_at = $1
FROM live_lease
WHERE d.preview_id = live_lease.id
  AND d.account_id = live_lease.account_id
  AND d.preview_generation = $2
  AND d.deleted_at IS NULL
`

type AdvancePreviewDomainsWithLeaseGenerationV1Params struct {
	Now                       time.Time
	PreviousPreviewGeneration int64
	PreviewID                 string
	AccountID                 string
}

func (q *Queries) AdvancePreviewDomainsWithLeaseGenerationV1(ctx context.Context, arg AdvancePreviewDomainsWithLeaseGenerationV1Params) (int64, error) {
	result, err := q.db.Exec(ctx, advancePreviewDomainsWithLeaseGenerationV1,
		arg.Now,
		arg.PreviousPreviewGeneration,
		arg.PreviewID,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const applyPreviewDomainCertificateObservationV1 = `-- name: ApplyPreviewDomainCertificateObservationV1 :one
UPDATE preview_domains
SET certificate_state = $1,
    certificate_reference = $2,
    certificate_expires_at = $3,
    certificate_renewal_attempted_at = $4,
    certificate_failure_code = $5,
    caa_state = $6,
    generation = generation + 1,
    updated_at = $4
WHERE id = $7
  AND account_id = $8
  AND preview_id = $9
  AND generation = $10
  AND ownership_state = 'verified'
  AND deleted_at IS NULL
RETURNING id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
`

type ApplyPreviewDomainCertificateObservationV1Params struct {
	CertificateState     string
	CertificateReference sql.NullString
	CertificateExpiresAt sql.NullTime
	Now                  sql.NullTime
	FailureCode          sql.NullString
	CaaState             string
	DomainID             string
	AccountID            string
	PreviewID            string
	ExpectedGeneration   int64
}

func (q *Queries) ApplyPreviewDomainCertificateObservationV1(ctx context.Context, arg ApplyPreviewDomainCertificateObservationV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, applyPreviewDomainCertificateObservationV1,
		arg.CertificateState,
		arg.CertificateReference,
		arg.CertificateExpiresAt,
		arg.Now,
		arg.FailureCode,
		arg.CaaState,
		arg.DomainID,
		arg.AccountID,
		arg.PreviewID,
		arg.ExpectedGeneration,
	)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const applyPreviewDomainDNSObservationV1 = `-- name: ApplyPreviewDomainDNSObservationV1 :one
UPDATE preview_domains
SET observed_records = $1::jsonb,
    ownership_state = $2,
    conflict_state = $3,
    dns_last_checked_at = $4,
    dns_next_check_at = $5,
    dns_ttl_seconds = $6,
    verification_attempts = CASE
      WHEN $7::boolean THEN 0
      ELSE verification_attempts + 1
    END,
    last_verified_at = CASE
      WHEN $7::boolean THEN $4
      ELSE last_verified_at
    END,
    certificate_state = CASE
      WHEN $7::boolean AND certificate_state = 'pending' THEN 'issuing'
      ELSE certificate_state
    END,
    generation = generation + 1,
    updated_at = $4
WHERE id = $8
  AND account_id = $9
  AND preview_id = $10
  AND generation = $11
  AND deleted_at IS NULL
RETURNING id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
`

type ApplyPreviewDomainDNSObservationV1Params struct {
	ObservedRecords     []byte
	OwnershipState      string
	ConflictState       string
	Now                 sql.NullTime
	NextCheckAt         time.Time
	TtlSeconds          sql.NullInt32
	ObservationVerified bool
	DomainID            string
	AccountID           string
	PreviewID           string
	ExpectedGeneration  int64
}

func (q *Queries) ApplyPreviewDomainDNSObservationV1(ctx context.Context, arg ApplyPreviewDomainDNSObservationV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, applyPreviewDomainDNSObservationV1,
		arg.ObservedRecords,
		arg.OwnershipState,
		arg.ConflictState,
		arg.Now,
		arg.NextCheckAt,
		arg.TtlSeconds,
		arg.ObservationVerified,
		arg.DomainID,
		arg.AccountID,
		arg.PreviewID,
		arg.ExpectedGeneration,
	)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const beginPreviewDomainVerificationV1 = `-- name: BeginPreviewDomainVerificationV1 :one
UPDATE preview_domains
SET ownership_state = 'pending',
    conflict_state = 'clear',
    verification_attempts = 0,
    dns_next_check_at = $1,
    generation = generation + 1,
    updated_at = $1
WHERE id = $2
  AND account_id = $3
  AND preview_id = $4
  AND generation = $5
  AND deleted_at IS NULL
  AND ownership_state IN ('pending','failed','verified')
RETURNING id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
`

type BeginPreviewDomainVerificationV1Params struct {
	Now                time.Time
	DomainID           string
	AccountID          string
	PreviewID          string
	ExpectedGeneration int64
}

func (q *Queries) BeginPreviewDomainVerificationV1(ctx context.Context, arg BeginPreviewDomainVerificationV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, beginPreviewDomainVerificationV1,
		arg.Now,
		arg.DomainID,
		arg.AccountID,
		arg.PreviewID,
		arg.ExpectedGeneration,
	)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const completePreviewDomainVerificationOperationsV1 = `-- name: CompletePreviewDomainVerificationOperationsV1 :execrows
UPDATE operations
SET state = 'succeeded', phase = 'ready', progress = 100,
    outcome = 'changed', completed_at = $1, updated_at = $1
WHERE account_id = $2
  AND resource_kind = 'domain_binding'
  AND resource_id = $3
  AND operation_type = 'preview.domain.verify'
  AND state IN ('pending','running')
`

type CompletePreviewDomainVerificationOperationsV1Params struct {
	Now       sql.NullTime
	AccountID string
	DomainID  sql.NullString
}

// DNS ownership is the only proof that may complete a verify operation. A
// wrong or unavailable record deliberately leaves the operation pending so
// the worker can retry without claiming readiness.
func (q *Queries) CompletePreviewDomainVerificationOperationsV1(ctx context.Context, arg CompletePreviewDomainVerificationOperationsV1Params) (int64, error) {
	result, err := q.db.Exec(ctx, completePreviewDomainVerificationOperationsV1, arg.Now, arg.AccountID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPreviewDomainV1 = `-- name: CreatePreviewDomainV1 :one
INSERT INTO preview_domains (
  id, account_id, preview_id, preview_generation, hostname, match_type,
  ownership_challenge_reference, ownership_state, dns_target,
  observed_records, dns_provider, expected_records, dns_next_check_at,
  certificate_strategy, certificate_state, caa_state, conflict_state,
  generation, created_at, updated_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  'pending', $8, '[]'::jsonb, $9,
  $10, $11, $12,
  CASE WHEN $12 = 'none' THEN 'not_applicable' ELSE 'pending' END,
  CASE WHEN $12 = 'none' THEN 'not_applicable' ELSE 'unknown' END,
  'clear', 1, $11, $11
)
RETURNING id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
`

type CreatePreviewDomainV1Params struct {
	ID                          string
	AccountID                   string
	PreviewID                   string
	PreviewGeneration           int64
	Hostname                    string
	MatchType                   string
	OwnershipChallengeReference string
	DnsTarget                   string
	DnsProvider                 string
	ExpectedRecords             []byte
	Now                         time.Time
	CertificateStrategy         string
}

func (q *Queries) CreatePreviewDomainV1(ctx context.Context, arg CreatePreviewDomainV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, createPreviewDomainV1,
		arg.ID,
		arg.AccountID,
		arg.PreviewID,
		arg.PreviewGeneration,
		arg.Hostname,
		arg.MatchType,
		arg.OwnershipChallengeReference,
		arg.DnsTarget,
		arg.DnsProvider,
		arg.ExpectedRecords,
		arg.Now,
		arg.CertificateStrategy,
	)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const deletePreviewDomainV1 = `-- name: DeletePreviewDomainV1 :one
UPDATE preview_domains
SET ownership_state = 'revoked',
    certificate_state = CASE WHEN certificate_state = 'not_applicable' THEN 'not_applicable' ELSE 'revoked' END,
    conflict_state = 'quarantined',
    quarantine_until = $1,
    deleted_at = $2,
    generation = generation + 1,
    updated_at = $2
WHERE id = $3
  AND account_id = $4
  AND preview_id = $5
  AND generation = $6
  AND deleted_at IS NULL
RETURNING id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
`

type DeletePreviewDomainV1Params struct {
	QuarantineUntil    sql.NullTime
	Now                sql.NullTime
	DomainID           string
	AccountID          string
	PreviewID          string
	ExpectedGeneration int64
}

func (q *Queries) DeletePreviewDomainV1(ctx context.Context, arg DeletePreviewDomainV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, deletePreviewDomainV1,
		arg.QuarantineUntil,
		arg.Now,
		arg.DomainID,
		arg.AccountID,
		arg.PreviewID,
		arg.ExpectedGeneration,
	)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const expirePreviewLeaseAndWithdrawDomainsV1 = `-- name: ExpirePreviewLeaseAndWithdrawDomainsV1 :many
WITH candidates AS (
  SELECT source.id
  FROM preview_leases AS source
  WHERE source.terminal_state = 'active'
    AND LEAST(source.lease_deadline, COALESCE(source.user_deadline, source.lease_deadline)) <= $1
  ORDER BY LEAST(source.lease_deadline, COALESCE(source.user_deadline, source.lease_deadline)), source.id
  LIMIT $2
  FOR UPDATE SKIP LOCKED
), expired AS (
  UPDATE preview_leases AS p
  SET allocation_state = 'released', edge_state = 'released', terminal_state = 'expired',
      generation = p.generation + 1, stopped_at = $1
  FROM candidates
  WHERE p.id = candidates.id
  RETURNING p.id, p.account_id, p.generation
), withdrawn AS (
  UPDATE preview_domains AS d
  SET ownership_state = 'expired',
      certificate_state = CASE WHEN d.certificate_state = 'not_applicable' THEN 'not_applicable' ELSE 'revoked' END,
      conflict_state = 'quarantined', quarantine_until = $3,
      deleted_at = $1, generation = d.generation + 1, updated_at = $1
  FROM expired
  WHERE d.preview_id = expired.id AND d.account_id = expired.account_id
    AND d.preview_generation < expired.generation AND d.deleted_at IS NULL
  RETURNING d.id
)
SELECT id, account_id, generation FROM expired
`

type ExpirePreviewLeaseAndWithdrawDomainsV1Params struct {
	Now             time.Time
	RowLimit        int32
	QuarantineUntil sql.NullTime
}

type ExpirePreviewLeaseAndWithdrawDomainsV1Row struct {
	ID         string
	AccountID  string
	Generation int64
}

func (q *Queries) ExpirePreviewLeaseAndWithdrawDomainsV1(ctx context.Context, arg ExpirePreviewLeaseAndWithdrawDomainsV1Params) ([]ExpirePreviewLeaseAndWithdrawDomainsV1Row, error) {
	rows, err := q.db.Query(ctx, expirePreviewLeaseAndWithdrawDomainsV1, arg.Now, arg.RowLimit, arg.QuarantineUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpirePreviewLeaseAndWithdrawDomainsV1Row
	for rows.Next() {
		var i ExpirePreviewLeaseAndWithdrawDomainsV1Row
		if err := rows.Scan(&i.ID, &i.AccountID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreviewDomainAnyV1 = `-- name: GetPreviewDomainAnyV1 :one
SELECT id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
FROM preview_domains
WHERE id = $1
  AND account_id = $2
  AND preview_id = $3
`

type GetPreviewDomainAnyV1Params struct {
	DomainID  string
	AccountID string
	PreviewID string
}

func (q *Queries) GetPreviewDomainAnyV1(ctx context.Context, arg GetPreviewDomainAnyV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, getPreviewDomainAnyV1, arg.DomainID, arg.AccountID, arg.PreviewID)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const getPreviewDomainForReconciliationV1 = `-- name: GetPreviewDomainForReconciliationV1 :one
SELECT d.id, d.account_id, d.preview_id, d.preview_generation, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.quarantine_until
FROM preview_domains AS d
JOIN preview_leases AS p
  ON p.id = d.preview_id AND p.account_id = d.account_id
WHERE d.id = $1
  AND d.deleted_at IS NULL
  AND p.terminal_state = 'active'
  AND p.generation = d.preview_generation
FOR UPDATE OF d
`

func (q *Queries) GetPreviewDomainForReconciliationV1(ctx context.Context, domainID string) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, getPreviewDomainForReconciliationV1, domainID)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const getPreviewDomainLeaseContextV1 = `-- name: GetPreviewDomainLeaseContextV1 :one
SELECT p.id, p.account_id, p.generation, p.lease_deadline, p.user_deadline,
       p.allocation_state, p.edge_state, p.origin_state, p.terminal_state,
       p.owner_device_id, p.owner_session_id
FROM preview_leases AS p
JOIN preview_domains AS d
  ON d.preview_id = p.id AND d.account_id = p.account_id
WHERE p.id = $1
  AND p.account_id = $2
  AND d.id = $3
FOR UPDATE OF p
`

type GetPreviewDomainLeaseContextV1Params struct {
	PreviewID string
	AccountID string
	DomainID  string
}

type GetPreviewDomainLeaseContextV1Row struct {
	ID              string
	AccountID       string
	Generation      int64
	LeaseDeadline   time.Time
	UserDeadline    sql.NullTime
	AllocationState string
	EdgeState       string
	OriginState     string
	TerminalState   string
	OwnerDeviceID   string
	OwnerSessionID  string
}

func (q *Queries) GetPreviewDomainLeaseContextV1(ctx context.Context, arg GetPreviewDomainLeaseContextV1Params) (GetPreviewDomainLeaseContextV1Row, error) {
	row := q.db.QueryRow(ctx, getPreviewDomainLeaseContextV1, arg.PreviewID, arg.AccountID, arg.DomainID)
	var i GetPreviewDomainLeaseContextV1Row
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Generation,
		&i.LeaseDeadline,
		&i.UserDeadline,
		&i.AllocationState,
		&i.EdgeState,
		&i.OriginState,
		&i.TerminalState,
		&i.OwnerDeviceID,
		&i.OwnerSessionID,
	)
	return i, err
}

const getPreviewDomainLeaseViewV1 = `-- name: GetPreviewDomainLeaseViewV1 :one
SELECT id, account_id, generation, lease_deadline, user_deadline,
       allocation_state, edge_state, origin_state, terminal_state,
       owner_device_id, owner_session_id, endpoint
FROM preview_leases
WHERE id = $1
  AND account_id = $2
`

type GetPreviewDomainLeaseViewV1Params struct {
	PreviewID string
	AccountID string
}

type GetPreviewDomainLeaseViewV1Row struct {
	ID              string
	AccountID       string
	Generation      int64
	LeaseDeadline   time.Time
	UserDeadline    sql.NullTime
	AllocationState string
	EdgeState       string
	OriginState     string
	TerminalState   string
	OwnerDeviceID   string
	OwnerSessionID  string
	Endpoint        string
}

func (q *Queries) GetPreviewDomainLeaseViewV1(ctx context.Context, arg GetPreviewDomainLeaseViewV1Params) (GetPreviewDomainLeaseViewV1Row, error) {
	row := q.db.QueryRow(ctx, getPreviewDomainLeaseViewV1, arg.PreviewID, arg.AccountID)
	var i GetPreviewDomainLeaseViewV1Row
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Generation,
		&i.LeaseDeadline,
		&i.UserDeadline,
		&i.AllocationState,
		&i.EdgeState,
		&i.OriginState,
		&i.TerminalState,
		&i.OwnerDeviceID,
		&i.OwnerSessionID,
		&i.Endpoint,
	)
	return i, err
}

const getPreviewDomainV1 = `-- name: GetPreviewDomainV1 :one
SELECT id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
FROM preview_domains
WHERE id = $1
  AND account_id = $2
  AND preview_id = $3
  AND deleted_at IS NULL
`

type GetPreviewDomainV1Params struct {
	DomainID  string
	AccountID string
	PreviewID string
}

func (q *Queries) GetPreviewDomainV1(ctx context.Context, arg GetPreviewDomainV1Params) (PreviewDomain, error) {
	row := q.db.QueryRow(ctx, getPreviewDomainV1, arg.DomainID, arg.AccountID, arg.PreviewID)
	var i PreviewDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PreviewID,
		&i.PreviewGeneration,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuarantineUntil,
	)
	return i, err
}

const getPreviewLeaseForDomainV1 = `-- name: GetPreviewLeaseForDomainV1 :one
SELECT id, account_id, generation, lease_deadline, user_deadline,
       allocation_state, edge_state, origin_state, terminal_state
FROM preview_leases
WHERE id = $1
  AND account_id = $2
FOR UPDATE
`

type GetPreviewLeaseForDomainV1Params struct {
	PreviewID string
	AccountID string
}

type GetPreviewLeaseForDomainV1Row struct {
	ID              string
	AccountID       string
	Generation      int64
	LeaseDeadline   time.Time
	UserDeadline    sql.NullTime
	AllocationState string
	EdgeState       string
	OriginState     string
	TerminalState   string
}

func (q *Queries) GetPreviewLeaseForDomainV1(ctx context.Context, arg GetPreviewLeaseForDomainV1Params) (GetPreviewLeaseForDomainV1Row, error) {
	row := q.db.QueryRow(ctx, getPreviewLeaseForDomainV1, arg.PreviewID, arg.AccountID)
	var i GetPreviewLeaseForDomainV1Row
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Generation,
		&i.LeaseDeadline,
		&i.UserDeadline,
		&i.AllocationState,
		&i.EdgeState,
		&i.OriginState,
		&i.TerminalState,
	)
	return i, err
}

const getPreviewLeaseOwnerContextV1 = `-- name: GetPreviewLeaseOwnerContextV1 :one
SELECT id, account_id, generation, lease_deadline, user_deadline,
       allocation_state, edge_state, origin_state, terminal_state,
       owner_device_id, owner_session_id, endpoint
FROM preview_leases
WHERE id = $1
  AND account_id = $2
FOR UPDATE
`

type GetPreviewLeaseOwnerContextV1Params struct {
	PreviewID string
	AccountID string
}

type GetPreviewLeaseOwnerContextV1Row struct {
	ID              string
	AccountID       string
	Generation      int64
	LeaseDeadline   time.Time
	UserDeadline    sql.NullTime
	AllocationState string
	EdgeState       string
	OriginState     string
	TerminalState   string
	OwnerDeviceID   string
	OwnerSessionID  string
	Endpoint        string
}

func (q *Queries) GetPreviewLeaseOwnerContextV1(ctx context.Context, arg GetPreviewLeaseOwnerContextV1Params) (GetPreviewLeaseOwnerContextV1Row, error) {
	row := q.db.QueryRow(ctx, getPreviewLeaseOwnerContextV1, arg.PreviewID, arg.AccountID)
	var i GetPreviewLeaseOwnerContextV1Row
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Generation,
		&i.LeaseDeadline,
		&i.UserDeadline,
		&i.AllocationState,
		&i.EdgeState,
		&i.OriginState,
		&i.TerminalState,
		&i.OwnerDeviceID,
		&i.OwnerSessionID,
		&i.Endpoint,
	)
	return i, err
}

const listDuePreviewDomainsV1 = `-- name: ListDuePreviewDomainsV1 :many
SELECT d.id, d.account_id, d.preview_id, d.preview_generation, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.quarantine_until
FROM preview_domains AS d
JOIN preview_leases AS p
  ON p.id = d.preview_id AND p.account_id = d.account_id
WHERE d.deleted_at IS NULL
  AND p.terminal_state = 'active'
  AND p.generation = d.preview_generation
  AND p.lease_deadline > $1
  AND (p.user_deadline IS NULL OR p.user_deadline > $1)
  AND d.dns_next_check_at <= $1
  AND d.ownership_state IN ('pending','failed','verified')
ORDER BY d.dns_next_check_at, d.id
LIMIT $2
`

type ListDuePreviewDomainsV1Params struct {
	Now      time.Time
	RowLimit int32
}

func (q *Queries) ListDuePreviewDomainsV1(ctx context.Context, arg ListDuePreviewDomainsV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, listDuePreviewDomainsV1, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewDomainProjectionV1 = `-- name: ListPreviewDomainProjectionV1 :many
SELECT id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
FROM preview_domains
WHERE account_id = $1
  AND preview_id = $2
ORDER BY created_at, id
LIMIT $3
`

type ListPreviewDomainProjectionV1Params struct {
	AccountID string
	PreviewID string
	RowLimit  int32
}

func (q *Queries) ListPreviewDomainProjectionV1(ctx context.Context, arg ListPreviewDomainProjectionV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, listPreviewDomainProjectionV1, arg.AccountID, arg.PreviewID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviewDomainsV1 = `-- name: ListPreviewDomainsV1 :many
SELECT id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
FROM preview_domains
WHERE account_id = $1
  AND preview_id = $2
  AND deleted_at IS NULL
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) > (
      $3::timestamptz,
      $4::text
    )
  )
ORDER BY created_at, id
LIMIT $5
`

type ListPreviewDomainsV1Params struct {
	AccountID      string
	PreviewID      string
	AfterCreatedAt sql.NullTime
	AfterID        sql.NullString
	RowLimit       int32
}

func (q *Queries) ListPreviewDomainsV1(ctx context.Context, arg ListPreviewDomainsV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, listPreviewDomainsV1,
		arg.AccountID,
		arg.PreviewID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyPreviewDomainAliasesV1 = `-- name: ListReadyPreviewDomainAliasesV1 :many
SELECT d.id, d.account_id, d.preview_id, d.preview_generation, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.quarantine_until, cert.certificate_reference AS active_certificate_reference,
       cert.certificate_generation AS active_certificate_generation
FROM preview_domains AS d
JOIN preview_leases AS p
  ON p.id = d.preview_id AND p.account_id = d.account_id
JOIN tunnel_certificate_records AS cert
  ON cert.target_kind = 'preview_lease'
 AND cert.account_id = d.account_id
 AND cert.preview_id = d.preview_id
 AND cert.preview_generation = d.preview_generation
 AND cert.hostname = d.hostname
 AND cert.state = 'active'
 AND cert.preview_state = 'active'
 AND cert.certificate_reference = d.certificate_reference
 AND cert.expires_at > $1
WHERE d.account_id = $2
  AND d.preview_id = $3
  AND d.deleted_at IS NULL
  AND d.ownership_state = 'verified'
  AND d.conflict_state = 'clear'
  AND d.certificate_state = 'ready'
  AND d.certificate_reference IS NOT NULL
  AND p.terminal_state = 'active'
  AND p.generation = d.preview_generation
  AND p.lease_deadline > $1
  AND (p.user_deadline IS NULL OR p.user_deadline > $1)
ORDER BY d.hostname, d.id
`

type ListReadyPreviewDomainAliasesV1Params struct {
	Now       time.Time
	AccountID string
	PreviewID string
}

type ListReadyPreviewDomainAliasesV1Row struct {
	ID                            string
	AccountID                     string
	PreviewID                     string
	PreviewGeneration             int64
	Hostname                      string
	MatchType                     string
	OwnershipChallengeReference   string
	OwnershipState                string
	DnsTarget                     string
	ObservedRecords               []byte
	DnsProvider                   string
	ExpectedRecords               []byte
	DnsLastCheckedAt              sql.NullTime
	DnsNextCheckAt                time.Time
	DnsTtlSeconds                 sql.NullInt32
	VerificationAttempts          int32
	CertificateStrategy           string
	CertificateReference          sql.NullString
	CertificateState              string
	CertificateExpiresAt          sql.NullTime
	CertificateRenewalAttemptedAt sql.NullTime
	CertificateFailureCode        sql.NullString
	CaaState                      string
	ConflictState                 string
	LastVerifiedAt                sql.NullTime
	Generation                    int64
	CreatedAt                     time.Time
	UpdatedAt                     time.Time
	DeletedAt                     sql.NullTime
	QuarantineUntil               sql.NullTime
	ActiveCertificateReference    string
	ActiveCertificateGeneration   int64
}

func (q *Queries) ListReadyPreviewDomainAliasesV1(ctx context.Context, arg ListReadyPreviewDomainAliasesV1Params) ([]ListReadyPreviewDomainAliasesV1Row, error) {
	rows, err := q.db.Query(ctx, listReadyPreviewDomainAliasesV1, arg.Now, arg.AccountID, arg.PreviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyPreviewDomainAliasesV1Row
	for rows.Next() {
		var i ListReadyPreviewDomainAliasesV1Row
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
			&i.ActiveCertificateReference,
			&i.ActiveCertificateGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyPreviewDomainsV1 = `-- name: ListReadyPreviewDomainsV1 :many
SELECT d.id, d.account_id, d.preview_id, d.preview_generation, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.quarantine_until
FROM preview_domains AS d
JOIN preview_leases AS p
  ON p.id = d.preview_id AND p.account_id = d.account_id
WHERE d.account_id = $1
  AND d.preview_id = $2
  AND d.deleted_at IS NULL
  AND d.ownership_state = 'verified'
  AND d.conflict_state = 'clear'
  AND d.certificate_state = 'ready'
  AND d.certificate_reference IS NOT NULL
  AND p.terminal_state = 'active'
  AND p.generation = d.preview_generation
  AND p.lease_deadline > $3
  AND (p.user_deadline IS NULL OR p.user_deadline > $3)
ORDER BY d.hostname, d.id
`

type ListReadyPreviewDomainsV1Params struct {
	AccountID string
	PreviewID string
	Now       time.Time
}

func (q *Queries) ListReadyPreviewDomainsV1(ctx context.Context, arg ListReadyPreviewDomainsV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, listReadyPreviewDomainsV1, arg.AccountID, arg.PreviewID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLostPreviewLeaseAndWithdrawDomainsV1 = `-- name: MarkLostPreviewLeaseAndWithdrawDomainsV1 :many
WITH candidates AS (
  SELECT source.id
  FROM preview_leases AS source
  WHERE source.terminal_state = 'active'
    AND source.lease_deadline > $1
    AND source.owner_last_seen_at <= $2
  ORDER BY source.owner_last_seen_at, source.id
  LIMIT $3
  FOR UPDATE SKIP LOCKED
), lost AS (
  UPDATE preview_leases AS p
  SET allocation_state = 'released', edge_state = 'released', terminal_state = 'owner_lost',
      generation = p.generation + 1, stopped_at = $1
  FROM candidates
  WHERE p.id = candidates.id
  RETURNING p.id, p.account_id, p.generation
), withdrawn AS (
  UPDATE preview_domains AS d
  SET ownership_state = 'expired',
      certificate_state = CASE WHEN d.certificate_state = 'not_applicable' THEN 'not_applicable' ELSE 'revoked' END,
      conflict_state = 'quarantined', quarantine_until = $4,
      deleted_at = $1, generation = d.generation + 1, updated_at = $1
  FROM lost
  WHERE d.preview_id = lost.id AND d.account_id = lost.account_id
    AND d.preview_generation < lost.generation AND d.deleted_at IS NULL
  RETURNING d.id
)
SELECT id, account_id, generation FROM lost
`

type MarkLostPreviewLeaseAndWithdrawDomainsV1Params struct {
	Now             time.Time
	OwnerCutoff     time.Time
	RowLimit        int32
	QuarantineUntil sql.NullTime
}

type MarkLostPreviewLeaseAndWithdrawDomainsV1Row struct {
	ID         string
	AccountID  string
	Generation int64
}

func (q *Queries) MarkLostPreviewLeaseAndWithdrawDomainsV1(ctx context.Context, arg MarkLostPreviewLeaseAndWithdrawDomainsV1Params) ([]MarkLostPreviewLeaseAndWithdrawDomainsV1Row, error) {
	rows, err := q.db.Query(ctx, markLostPreviewLeaseAndWithdrawDomainsV1,
		arg.Now,
		arg.OwnerCutoff,
		arg.RowLimit,
		arg.QuarantineUntil,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkLostPreviewLeaseAndWithdrawDomainsV1Row
	for rows.Next() {
		var i MarkLostPreviewLeaseAndWithdrawDomainsV1Row
		if err := rows.Scan(&i.ID, &i.AccountID, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseExpiredPreviewDomainQuarantinesV1 = `-- name: ReleaseExpiredPreviewDomainQuarantinesV1 :execrows
UPDATE preview_domains
SET conflict_state = 'clear', quarantine_until = NULL, updated_at = $1
WHERE deleted_at IS NOT NULL
  AND conflict_state = 'quarantined'
  AND quarantine_until <= $1
`

func (q *Queries) ReleaseExpiredPreviewDomainQuarantinesV1(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, releaseExpiredPreviewDomainQuarantinesV1, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewPreviewLeaseAndAdvanceDomainsV1 = `-- name: RenewPreviewLeaseAndAdvanceDomainsV1 :one
WITH renewed AS (
  UPDATE preview_leases
  SET lease_deadline = $1,
      last_renewed_at = $2,
      owner_last_seen_at = $2,
      generation = generation + 1
  WHERE preview_leases.id = $3
    AND preview_leases.account_id = $4
    AND preview_leases.owner_device_id = $5
    AND preview_leases.owner_session_id = $6
    AND preview_leases.terminal_state = 'active'
    AND preview_leases.generation = $7
    AND (preview_leases.user_deadline IS NULL OR $1 <= preview_leases.user_deadline)
  RETURNING id, account_id, generation
), moved AS (
  UPDATE preview_domains AS d
  SET preview_generation = renewed.generation,
      updated_at = $2
  FROM renewed
  WHERE d.preview_id = renewed.id
    AND d.account_id = renewed.account_id
    AND d.preview_generation = $7
    AND d.deleted_at IS NULL
  RETURNING d.id
)
SELECT renewed.id, renewed.account_id, renewed.generation
FROM renewed
`

type RenewPreviewLeaseAndAdvanceDomainsV1Params struct {
	LeaseDeadline      time.Time
	Now                time.Time
	PreviewID          string
	AccountID          string
	OwnerDeviceID      string
	OwnerSessionID     string
	ExpectedGeneration int64
}

type RenewPreviewLeaseAndAdvanceDomainsV1Row struct {
	ID         string
	AccountID  string
	Generation int64
}

func (q *Queries) RenewPreviewLeaseAndAdvanceDomainsV1(ctx context.Context, arg RenewPreviewLeaseAndAdvanceDomainsV1Params) (RenewPreviewLeaseAndAdvanceDomainsV1Row, error) {
	row := q.db.QueryRow(ctx, renewPreviewLeaseAndAdvanceDomainsV1,
		arg.LeaseDeadline,
		arg.Now,
		arg.PreviewID,
		arg.AccountID,
		arg.OwnerDeviceID,
		arg.OwnerSessionID,
		arg.ExpectedGeneration,
	)
	var i RenewPreviewLeaseAndAdvanceDomainsV1Row
	err := row.Scan(&i.ID, &i.AccountID, &i.Generation)
	return i, err
}

const stopPreviewLeaseAndWithdrawDomainsV1 = `-- name: StopPreviewLeaseAndWithdrawDomainsV1 :one
WITH stopped AS (
  UPDATE preview_leases
  SET allocation_state = 'released',
      edge_state = 'released',
      terminal_state = $1,
      generation = generation + 1,
      stopped_at = $2
  WHERE preview_leases.id = $3
    AND preview_leases.account_id = $4
    AND preview_leases.terminal_state = 'active'
    AND preview_leases.generation = $5
  RETURNING id, account_id, generation
), withdrawn AS (
  UPDATE preview_domains AS d
  SET ownership_state = CASE WHEN $1 = 'owner_lost' THEN 'expired' ELSE 'revoked' END,
      certificate_state = CASE WHEN d.certificate_state = 'not_applicable' THEN 'not_applicable' ELSE 'revoked' END,
      conflict_state = 'quarantined',
      quarantine_until = $6,
      deleted_at = $2,
      generation = d.generation + 1,
      updated_at = $2
  FROM stopped
  WHERE d.preview_id = stopped.id
    AND d.account_id = stopped.account_id
    AND d.preview_generation <= $5
    AND d.deleted_at IS NULL
  RETURNING d.id
)
SELECT stopped.id, stopped.account_id, stopped.generation
FROM stopped
`

type StopPreviewLeaseAndWithdrawDomainsV1Params struct {
	TerminalState      string
	Now                sql.NullTime
	PreviewID          string
	AccountID          string
	ExpectedGeneration int64
	QuarantineUntil    sql.NullTime
}

type StopPreviewLeaseAndWithdrawDomainsV1Row struct {
	ID         string
	AccountID  string
	Generation int64
}

func (q *Queries) StopPreviewLeaseAndWithdrawDomainsV1(ctx context.Context, arg StopPreviewLeaseAndWithdrawDomainsV1Params) (StopPreviewLeaseAndWithdrawDomainsV1Row, error) {
	row := q.db.QueryRow(ctx, stopPreviewLeaseAndWithdrawDomainsV1,
		arg.TerminalState,
		arg.Now,
		arg.PreviewID,
		arg.AccountID,
		arg.ExpectedGeneration,
		arg.QuarantineUntil,
	)
	var i StopPreviewLeaseAndWithdrawDomainsV1Row
	err := row.Scan(&i.ID, &i.AccountID, &i.Generation)
	return i, err
}

const withdrawPreviewDomainsV1 = `-- name: WithdrawPreviewDomainsV1 :many
UPDATE preview_domains
SET ownership_state = 'expired',
    certificate_state = CASE WHEN certificate_state = 'not_applicable' THEN 'not_applicable' ELSE 'revoked' END,
    conflict_state = 'quarantined',
    quarantine_until = $1,
    deleted_at = $2,
    generation = generation + 1,
    updated_at = $2
WHERE preview_id = $3
  AND account_id = $4
  AND preview_generation <= $5
  AND deleted_at IS NULL
RETURNING id, account_id, preview_id, preview_generation, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, quarantine_until
`

type WithdrawPreviewDomainsV1Params struct {
	QuarantineUntil           sql.NullTime
	Now                       sql.NullTime
	PreviewID                 string
	AccountID                 string
	TerminalPreviewGeneration int64
}

func (q *Queries) WithdrawPreviewDomainsV1(ctx context.Context, arg WithdrawPreviewDomainsV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, withdrawPreviewDomainsV1,
		arg.QuarantineUntil,
		arg.Now,
		arg.PreviewID,
		arg.AccountID,
		arg.TerminalPreviewGeneration,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
