// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package dbsqlc

import (
	"context"
)

const createStorageAllocationEntry = `-- name: CreateStorageAllocationEntry :exec
INSERT INTO storage_ledger_entries (id, account_id, entry_type, amount_gb, source_type, source_id, idempotency_key)
VALUES ($1, $2, 'allocation', $3, 'project', $4, $5)
`

type CreateStorageAllocationEntryParams struct {
	ID             string
	AccountID      string
	AmountGb       int32
	SourceID       string
	IdempotencyKey string
}

func (q *Queries) CreateStorageAllocationEntry(ctx context.Context, arg CreateStorageAllocationEntryParams) error {
	_, err := q.db.ExecContext(ctx, createStorageAllocationEntry,
		arg.ID,
		arg.AccountID,
		arg.AmountGb,
		arg.SourceID,
		arg.IdempotencyKey,
	)
	return err
}

const getStorageAccountForUpdate = `-- name: GetStorageAccountForUpdate :one
SELECT least(sa.included_gb, coalesce(limits.pending_included_gb, sa.included_gb))::integer AS included_gb,
       least(sa.purchased_gb, coalesce(limits.pending_purchased_gb, sa.purchased_gb))::integer AS purchased_gb,
       sa.allocated_gb
FROM storage_accounts sa
LEFT JOIN LATERAL (
  SELECT pending_pv.included_storage_gb AS pending_included_gb,
         CASE WHEN s.pending_storage_units IS NULL THEN NULL ELSE
           greatest(0, s.pending_storage_units - coalesce((active_pv.metadata->'billing'->>'storage_seat_offset')::integer,0)) *
           coalesce((active_pv.metadata->'billing'->>'storage_unit_gb')::integer,0)
         END AS pending_purchased_gb
  FROM subscriptions s
  LEFT JOIN plan_versions active_pv ON active_pv.id=s.active_plan_version_id
  LEFT JOIN plan_versions pending_pv ON pending_pv.id=s.pending_plan_version_id
  WHERE s.user_id=sa.user_id AND s.provider='polar' AND s.state IN ('active','trialing')
  ORDER BY s.updated_at DESC LIMIT 1
) limits ON true
WHERE sa.id = $1
FOR UPDATE OF sa
`

type GetStorageAccountForUpdateRow struct {
	IncludedGb  int32
	PurchasedGb int32
	AllocatedGb int32
}

func (q *Queries) GetStorageAccountForUpdate(ctx context.Context, id string) (GetStorageAccountForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getStorageAccountForUpdate, id)
	var i GetStorageAccountForUpdateRow
	err := row.Scan(&i.IncludedGb, &i.PurchasedGb, &i.AllocatedGb)
	return i, err
}

const getStorageLedgerEntryByIdempotencyKey = `-- name: GetStorageLedgerEntryByIdempotencyKey :one
SELECT account_id, entry_type, amount_gb, source_type, source_id
FROM storage_ledger_entries
WHERE idempotency_key = $1
`

type GetStorageLedgerEntryByIdempotencyKeyRow struct {
	AccountID  string
	EntryType  string
	AmountGb   int32
	SourceType string
	SourceID   string
}

func (q *Queries) GetStorageLedgerEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetStorageLedgerEntryByIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getStorageLedgerEntryByIdempotencyKey, idempotencyKey)
	var i GetStorageLedgerEntryByIdempotencyKeyRow
	err := row.Scan(
		&i.AccountID,
		&i.EntryType,
		&i.AmountGb,
		&i.SourceType,
		&i.SourceID,
	)
	return i, err
}

const increaseAllocatedStorage = `-- name: IncreaseAllocatedStorage :exec
UPDATE storage_accounts
SET allocated_gb = allocated_gb + $2, version = version + 1, updated_at = now()
WHERE id = $1
`

type IncreaseAllocatedStorageParams struct {
	ID          string
	AllocatedGb int32
}

func (q *Queries) IncreaseAllocatedStorage(ctx context.Context, arg IncreaseAllocatedStorageParams) error {
	_, err := q.db.ExecContext(ctx, increaseAllocatedStorage, arg.ID, arg.AllocatedGb)
	return err
}
