// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tunnel_certificate_domains_v1.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDuePreviewCertificateDomainsV1 = `-- name: ListDuePreviewCertificateDomainsV1 :many
SELECT d.id, d.account_id, d.preview_id, d.preview_generation, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.quarantine_until
FROM preview_domains AS d
JOIN preview_leases AS lease
  ON lease.id = d.preview_id AND lease.account_id = d.account_id
WHERE d.deleted_at IS NULL
  AND d.ownership_state = 'verified'
  AND d.conflict_state = 'clear'
  AND lease.terminal_state = 'active'
  AND lease.generation = d.preview_generation
  AND lease.lease_deadline > $1
  AND (lease.user_deadline IS NULL OR lease.user_deadline > $1)
  AND (
    d.certificate_state IN ('pending','issuing','renewing','failed')
    OR d.certificate_expires_at <= $1::timestamptz + $2::interval
    OR (
      d.certificate_state = 'ready'
      AND EXISTS (
        SELECT 1
        FROM tunnel_certificate_records AS cert
        WHERE cert.domain_id = d.id
          AND cert.account_id = d.account_id
          AND cert.target_kind = 'preview_lease'
          AND cert.preview_id = d.preview_id
          AND cert.preview_generation = d.preview_generation
          AND cert.certificate_reference = d.certificate_reference
          AND cert.leaf_hostname IS NULL
          AND cert.state = 'active'
          AND cert.expires_at > $1
          AND EXISTS (
            SELECT 1
            FROM preview_lease_carrier_attachments AS attachment
            WHERE attachment.account_id = d.account_id
              AND attachment.preview_id = d.preview_id
              AND attachment.lease_generation = d.preview_generation
              AND attachment.state = 'ready'
              AND attachment.edge_ready
              AND attachment.expires_at > $1
              AND NOT EXISTS (
                SELECT 1
                FROM tunnel_certificate_edge_distributions AS edge_cert
                WHERE edge_cert.certificate_id = cert.id
                  AND edge_cert.edge_node_id = attachment.edge_node_id
                  AND edge_cert.edge_process_epoch = attachment.edge_process_epoch
                  AND edge_cert.edge_assignment_generation = attachment.attachment_generation
                  AND edge_cert.observed_certificate_generation = cert.certificate_generation
                  AND edge_cert.state = 'active'
                  AND edge_cert.updated_at >= cert.updated_at
              )
          )
      )
    )
  )
ORDER BY d.certificate_expires_at NULLS FIRST, d.id
LIMIT $3
`

type ListDuePreviewCertificateDomainsV1Params struct {
	Now         time.Time
	RenewBefore pgtype.Interval
	RowLimit    int32
}

// Preview domains are lease-bound aliases, so their certificate worker uses
// the same DNS/certificate/distribution due rules as durable domains while
// retaining the preview target fence. Lease identity and expiry are resolved
// separately by the worker before issuance.
func (q *Queries) ListDuePreviewCertificateDomainsV1(ctx context.Context, arg ListDuePreviewCertificateDomainsV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, listDuePreviewCertificateDomainsV1, arg.Now, arg.RenewBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTunnelCertificateDomainsV1 = `-- name: ListDueTunnelCertificateDomainsV1 :many
SELECT d.id, d.account_id, d.tunnel_id, d.route_id, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.quarantine_until
FROM tunnel_domains AS d
WHERE d.deleted_at IS NULL
  AND d.ownership_state = 'verified'
  AND d.conflict_state = 'clear'
  AND (
    d.certificate_state IN ('issuing','renewing','failed')
    OR d.certificate_expires_at <= $1::timestamptz + $2::interval
    OR (
      d.certificate_state = 'ready'
      AND EXISTS (
        SELECT 1
        FROM tunnel_certificate_records AS cert
        JOIN tunnel_edge_route_assignments AS a
          ON a.route_id = d.route_id
         AND a.tunnel_id = d.tunnel_id
         AND a.account_id = d.account_id
        WHERE cert.domain_id = d.id
          AND cert.certificate_reference = d.certificate_reference
          AND cert.target_kind = 'durable_route'
          AND cert.leaf_hostname IS NULL
          AND cert.state = 'active'
          AND a.state = 'active'
          AND a.observed_state = 'ready'
          AND NOT EXISTS (
            SELECT 1
            FROM tunnel_certificate_edge_distributions AS edge_cert
            WHERE edge_cert.certificate_id = cert.id
              AND edge_cert.edge_node_id = a.edge_node_id
              AND edge_cert.edge_process_epoch = a.edge_process_epoch
              AND edge_cert.edge_assignment_generation = a.assignment_generation
              AND edge_cert.observed_certificate_generation = cert.certificate_generation
              AND edge_cert.state = 'active'
          )
      )
    )
  )
ORDER BY d.certificate_expires_at NULLS FIRST, d.id
LIMIT $3
`

type ListDueTunnelCertificateDomainsV1Params struct {
	Now         time.Time
	RenewBefore pgtype.Interval
	RowLimit    int32
}

func (q *Queries) ListDueTunnelCertificateDomainsV1(ctx context.Context, arg ListDueTunnelCertificateDomainsV1Params) ([]TunnelDomain, error) {
	rows, err := q.db.Query(ctx, listDueTunnelCertificateDomainsV1, arg.Now, arg.RenewBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TunnelDomain
	for rows.Next() {
		var i TunnelDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TunnelID,
			&i.RouteID,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnDemandPreviewDomainsForEdgeV1 = `-- name: ListOnDemandPreviewDomainsForEdgeV1 :many
SELECT d.id, d.account_id, d.preview_id, d.preview_generation, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.quarantine_until
FROM preview_domains AS d
JOIN preview_leases AS lease
  ON lease.id = d.preview_id AND lease.account_id = d.account_id
JOIN preview_lease_carrier_attachments AS a
  ON a.account_id = d.account_id AND a.preview_id = d.preview_id
 AND a.lease_generation = d.preview_generation
WHERE d.certificate_strategy = 'on_demand_leaf'
  AND d.match_type = 'one_label_wildcard'
  AND d.ownership_state = 'verified'
  AND d.conflict_state = 'clear'
  AND d.certificate_state = 'ready'
  AND d.certificate_reference IS NOT NULL
  AND d.deleted_at IS NULL
  AND lease.terminal_state = 'active'
  AND lease.generation = d.preview_generation
  AND lease.lease_deadline > $1
  AND (lease.user_deadline IS NULL OR lease.user_deadline > $1)
  AND a.edge_node_id = $2
  AND a.edge_process_epoch = $3
  AND a.state = 'ready'
  AND a.edge_ready
  AND a.expires_at > $1
  AND EXISTS (
    SELECT 1
    FROM tunnel_certificate_records AS cert
    WHERE cert.domain_id = d.id
      AND cert.account_id = d.account_id
      AND cert.target_kind = 'preview_lease'
      AND cert.preview_id = d.preview_id
      AND cert.preview_generation = d.preview_generation
      AND cert.certificate_reference = d.certificate_reference
      AND cert.leaf_hostname IS NULL
      AND cert.state = 'active'
      AND cert.expires_at > $1
  )
ORDER BY d.id
LIMIT $4
`

type ListOnDemandPreviewDomainsForEdgeV1Params struct {
	Now              time.Time
	EdgeNodeID       string
	EdgeProcessEpoch string
	RowLimit         int32
}

// Authenticated first-SNI requests may issue an exact leaf only when the
// verified preview wildcard parent and this edge's current ready attachment
// are both present. A preview lease never falls back to a wildcard parent for
// a matcher-marked exact name.
func (q *Queries) ListOnDemandPreviewDomainsForEdgeV1(ctx context.Context, arg ListOnDemandPreviewDomainsForEdgeV1Params) ([]PreviewDomain, error) {
	rows, err := q.db.Query(ctx, listOnDemandPreviewDomainsForEdgeV1,
		arg.Now,
		arg.EdgeNodeID,
		arg.EdgeProcessEpoch,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreviewDomain
	for rows.Next() {
		var i PreviewDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PreviewID,
			&i.PreviewGeneration,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnDemandWildcardDomainsForEdgeV1 = `-- name: ListOnDemandWildcardDomainsForEdgeV1 :many
SELECT d.id, d.account_id, d.tunnel_id, d.route_id, d.hostname, d.match_type, d.ownership_challenge_reference, d.ownership_state, d.dns_target, d.observed_records, d.certificate_strategy, d.certificate_reference, d.certificate_state, d.certificate_expires_at, d.certificate_renewal_attempted_at, d.certificate_failure_code, d.caa_state, d.conflict_state, d.last_verified_at, d.generation, d.created_at, d.updated_at, d.deleted_at, d.dns_provider, d.expected_records, d.dns_last_checked_at, d.dns_next_check_at, d.dns_ttl_seconds, d.verification_attempts, d.quarantine_until
FROM tunnel_domains AS d
JOIN tunnel_edge_route_assignments AS a
  ON a.route_id = d.route_id
 AND a.tunnel_id = d.tunnel_id
 AND a.account_id = d.account_id
WHERE d.certificate_strategy = 'on_demand_leaf'
  AND d.match_type = 'one_label_wildcard'
  AND d.ownership_state = 'verified'
  AND d.conflict_state = 'clear'
  AND d.certificate_state = 'ready'
  AND d.certificate_reference IS NOT NULL
  AND d.deleted_at IS NULL
  AND a.edge_node_id = $1
  AND a.edge_process_epoch = $2
  AND a.state = 'active'
  AND a.observed_state = 'ready'
  AND EXISTS (
    SELECT 1
    FROM tunnel_certificate_records AS cert
    WHERE cert.domain_id = d.id
      AND cert.certificate_reference = d.certificate_reference
      AND cert.target_kind = 'durable_route'
      AND cert.leaf_hostname IS NULL
      AND cert.state = 'active'
  )
ORDER BY d.id
LIMIT $3
`

type ListOnDemandWildcardDomainsForEdgeV1Params struct {
	EdgeNodeID       string
	EdgeProcessEpoch string
	RowLimit         int32
}

func (q *Queries) ListOnDemandWildcardDomainsForEdgeV1(ctx context.Context, arg ListOnDemandWildcardDomainsForEdgeV1Params) ([]TunnelDomain, error) {
	rows, err := q.db.Query(ctx, listOnDemandWildcardDomainsForEdgeV1, arg.EdgeNodeID, arg.EdgeProcessEpoch, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TunnelDomain
	for rows.Next() {
		var i TunnelDomain
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TunnelID,
			&i.RouteID,
			&i.Hostname,
			&i.MatchType,
			&i.OwnershipChallengeReference,
			&i.OwnershipState,
			&i.DnsTarget,
			&i.ObservedRecords,
			&i.CertificateStrategy,
			&i.CertificateReference,
			&i.CertificateState,
			&i.CertificateExpiresAt,
			&i.CertificateRenewalAttemptedAt,
			&i.CertificateFailureCode,
			&i.CaaState,
			&i.ConflictState,
			&i.LastVerifiedAt,
			&i.Generation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DnsProvider,
			&i.ExpectedRecords,
			&i.DnsLastCheckedAt,
			&i.DnsNextCheckAt,
			&i.DnsTtlSeconds,
			&i.VerificationAttempts,
			&i.QuarantineUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyPreviewCertificateEdgesV1 = `-- name: ListReadyPreviewCertificateEdgesV1 :many
SELECT a.edge_node_id, a.edge_process_epoch, a.attachment_generation
FROM preview_lease_carrier_attachments AS a
JOIN preview_leases AS lease
  ON lease.id = a.preview_id AND lease.account_id = a.account_id
JOIN preview_domains AS d
  ON d.preview_id = lease.id AND d.account_id = lease.account_id
WHERE d.id = $1
  AND a.state = 'ready'
  AND a.edge_ready
  AND a.expires_at > $2
  AND lease.terminal_state = 'active'
  AND lease.generation = d.preview_generation
  AND lease.lease_deadline > $2
  AND (lease.user_deadline IS NULL OR lease.user_deadline > $2)
ORDER BY a.edge_node_id, a.edge_process_epoch, a.attachment_generation
`

type ListReadyPreviewCertificateEdgesV1Params struct {
	DomainID string
	Now      time.Time
}

type ListReadyPreviewCertificateEdgesV1Row struct {
	EdgeNodeID           string
	EdgeProcessEpoch     string
	AttachmentGeneration int64
}

// Current ready preview attachment tuples are the distribution targets for a
// preview certificate. The attachment generation is used as the assignment
// fence because preview carriers do not have durable route assignments.
func (q *Queries) ListReadyPreviewCertificateEdgesV1(ctx context.Context, arg ListReadyPreviewCertificateEdgesV1Params) ([]ListReadyPreviewCertificateEdgesV1Row, error) {
	rows, err := q.db.Query(ctx, listReadyPreviewCertificateEdgesV1, arg.DomainID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyPreviewCertificateEdgesV1Row
	for rows.Next() {
		var i ListReadyPreviewCertificateEdgesV1Row
		if err := rows.Scan(&i.EdgeNodeID, &i.EdgeProcessEpoch, &i.AttachmentGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyTunnelCertificateEdgesV1 = `-- name: ListReadyTunnelCertificateEdgesV1 :many
SELECT a.edge_node_id, a.edge_process_epoch, a.assignment_generation
FROM tunnel_edge_route_assignments AS a
JOIN tunnel_domains AS d ON d.route_id = a.route_id AND d.tunnel_id = a.tunnel_id AND d.account_id = a.account_id
WHERE d.id = $1
  AND a.state = 'active'
  AND a.observed_state = 'ready'
ORDER BY a.edge_node_id, a.edge_process_epoch, a.assignment_generation
`

type ListReadyTunnelCertificateEdgesV1Row struct {
	EdgeNodeID           string
	EdgeProcessEpoch     string
	AssignmentGeneration int64
}

func (q *Queries) ListReadyTunnelCertificateEdgesV1(ctx context.Context, domainID string) ([]ListReadyTunnelCertificateEdgesV1Row, error) {
	rows, err := q.db.Query(ctx, listReadyTunnelCertificateEdgesV1, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReadyTunnelCertificateEdgesV1Row
	for rows.Next() {
		var i ListReadyTunnelCertificateEdgesV1Row
		if err := rows.Scan(&i.EdgeNodeID, &i.EdgeProcessEpoch, &i.AssignmentGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTunnelDomainCertificateFailureV1 = `-- name: MarkTunnelDomainCertificateFailureV1 :one
UPDATE tunnel_domains
SET certificate_state = CASE WHEN certificate_state = 'ready' THEN 'renewing' ELSE 'failed' END,
    certificate_renewal_attempted_at = $1,
    certificate_failure_code = $2,
    generation = generation + 1,
    updated_at = $1
WHERE id = $3
  AND generation = $4
  AND ownership_state = 'verified'
  AND deleted_at IS NULL
RETURNING id, account_id, tunnel_id, route_id, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, quarantine_until
`

type MarkTunnelDomainCertificateFailureV1Params struct {
	Now                sql.NullTime
	FailureCode        sql.NullString
	DomainID           string
	ExpectedGeneration int64
}

func (q *Queries) MarkTunnelDomainCertificateFailureV1(ctx context.Context, arg MarkTunnelDomainCertificateFailureV1Params) (TunnelDomain, error) {
	row := q.db.QueryRow(ctx, markTunnelDomainCertificateFailureV1,
		arg.Now,
		arg.FailureCode,
		arg.DomainID,
		arg.ExpectedGeneration,
	)
	var i TunnelDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TunnelID,
		&i.RouteID,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.QuarantineUntil,
	)
	return i, err
}

const markTunnelDomainCertificateReadyV1 = `-- name: MarkTunnelDomainCertificateReadyV1 :one
UPDATE tunnel_domains
SET certificate_state = 'ready',
    certificate_reference = $1,
    certificate_expires_at = $2,
    certificate_renewal_attempted_at = $3,
    certificate_failure_code = NULL,
    caa_state = 'ready',
    generation = generation + 1,
    updated_at = $3
WHERE id = $4
  AND generation = $5
  AND ownership_state = 'verified'
  AND conflict_state = 'clear'
  AND deleted_at IS NULL
RETURNING id, account_id, tunnel_id, route_id, hostname, match_type, ownership_challenge_reference, ownership_state, dns_target, observed_records, certificate_strategy, certificate_reference, certificate_state, certificate_expires_at, certificate_renewal_attempted_at, certificate_failure_code, caa_state, conflict_state, last_verified_at, generation, created_at, updated_at, deleted_at, dns_provider, expected_records, dns_last_checked_at, dns_next_check_at, dns_ttl_seconds, verification_attempts, quarantine_until
`

type MarkTunnelDomainCertificateReadyV1Params struct {
	CertificateReference sql.NullString
	CertificateExpiresAt sql.NullTime
	Now                  sql.NullTime
	DomainID             string
	ExpectedGeneration   int64
}

func (q *Queries) MarkTunnelDomainCertificateReadyV1(ctx context.Context, arg MarkTunnelDomainCertificateReadyV1Params) (TunnelDomain, error) {
	row := q.db.QueryRow(ctx, markTunnelDomainCertificateReadyV1,
		arg.CertificateReference,
		arg.CertificateExpiresAt,
		arg.Now,
		arg.DomainID,
		arg.ExpectedGeneration,
	)
	var i TunnelDomain
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TunnelID,
		&i.RouteID,
		&i.Hostname,
		&i.MatchType,
		&i.OwnershipChallengeReference,
		&i.OwnershipState,
		&i.DnsTarget,
		&i.ObservedRecords,
		&i.CertificateStrategy,
		&i.CertificateReference,
		&i.CertificateState,
		&i.CertificateExpiresAt,
		&i.CertificateRenewalAttemptedAt,
		&i.CertificateFailureCode,
		&i.CaaState,
		&i.ConflictState,
		&i.LastVerifiedAt,
		&i.Generation,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DnsProvider,
		&i.ExpectedRecords,
		&i.DnsLastCheckedAt,
		&i.DnsNextCheckAt,
		&i.DnsTtlSeconds,
		&i.VerificationAttempts,
		&i.QuarantineUntil,
	)
	return i, err
}
